/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../../mock-server/MockServerPool";
import { SquareClient } from "../../../src/Client";

describe("TeamMemberWages", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            team_member_wage: {
                id: "pXS3qCv7BERPnEGedM4S8mhm",
                team_member_id: "33fJchumvVdJwxV0H6L9",
                title: "Manager",
                hourly_rate: { amount: BigInt(2000), currency: "USD" },
                job_id: "jxJNN6eCJsLrhg5UFJrDWDGE",
                tip_eligible: false,
            },
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
        };
        server
            .mockEndpoint()
            .get("/v2/labor/team-member-wages/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.labor.teamMemberWages.get({
            id: "id",
        });
        expect(response).toEqual({
            teamMemberWage: {
                id: "pXS3qCv7BERPnEGedM4S8mhm",
                teamMemberId: "33fJchumvVdJwxV0H6L9",
                title: "Manager",
                hourlyRate: {
                    amount: BigInt("2000"),
                    currency: "USD",
                },
                jobId: "jxJNN6eCJsLrhg5UFJrDWDGE",
                tipEligible: false,
            },
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
        });
    });
});
