// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";
import { BulkUpdateCustomerData } from "../../../../types/BulkUpdateCustomerData";

export const BulkUpdateCustomersRequest: core.serialization.Schema<
    serializers.BulkUpdateCustomersRequest.Raw,
    Square.BulkUpdateCustomersRequest
> = core.serialization.object({
    customers: core.serialization.record(core.serialization.string(), BulkUpdateCustomerData),
});

export declare namespace BulkUpdateCustomersRequest {
    export interface Raw {
        customers: Record<string, BulkUpdateCustomerData.Raw>;
    }
}
