/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         location_id: "location_id",
 *         transaction_id: "transaction_id"
 *     }
 */
export interface CaptureTransactionsRequest {
    /**
     *
     */
    location_id: string;
    /**
     *
     */
    transaction_id: string;
}
