{
  "openapi": "3.0.0",
  "info": {
    "version": "2.0",
    "title": "Square",
    "description": "Use Square APIs to manage and run business including payment, customer, product, inventory, and employee management.",
    "termsOfService": "https://connect.squareup.com/tos",
    "contact": {
      "name": "Square Developer Platform",
      "email": "developers@squareup.com",
      "url": "https://squareup.com/developers"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "x-server-configuration": {
      "default-environment": "production",
      "default-server": "default",
      "environments": [
        {
          "name": "production",
          "servers": [
            {
              "name": "default",
              "url": "https://connect.squareup.com"
            }
          ]
        },
        {
          "name": "sandbox",
          "servers": [
            {
              "name": "default",
              "url": "https://connect.squareupsandbox.com"
            }
          ]
        },
        {
          "name": "custom",
          "servers": [
            {
              "name": "default",
              "url": "{custom_url}"
            }
          ]
        }
      ]
    },
    "x-square-generic-error-codes": [
      "ACCESS_TOKEN_EXPIRED",
      "ACCESS_TOKEN_REVOKED",
      "API_VERSION_INCOMPATIBLE",
      "APPLICATION_DISABLED",
      "ARRAY_EMPTY",
      "ARRAY_LENGTH_TOO_LONG",
      "ARRAY_LENGTH_TOO_SHORT",
      "BAD_CERTIFICATE",
      "BAD_GATEWAY",
      "BAD_REQUEST",
      "CONFLICT",
      "CONFLICTING_PARAMETERS",
      "CURRENCY_MISMATCH",
      "EXPECTED_ARRAY",
      "EXPECTED_BASE64_ENCODED_BYTE_ARRAY",
      "EXPECTED_BOOLEAN",
      "EXPECTED_FLOAT",
      "EXPECTED_INTEGER",
      "EXPECTED_JSON_BODY",
      "EXPECTED_MAP",
      "EXPECTED_OBJECT",
      "EXPECTED_STRING",
      "FORBIDDEN",
      "GATEWAY_TIMEOUT",
      "GONE",
      "IDEMPOTENCY_KEY_REUSED",
      "INCORRECT_TYPE",
      "INSUFFICIENT_SCOPES",
      "INTERNAL_SERVER_ERROR",
      "INVALID_ARRAY_VALUE",
      "INVALID_CONTENT_TYPE",
      "INVALID_CURSOR",
      "INVALID_ENUM_VALUE",
      "INVALID_FORM_VALUE",
      "INVALID_SORT_ORDER",
      "INVALID_SQUARE_VERSION_FORMAT",
      "INVALID_TIME",
      "INVALID_TIME_RANGE",
      "INVALID_VALUE",
      "LOCATION_MISMATCH",
      "MAP_KEY_LENGTH_TOO_LONG",
      "MAP_KEY_LENGTH_TOO_SHORT",
      "MERCHANT_SUBSCRIPTION_NOT_FOUND",
      "METHOD_NOT_ALLOWED",
      "MISSING_REQUIRED_PARAMETER",
      "NOT_ACCEPTABLE",
      "NOT_FOUND",
      "NOT_IMPLEMENTED",
      "NO_FIELDS_SET",
      "RATE_LIMITED",
      "REQUEST_ENTITY_TOO_LARGE",
      "REQUEST_TIMEOUT",
      "SANDBOX_NOT_SUPPORTED",
      "SERVICE_UNAVAILABLE",
      "TOO_MANY_MAP_ENTRIES",
      "UNAUTHORIZED",
      "UNEXPECTED_VALUE",
      "UNKNOWN_BODY_PARAMETER",
      "UNKNOWN_QUERY_PARAMETER",
      "UNPROCESSABLE_ENTITY",
      "UNSUPPORTED_MEDIA_TYPE",
      "V1_ACCESS_TOKEN",
      "V1_APPLICATION",
      "VALUE_EMPTY",
      "VALUE_REGEX_MISMATCH",
      "VALUE_TOO_HIGH",
      "VALUE_TOO_LONG",
      "VALUE_TOO_LOW",
      "VALUE_TOO_SHORT"
    ]
  },
  "servers": [
    {
      "url": "https://connect.squareup.com",
      "variables": {}
    }
  ],
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "x-additional-headers": [
          {
            "name": "Square-Version",
            "description": "Square Connect API versions",
            "schema": {
              "default": "2025-07-16"
            }
          }
        ],
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://connect.squareup.com/oauth2/authorize",
            "tokenUrl": "https://connect.squareup.com/oauth2/token",
            "scopes": {
              "ADDON_CONFIGURATIONS_READ": "__HTTP Method__: `GET`\n\nGrants write access for third-party Add-ons to read configurations of their Add-ons, for example, when calling `RetrieveConfiguration` endpoint.",
              "ADDON_CONFIGURATIONS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access for third-party Add-ons to store configurations of their Add-ons, for example, when calling `CreateConfiguration` endpoint.",
              "APPOINTMENTS_ALL_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to all of a seller's booking information, calendar, and business details.\nThis permission must be accompanied by the `APPOINTMENTS_READ` permission.",
              "APPOINTMENTS_ALL_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to all booking details, including double-booking a seller.\nThis permission must be accompanied by the `APPOINTMENTS_WRITE` permission.",
              "APPOINTMENTS_BUSINESS_SETTINGS_READ": "__HTTP Method__: `GET`\n\nGrants read access to booking business settings. For example, to call the\nListTeamMemberBookingProfiles endpoint.",
              "APPOINTMENTS_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to booking information. For example, to call the\nRetrieveBooking endpoint.",
              "APPOINTMENTS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to booking information. For example, to call the CreateBooking endpoint.",
              "BANK_ACCOUNTS_READ": "__HTTP Method__: `GET`\n\nGrants read access to bank account information associated with the targeted\nSquare account. For example, to call the Connect v1 ListBankAccounts endpoint.",
              "CASH_DRAWER_READ": "__HTTP Method__: `GET`\n\nGrants read access to cash drawer shift information. For example, to call the\nListCashDrawerShifts endpoint.",
              "CHANNELS_CREATE": "__HTTP Method__: `POST`\n\nGrants write access to create channels, for example, when calling the\n`CreateChannel` endpoint.",
              "CHANNELS_READ": "__HTTP Method__: `GET`\n\nGrants read access to view channels, for example, when calling the\n`RetrieveChannel` endpoint.",
              "CHANNELS_UPDATE": "__HTTP Method__: `PUT`\n\nGrants write access to update channels, for example, when calling the\n`UpdateChannel` endpoint.",
              "CUSTOMERS_READ": "__HTTP Method__: `GET`\n\nGrants read access to customer information. For example, to call the\nListCustomers endpoint.",
              "CUSTOMERS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to customer information. For example, to create and update\ncustomer profiles.",
              "DEVICES_READ": "__HTTP Method__: `GET`\n\nGrants read access to device information. For example, to\ncall the `GetDevice` and `ListDevices` endpoints.",
              "DEVICE_CREDENTIAL_MANAGEMENT": "__HTTP Method__: `POST`, `GET`\n\nGrants read/write access to device credentials information. For example, to\ncall the CreateDeviceCode endpoint.",
              "DISCOUNT_CODES_READ": "__HTTP Method__: `GET`\n\nGrants read access to Discount Codes API. For example, to call the `RetrieveDiscountCode` and `RetrieveRedemption` endpoints.",
              "DISCOUNT_CODES_WRITE": "__HTTP Method__: `POST`\n\nGrants write access to Discount Codes API.",
              "DISPUTES_READ": "__HTTP Method__: `GET`\n\nGrants read access to dispute information. For example, to call the RetrieveDispute\nendpoint.",
              "DISPUTES_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to dispute information. For example, to call the SubmitEvidence\nendpoint.",
              "EMPLOYEES_READ": "__HTTP Method__: `GET`\n\nGrants read access to employee profile information. For example, to call the\nConnect v1 Employees API.",
              "EMPLOYEES_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to employee profile information. For example, to create\nand modify employee profiles.",
              "GIFTCARDS_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to gift card information. For example, to call the RetrieveGiftCard\nendpoint.",
              "GIFTCARDS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to gift card information. For example, to call the CreateGiftCard\nendpoint.",
              "INVENTORY_READ": "__HTTP Method__: `GET`\n\nGrants read access to inventory information. For example, to call the\nRetrieveInventoryCount endpoint.",
              "INVENTORY_WRITE": "__HTTP Method__:  `POST`, `PUT`, `DELETE`\n\nGrants write access to inventory information. For example, to call the\nBatchChangeInventory endpoint.",
              "INVOICES_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to invoice information. For example, to call the ListInvoices endpoint.",
              "INVOICES_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to invoice information. For example, to call the CreateInvoice endpoint.",
              "ITEMS_READ": "__HTTP Method__: `GET`\n\nGrants read access to product catalog information. For example, to obtain objects in a product catalog.",
              "ITEMS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to product catalog information. For example, to modify or\nadd to a product catalog.",
              "LOYALTY_READ": "__HTTP Method__: `GET`\n\nGrants read access to loyalty information. For example, to call the\nListLoyaltyPrograms endpoint.",
              "LOYALTY_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to loyalty information. For example, to call the\nCreateLoyaltyAccount endpoint.",
              "MERCHANT_PROFILE_READ": "__HTTP Method__: `GET`\n\nGrants read access to business and location information. For example, to\nobtain a location ID for subsequent activity.",
              "MERCHANT_PROFILE_WRITE": "__HTTP Method__: `POST`, `PUT`\n\nGrants write access to business and location information. For example, to create a new location or\nupdate the business hours at an existing location.",
              "ONLINE_STORE_SITE_READ": "__HTTP Method__: `GET`, `POST`\n\nRead access to ECOM online store site details.",
              "ONLINE_STORE_SNIPPETS_READ": "__HTTP Method__: `GET`, `POST`\n\nRead access to ECOM online store snippets on published websites.",
              "ONLINE_STORE_SNIPPETS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nWrite access to ECOM online store snippets on published websites.",
              "ORDERS_READ": "__HTTP Method__: `GET`\n\nGrants read access to order information. For example, to call the\nBatchRetrieveOrders endpoint.",
              "ORDERS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to order information. For example, to call the\nCreateCheckout endpoint.",
              "PAYMENTS_READ": "__HTTP Method__: `GET`\n\nGrants read access to transaction and refund information. For example, to call\nthe RetrieveTransaction endpoint.",
              "PAYMENTS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to transaction and refunds information. For example, to\nprocess payments with the Payments or Checkout API.",
              "PAYMENTS_WRITE_ADDITIONAL_RECIPIENTS": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nAllow third party applications to deduct a portion of each transaction amount.\n__Required__ to use multiparty transaction functionality with the Payments\nAPI.",
              "PAYMENTS_WRITE_IN_PERSON": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to payments and refunds information. For example, to\nprocess in-person payments.",
              "PAYMENTS_WRITE_SHARED_ONFILE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nAllows the developer to process payments on behalf of a seller using a shared on file payment method.",
              "PAYOUTS_READ": "__HTTP Method__: `GET`\n\nGrants read access to payouts and payout entries information. For example,\nto call the Connect v2 `ListPayouts` endpoint.",
              "PERMISSION_SETS_READ": "__HTTP Method__: `GET`\n\nGrants read access to Permission Sets. For example, to\ncall the `ListPermissionSets` and `RetrievePermissionSet` endpoints.",
              "PERMISSION_SETS_WRITE": "__HTTP Method__: `PUT`\n\nGrants write access to Permission Sets.",
              "RESERVATIONS_READ": "__HTTP Method__: `GET`\n\nGrants read access to reservation information, for example, when calling the\n`RetrieveReservation` endpoint.",
              "RESERVATIONS_WRITE": "__HTTP Method__:  `POST`, `PUT`, `DELETE`\n\nGrants write access to reservation information, for example, when calling the\n`CreateReservation` endpoint.",
              "RESTAURANT_CHECKS_READ": "__HTTP Method__: `GET`\n\nGrants read access to check information, for example, when calling the\n`RetrieveCheck` endpoint.",
              "SETTLEMENTS_READ": "__HTTP Method__: `GET`\n\nGrants read access to settlement (deposit) information. For example, to call\nthe Connect v1 ListSettlements endpoint.",
              "SUBSCRIPTIONS_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to subscription information. For example, to call the RetrieveSubscription\nendpoint.",
              "SUBSCRIPTIONS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to subscription information. For example, to call the CreateSubscription\nendpoint.",
              "TIMECARDS_READ": "__HTTP Method__: `GET`\n\nGrants read access to employee timecard information. For example, to call the\nConnect v2 SearchShifts endpoint.",
              "TIMECARDS_SETTINGS_READ": "__HTTP Method__: `GET`\n\nGrants read access to employee timecard settings information. For example, to\ncall the GetBreakType endpoint.",
              "TIMECARDS_SETTINGS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to employee timecard settings information. For example, to\ncall the UpdateBreakType endpoint.",
              "TIMECARDS_WRITE": "__HTTP Method__: `POST`, `PUT`, `DELETE`\n\nGrants write access to employee shift information. For example, to create\nand modify employee shifts.",
              "VENDOR_READ": "__HTTP Method__: `GET`, `POST`\n\nGrants read access to vendor information, for example, when calling the\n`RetrieveVendor` endpoint.",
              "VENDOR_WRITE": "__HTTP Method__:  `POST`, `PUT`, `DELETE`\n\nGrants write access to vendor information, for example, when calling the\n`BulkUpdateVendors` endpoint."
            }
          }
        }
      },
      "oauth2ClientSecret": {
        "type": "apiKey",
        "in": "header",
        "name": "Authorization"
      }
    },
    "x-apis": {
      "ApplePay": {
        "name": "Apple Pay",
        "summary": "Apple Pay support APIs",
        "description": "\nThe Apple Pay APIs provides an easy way for platform developers\nto bulk activate Web Apple Pay with Square for merchants using their platform.\n\nFor more information, see the following guides:\n- [Web Payments SDK](https://developer.squareup.com/docs/web-payments/apple-pay)\n- [In-App Payments SDK](https://developer.squareup.com/docs/in-app-payments-sdk/add-digital-wallets/apple-pay)"
      },
      "BankAccounts": {
        "name": "Bank Accounts",
        "summary": "Get a list of a seller's bank accounts.",
        "description": "\nThe Bank Accounts API allows you to get basic details about a seller's bank account, such as the\nlast few digits of the account number and the routing number. It can be paired with the Payouts API to understand the\npattern of deposits and withdrawals from a seller's bank account.\n\nFor more information, see the following guides:\n - [Bank Accounts](https://developer.squareup.com/docs/bank-accounts-api)\n - [Square Webhooks Overview](https://developer.squareup.com/doc[...]"
      },
      "BookingCustomAttributes": {
        "name": "Booking Custom Attributes",
        "summary": "Create and manage booking-related custom attribute definitions and custom attributes.",
        "description": "\nUse the Booking Custom Attributes API to create and manage custom attributes for bookings to store properties or \nmetadata to support seller-specific customizations of and extensions to the `Booking` object. \n\nFor more information, see the following guides: \n - [Booking Custom Attributes](https://developer.squareup.com/docs/booking-custom-attributes-api/overview).\n - [Square Webhooks Overview](https://developer.squareup.com/docs/webhooks-overview)\n"
      },
      "Bookings": {
        "name": "Bookings",
        "summary": "Create and manage bookings for Square sellers with the Bookings API.",
        "description": "\nThe Bookings API allows you to create, retrieve, update, and cancel appointments online. When used with other Square APIs (such as the Locations API, Team API, Catalog API, and Customers API), the Bookings API lets you create online-booking applications for users to book services provided by Square sellers.   \n\n\n## Why Use the Bookings API?\nThe Bookings API simplifies the scheduling process for Square sellers and their customers. By integrating with Square’s broader[...]"
      },
      "Cards": {
        "name": "Cards",
        "summary": "Use the Cards API to save a credit or debit card on file.",
        "description": "\nYou can use the [CreateCard](/reference/square/cards-api/create-card) endpoint to save a credit or debit card to a Square account.\nDevelopers can integrate the Cards API in their application to let Square sellers:\n\n- **Save a card that can be charged by any Square seller who uses your application.** Your application specifies the organization access token in the `CreateCard` request.\n- **Save a card that can be charged by a single Square seller.**  Your application [...]"
      },
      "CashDrawers": {
        "name": "Cash Drawers",
        "summary": "Get details about cash drawer shifts.",
        "description": "\nCash drawer shifts track cash transactions so that the total money in the cash drawers can be reconciled for a\nspecific period of time (a cash drawer shift), for a particular device, in a particular location. The Cash Drawer Shifts API\nenables you to list and retrieve information about cash drawer shifts.\n\nFor more information, see the following guide:\n - [Cash Drawer Shifts](https://developer.squareup.com/docs/cashdrawershift-api/reporting)"
      },
      "Catalog": {
        "name": "Catalog",
        "summary": "Programmatically catalogs a Square seller’s products for sale and services for hire.",
        "description": "\nThe Catalog API allows you to programmatically catalog products or services, including items, variations, categories, discounts, taxes, modifiers, and more.\n\nFor more information, see the following guides:\n - [Catalog](https://developer.squareup.com/docs/catalog-api/what-it-does)\n - [Square Webhooks Overview](https://developer.squareup.com/docs/webhooks-overview)"
      },
      "Checkout": {
        "name": "Checkout",
        "summary": "Accept payments through a pre-built, Square-hosted checkout page. No frontend required.",
        "description": "\nWith the Square Checkout API, your customers can pay for a purchase through a simple, Square-hosted checkout page. It can be integrated into any payments workflow with minimal coding. \n\nYou can create and configure your checkout page through a `CreatePaymentLink` request, specifying the accepted payment methods and checkout options like tipping and custom fields.  You can also configure a URL for customers to be redirected to once they complete their purchase. \n\nFir[...]"
      },
      "CustomerCustomAttributes": {
        "name": "Customer Custom Attributes",
        "summary": "Create and manage customer-related custom attribute definitions and custom attributes.",
        "description": "\nUse the Customer Custom Attributes API to create and manage custom attributes for customer profiles. Custom attributes can be used to store properties or metadata that simplify integration, synchronization, and personalization workflows. After a custom attribute definition is created in a Square seller account, the custom attribute value can be set for customer profiles in the seller's Customer Directory.\n\nFor more information, see the following guides:\n - [Customer [...]"
      },
      "CustomerGroups": {
        "name": "Customer Groups",
        "summary": "Create and manage customer groups to streamline and automate workflows and help personalize customer interactions.",
        "description": "\nThe Customer Groups API lets you create and manage customer groups to provide targeted promotions or take other customized actions based on group membership. For example, you can create Weekly, Monthly, and Quarterly customer groups and add customers to them based on their preferences to receive marketing promotions on a weekly, monthly, and quarterly basis. You can then use the information to manage your marketing email schedule. \n\nYou can use the Customer Groups API[...]"
      },
      "CustomerSegments": {
        "name": "Customer Segments",
        "summary": "Retrieve customer segments (also called smart groups) in a business account.",
        "description": "\nThe Customer Segments API lets you retrieve information about the segments defined for a business. Square sellers can create customer segments in the Seller Dashboard or Point of Sale by defining filters for the segment. For example, a segment can include customers who have visited more than 10 times. Customers are automatically added to and removed from the segment over time based on this criterion. \n\nYou can inspect the customer's `segment_ids` property to determine[...]"
      },
      "Customers": {
        "name": "Customers",
        "summary": "Create and manage customer profiles and sync CRM systems with Square.",
        "description": "\nThe Customers API enables you to create and manage customer profiles, as well as search for customers based on various criteria (including customer group membership). You can also use the API to sync contacts between your CRM system and Square.\n\nFor more information, see the following guides:\n - [Customers](https://developer.squareup.com/docs/customers-api/what-it-does)\n - [Square Webhooks Overview](https://developer.squareup.com/docs/webhooks-overview)"
      },
      "Devices": {
        "name": "Devices",
        "summary": "Create device codes used to connect Square Terminal with a 3rd-party point of sale system, and get details about all connected Terminals. ",
        "description": "\nFor more information, see the following guides:\n - [Devices](https://developer.squareup.com/docs/terminal-api/overview)\n - [Square Webhooks Overview](https://developer.squareup.com/docs/webhooks-overview)"
      },
      "Disputes": {
        "name": "Disputes",
        "summary": "Use the Disputes API to manage disputes (chargebacks).",
        "description": "\nA seller has the following options to process a dispute:\n\n- Accept the dispute using the [AcceptDispute](/reference/square/disputes-api/accept-dispute) endpoint. Square returns the disputed amount from the account balance of the Square account.\n- Challenge the dispute using the [SubmitEvidence](/reference/square/disputes-api/submit-evidence) endpoint. If the payment was valid, you can contest the disputed payment.\nYou submit supporting evidence you have about the tr[...]"
      },
      "Employees": {
        "name": "Employees",
        "summary": "Pull employee data into accounting and payroll systems with the Employees API.",
        "description": "\nThe Employees API allows applications to retrieve a roster of employees registered in the Square Point\nof Sale system, which can be useful in payroll and account contexts.\n\nPrior to 2020-08-26, the Employees API was best used in conjunction with the Labor API, where you provide employee IDs to\nmanage shifts, breaks, and wages. After that deprecation date, the Team API should be used.\n\nFor information about migrating your code to the Team API, see [Migrate from the[...]"
      },
      "Events": {
        "name": "Events",
        "summary": "Search for Square API events that occur within a 28-day timeframe.",
        "description": "\nIf you don't need a real-time response to data changes or need a disaster recovery or reconciliation mechanism for missed webhook events (caused by server outages, misconfigured webhook subscriptions, network errors, and other events), you can use the Events API instead of webhook subscriptions managed manually or through the Webhook Subscriptions API.\n\nBecause Square events are owned by the application and not any one seller, you cannot use OAuth access tokens with t[...]"
      },
      "GiftCardActivities": {
        "name": "Gift Card Activities",
        "summary": "Create and retrieve gift card activities.",
        "description": "\nUse the Gift Card Activities API to create activities for a Square gift card (such as activating or reloading the gift card) and to track gift card activities. The Gift Card Activities API is used with the [Gift Cards API](https://developer.squareup.com/reference/square/gift-cards-api) to manage the gift card program for a Square seller.\n\nFor more information, see the following guides:\n - [Gift Card Activities](https://developer.squareup.com/docs/gift-cards/using-gif[...]"
      },
      "GiftCards": {
        "name": "Gift Cards",
        "summary": "Create and retrieve gift cards and manage gift cards on file.",
        "description": "\n[Square Gift Cards](https://squareup.com/gift-cards) enable sellers to boost sales and attract new customers. Customers can purchase gift cards and redeem them at any of the seller's locations. Sellers can manage gift cards and track activity.\n\nUse the Gift Cards API to create and retrieve gift cards (for example, to get the gift card balance) and manage gift cards on file by linking or unlinking gift cards with customers. After creating a gift card, use the [Gift Car[...]"
      },
      "Inventory": {
        "name": "Inventory",
        "summary": "Programmatically manages a Square seller’s inventory of catalog items.",
        "description": "\nThe Inventory API allows you to programmatically manage inventory counts and inventory changes of products or services.\n\nFor more information, see the following guides:\n - [Inventory](https://developer.squareup.com/docs/inventory-api/what-it-does)\n - [Square Webhooks Overview](https://developer.squareup.com/docs/webhooks-overview)"
      },
      "Invoices": {
        "name": "Invoices",
        "summary": "Create, configure, and publish invoices for orders that were created using the Orders API.",
        "description": "\n[Square Invoices](https://squareup.com/invoices) makes it easy for sellers to request and collect payments from their customers. Square notifies customers and processes invoice payments.\n\nUse the Invoices API to create and manage invoices for orders that were created using the Orders API. After you create the invoice and configure its delivery method, payment schedule, and other invoice settings, you can publish the invoice. Depending on the invoice settings, Square c[...]"
      },
      "Labor": {
        "name": "Labor",
        "summary": "Manage timecards and schedules for team members.",
        "description": "\nThe Labor API allows applications to manage time tracking and shift scheduling workflows.\n\n**Time tracking** - Create and manage timecards (shifts) to track work hours, breaks, and declared cash tips for payroll processing and labor cost calculations. The Labor API provides search capabilities to retrieve timecards by location, time period, status, and team member assignments. It can also be used to access job and wage information for team members, define break types,[...]"
      },
      "LocationCustomAttributes": {
        "name": "Location Custom Attributes",
        "summary": "Create and manage location-related custom attribute definitions and custom attributes.",
        "description": "\nUse the Location Custom Attributes API to create and manage custom attributes for locations. Custom attributes can be used to store properties or metadata that simplify integration, synchronization, and personalization workflows. After a custom attribute definition is created in a Square seller account, the custom attribute value can be set for locations.\n\nFor more information, see the following guides:\n - [Location Custom Attributes](https://developer.squareup.com/d[...]"
      },
      "Locations": {
        "name": "Locations",
        "summary": "Create and manage the locations of a seller's business.",
        "description": "\nMany sellers use multiple locations to track where they make sales. The Locations API allows you to\ncreate and manage data about those locations, such as their addresses, names, and business hours.\n\nFor more information, see the following guides:\n - [Locations](https://developer.squareup.com/docs/locations-api)\n - [Square Webhooks Overview](https://developer.squareup.com/docs/webhooks-overview)"
      },
      "Loyalty": {
        "name": "Loyalty",
        "summary": "Enroll buyers in a Square loyalty program, view program settings, manage and track loyalty activity, and create and manage promotions.",
        "description": "\nSellers subscribe to [Square Loyalty](https://squareup.com/software/loyalty) to offer a loyalty program that can increase repeat visits to their business by rewarding customers.\n\nUse the Loyalty API to create loyalty accounts for buyers and enable them to earn points for purchases and redeem points for reward discounts. Also use the Loyalty API to retrieve details about the loyalty program, create and manage loyalty promotions that extend the base program, and track b[...]"
      },
      "MerchantCustomAttributes": {
        "name": "Merchant Custom Attributes",
        "summary": "Create and manage merchant-related custom attribute definitions and custom attributes.",
        "description": "\nUse the Merchant Custom Attributes API to create and manage custom attributes for merchants that connect to your application. Custom attributes can be used to store properties or metadata that simplify integration, synchronization, and personalization workflows.\n\nFor more information, see the following guides:\n - [Merchant Custom Attributes](https://developer.squareup.com/docs/merchant-custom-attributes-api/overview)\n - [Square Webhooks Overview](https://developer.s[...]"
      },
      "Merchants": {
        "name": "Merchants",
        "summary": "Retrieve information about an organization that sells with Square.",
        "description": "\nThe Merchants API groups individual seller locations into larger organizations, allowing them to operate as a single entity. Each merchant represents one organization or business that sells with Square. Use this API to retrieve core information about the organization connecting to your application such as the merchant ID, language preferences, country, account status, and the name of the overall business.\n\nFor more information, see the following guide:\n - [Merchants][...]"
      },
      "MobileAuthorization": {
        "name": "Mobile Authorization",
        "summary": "Authorize Reader SDK applications to take in-person payments.",
        "description": "\n**Deprecated** - Developers should update their Reader SDK integration to use the \n[Mobile Payments SDK](https://developer.squareup.com/docs/mobile-payments-sdk), which includes its own authorization methods. \n\nThe Mobile Authorization API accepts an account credential (an OAuth token or a personal access token) and a\nlocation ID and returns an authorization code that custom mobile applications can use to initialize Square mobile\nsolutions, like Reader SDK, to acce[...]"
      },
      "OAuth": {
        "name": "OAuth",
        "summary": "Allow your application to gain programmatic access to Square seller accounts.",
        "description": "\nApplications use the OAuth API to obtain access tokens that allow them to call Square APIs on behalf of Square sellers. Applications can request scoped permissions to limit their access to only the resources they need. The OAuth flow for obtaining an OAuth access token has three stages:\n\n**Authorization** - Your application directs the seller to the Square authorization page using an authorization URL that specifies your requested permissions. The seller signs in to S[...]"
      },
      "OrderCustomAttributes": {
        "name": "Order Custom Attributes",
        "summary": "Create and manage order-related custom attribute definitions and custom attributes.",
        "description": "\nUse the Order Custom Attributes API to create and manage custom attributes for orders. Custom attributes can be used to store properties or metadata that simplify integration, synchronization, and personalization workflows. After a custom attribute definition is created in a Square seller account, the custom attribute value can be set for orders.\n\nFor more information, see the following guides:\n - [Order Custom Attributes](https://developer.squareup.com/docs/orders-c[...]"
      },
      "Orders": {
        "name": "Orders",
        "summary": "Get sales data for a Square seller, itemize payments, push orders to POS, and more.",
        "description": "\nThe Orders API is your one-stop shop for adding rich functionality to payments. You can itemize\npayments using custom line items or catalog objects, send orders to physical Point of Sale devices\nto be fulfilled, attach a customer to a payment, and more.\n\nIn addition, the Orders API lets you search through all of a seller's past sales and returns itemization\ndata, customer references, and other details from sales made using POS or online.\n\nIf you use the Square Or[...]"
      },
      "Payments": {
        "name": "Payments",
        "summary": "The Payments API lets developers take and manage payments.",
        "description": "\nApplications need the following input to take a payment:\n\n- The amount to charge.\n- The payment recipient. The payment goes to the account identified by the Authorization header in the API request.\n- The payment source. The source can be a payment token or card on file.\n\n  You can generate a payment token using the Web Payments SDK and the In-App Payments SDK. For working code examples, see [Square Connect API Examples](https://github.com/square/connect-api-exampl[...]"
      },
      "Payouts": {
        "name": "Payouts",
        "summary": "Get a list of deposits and withdrawals from a seller's bank accounts.",
        "description": "\nThe Payouts API allows you to see a complete list of payouts made to a seller's banking destination,\nwith a list of payout entries that describe the payments associated with each payout. It can be paired with the\nBank Accounts API to add detail about which bank account each payout was made to.\n\nFor more information, see the following guide:\n - [Payouts](https://developer.squareup.com/docs/payouts/overview)\n - [Square Webhooks Overview](https://developer.squareup.c[...]"
      },
      "Refunds": {
        "name": "Refunds",
        "summary": "Manage and issue refunds for payments made to Square sellers.",
        "description": "\nThe following applies to refunds:\n\n- You cannot refund more than what was originally collected.\n- The refund amount must be available in the account's Square balance. If the amount is not available, Square attempts to take money out of\n  the associated bank account. Refunds are in a state of PENDING until the funds are secured.\n- If funds cannot be secured, the refund is not completed and the buyer does not receive a credit. The refund has \n  a status of FAILED. F[...]"
      },
      "Reporting": {
        "name": "Reporting",
        "summary": "Deprecated - Use the Orders and Payments APIs instead.",
        "description": "\nPrior to 2019/08/15, the Reporting API was the way to review multi-party payments taken with the Transactions\nAPI. The Payments API now includes an \"application fee\" parameter you can use to replace this functionality."
      },
      "Sites": {
        "name": "Sites",
        "summary": "Get details about Square Online sites that belong to Square sellers.",
        "description": "\nSquare sellers use Square Online to build eCommerce websites. The Sites API lets you get basic details about Square Online sites, such as the site ID, title, and domain. You can use the Sites API with the Snippets API to manage snippets that extend Square Online features.\n\n __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/o[...]"
      },
      "Snippets": {
        "name": "Snippets",
        "summary": "Manage snippets for Square Online sites.",
        "description": "\nThe Snippets API lets you manage snippets that add custom functionality to Square Online sites. A snippet is HTML, CSS, and JavaScript that is injected into the `head` element of all pages on a site, except for checkout pages. You can use the Snippets API to create applications that help meet the many needs of Square sellers.\n\n __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Sq[...]"
      },
      "Subscriptions": {
        "name": "Subscriptions",
        "summary": "Create and manage subscriptions.",
        "description": "\nSubscriptions enable sellers to generate a reliable cash flow and recurring revenue to grow their businesses. Square offers the Subscriptions API for developers to embed subscription functionality in their applications. You first create a subscription plan using the Catalog API and then use the Subscriptions API to create and manage subscriptions. \n\nFor more information, see the following guides:\n - [Subscriptions](https://developer.squareup.com/docs/subscriptions/ov[...]"
      },
      "Team": {
        "name": "Team",
        "summary": "Manage a roster of team members and pull employee data into accounting and payroll systems.",
        "description": "\nThe Team API allows applications to manage team members and job definitions for Square sellers. \nThis includes creating and managing team member profiles, wage settings, and job data. The Team API \nsupports synchronization of team member data with accounting and payroll systems, which is useful \nfor applications that handle payroll, scheduling, and other team member-related activities. \nNote that some operations, such as setting permissions and passcodes, still need[...]"
      },
      "Terminal": {
        "name": "Terminal",
        "summary": "Requests a checkout from a paired Square Terminal.",
        "description": "\nThe Terminal API allows you to manage sending and receiving requests and responses from a paired Square Terminal. For a Terminal checkout, refund, or action, you can create a request, check its status, cancel the request, search for in-process requests, and get the results of the request after it is completed. In the current implementation, refunds are only supported for Interac debit cards in Canada.\n\nFor more information, see the following guides:\n - [Terminal](htt[...]"
      },
      "Transactions": {
        "name": "Transactions",
        "summary": "Deprecated - Use the Orders and Payments APIs instead.",
        "description": "\nPrior to 2019/08/15, the Transactions API was the way to take online payments. Going forward, the Payments API \nand Refunds API (together with the Orders API) replace the Transactions API. For information about migrating your code to the Payments API, see [Migrate from Transactions](https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api)"
      },
      "V1Webhooks": {
        "name": "V1Webhooks",
        "summary": "Deprecated - Use V2 Webhooks.",
        "description": "\nIf you are working with V1 (deprecated) webhooks, you use the Webhooks API to subscribe to events for each seller you are interested in receiving events for.\n\nIf you are working with V2 webhooks, you do not need to use this API.\nInstead, you subscribe to events using the [Developer Dashboard](/apps) or the [Webhook Subscriptions API](/reference/square/webhook-subscriptions-api).\nLearn how to subscribe to V2 webhooks using the [dashboard](/docs/webhooks/step2subscrib[...]"
      },
      "Vendors": {
        "name": "Vendors",
        "summary": "Manages a seller's suppliers.",
        "description": "The Vendors API allows applications to create, retrieve, and update vendors as suppliers to a seller.\n\nFor more information, see the following guides:\n - [Vendors](https://developer.squareup.com/docs/vendors-api/overview)\n - [Square Webhooks Overview](https://developer.squareup.com/docs/webhooks-overview)"
      },
      "WebhookSubscriptions": {
        "name": "Webhook Subscriptions",
        "summary": "Create and manage webhook subscriptions.",
        "description": "\nThe Webhook Subscriptions API allows you to create, retrieve, update, and delete webhook subscriptions. Because Webhook subscriptions are owned by the application and not any one seller, you cannot use OAuth Access Tokens with the Webhook Subscriptions API. You must use the application’s [personal access token](/docs/build-basics/access-tokens).\n\nFor more information, see the following guide the following guide:\n - [Webhook Subscriptions](https://developer.squareup.c[...]"
      }
    },
    "x-categories": {
      "Commerce": {
        "name": "Commerce",
        "summary": "Process orders, manage catalogs, track inventory, book reservations, and manage vendors. ",
        "description": "",
        "apis": [
          "#/components/x-apis/Orders",
          "#/components/x-apis/OrderCustomAttributes",
          "#/components/x-apis/Catalog",
          "#/components/x-apis/Inventory",
          "#/components/x-apis/Bookings",
          "#/components/x-apis/Booking Custom Attributes",
          "#/components/x-apis/Vendors",
          "#/components/x-apis/Sites",
          "#/components/x-apis/Snippets",
          "#/components/x-apis/Cash Drawers"
        ]
      },
      "Customers": {
        "name": "Customers",
        "summary": "Securely manage customer data and integrate engagement features to increase repeat business and attract new customers.",
        "description": "\n",
        "apis": [
          "#/components/x-apis/Customers",
          "#/components/x-apis/CustomerCustomAttributes",
          "#/components/x-apis/CustomerGroups",
          "#/components/x-apis/CustomerSegments",
          "#/components/x-apis/Loyalty",
          "#/components/x-apis/GiftCards",
          "#/components/x-apis/GiftCardActivities"
        ]
      },
      "Dev Essentials": {
        "name": "Dev Essentials",
        "summary": "Authenticate your app, provide secure delegated access to Square account data, and manage webhook subscriptions.",
        "description": "",
        "apis": [
          "#/components/x-apis/OAuth",
          "#/components/x-apis/WebhookSubscriptions",
          "#/components/x-apis/Events"
        ]
      },
      "Merchants": {
        "name": "Merchants",
        "summary": "Manage a seller's core business information used for business, and suppliers.",
        "description": "",
        "apis": [
          "#/components/x-apis/Merchants",
          "#/components/x-apis/MerchantCustomAttributes",
          "#/components/x-apis/Locations",
          "#/components/x-apis/LocationCustomAttributes"
        ]
      },
      "Payments": {
        "name": "Payments",
        "summary": "Take payments, process refunds, manage disputes, enable subscriptions, and get paid for your sales.",
        "description": "\n",
        "apis": [
          "#/components/x-apis/Payments",
          "#/components/x-apis/Refunds",
          "#/components/x-apis/Checkout",
          "#/components/x-apis/Terminal",
          "#/components/x-apis/Disputes",
          "#/components/x-apis/Invoices",
          "#/components/x-apis/Cards",
          "#/components/x-apis/Subscriptions",
          "#/components/x-apis/BankAccounts",
          "#/components/x-apis/Payouts",
          "#/components/x-apis/MobileAuthorization",
          "#/components/x-apis/Devices",
          "#/components/x-apis/ApplePay"
        ]
      },
      "Staff": {
        "name": "Staff",
        "summary": "Manage team members and jobs, track hours worked, and manage team schedules.",
        "description": "",
        "apis": [
          "#/components/x-apis/Labor",
          "#/components/x-apis/Team"
        ]
      }
    },
    "x-categories-order": [
      "Dev Essentials",
      "Payments",
      "Commerce",
      "Customers",
      "Staff",
      "Merchants"
    ],
    "x-v1-api-mappings": {
      "V1Employees": {
        "V1CreateEmployee": "Employees",
        "V1CreateEmployeeRole": "Employees",
        "V1CreateTimecard": "Labor",
        "V1DeleteTimecard": "Labor",
        "V1ListCashDrawerShifts": "CashDrawers",
        "V1ListEmployeeRoles": "Employees",
        "V1ListEmployees": "Employees",
        "V1ListTimecardEvents": "Labor",
        "V1ListTimecards": "Labor",
        "V1RetrieveCashDrawerShift": "CashDrawers",
        "V1RetrieveEmployee": "Employees",
        "V1RetrieveEmployeeRole": "Employees",
        "V1RetrieveTimecard": "Labor",
        "V1UpdateEmployee": "Employees",
        "V1UpdateEmployeeRole": "Employees",
        "V1UpdateTimecard": "Labor"
      },
      "V1Items": {
        "V1AdjustInventory": "Inventory",
        "V1ApplyFee": "Catalog",
        "V1ApplyModifierList": "Catalog",
        "V1CreateCategory": "Catalog",
        "V1CreateDiscount": "Catalog",
        "V1CreateFee": "Catalog",
        "V1CreateItem": "Catalog",
        "V1CreateModifierList": "Catalog",
        "V1CreateModifierOption": "Catalog",
        "V1CreatePage": "Catalog",
        "V1CreateVariation": "Catalog",
        "V1DeleteCategory": "Catalog",
        "V1DeleteDiscount": "Catalog",
        "V1DeleteFee": "Catalog",
        "V1DeleteItem": "Catalog",
        "V1DeleteModifierList": "Catalog",
        "V1DeleteModifierOption": "Catalog",
        "V1DeletePage": "Catalog",
        "V1DeletePageCell": "Catalog",
        "V1DeleteVariation": "Catalog",
        "V1ListCategories": "Catalog",
        "V1ListDiscounts": "Catalog",
        "V1ListFees": "Catalog",
        "V1ListInventory": "Inventory",
        "V1ListItems": "Catalog",
        "V1ListModifierLists": "Catalog",
        "V1ListPages": "Catalog",
        "V1RemoveFee": "Catalog",
        "V1RemoveModifierList": "Catalog",
        "V1RetrieveItem": "Catalog",
        "V1RetrieveModifierList": "Catalog",
        "V1UpdateCategory": "Catalog",
        "V1UpdateDiscount": "Catalog",
        "V1UpdateFee": "Catalog",
        "V1UpdateItem": "Catalog",
        "V1UpdateModifierList": "Catalog",
        "V1UpdateModifierOption": "Catalog",
        "V1UpdatePage": "Catalog",
        "V1UpdatePageCell": "Catalog",
        "V1UpdateVariation": "Catalog",
        "V1UploadItemImage": "Catalog"
      },
      "V1Locations": {
        "V1ListLocations": "Locations",
        "V1RetrieveBusiness": "Merchants"
      },
      "V1Transactions": {
        "V1CreateRefund": "Refunds",
        "V1ListBankAccounts": "BankAccounts",
        "V1ListPayments": "Payments",
        "V1ListRefunds": "Refunds",
        "V1ListSettlements": "Payouts",
        "V1RetrieveBankAccount": "BankAccounts",
        "V1RetrievePayment": "Payments",
        "V1RetrieveSettlement": "Payouts"
      },
      "V1Webhooks": {
        "V1ListWebhooks": "V1Webhooks",
        "V1UpdateWebhooks": "V1Webhooks"
      }
    }
  },
  "paths": {
    "/mobile/authorization-code": {
      "post": {
        "tags": [
          "MobileAuthorization"
        ],
        "summary": "CreateMobileAuthorizationCode",
        "operationId": "CreateMobileAuthorizationCode",
        "description": "__Note:__ This endpoint is used by the deprecated Reader SDK. \nDevelopers should update their integration to use the [Mobile Payments SDK](https://developer.squareup.com/docs/mobile-payments-sdk), which includes its own authorization methods. \n\nGenerates code to authorize a mobile application to connect to a Square card reader.\n\nAuthorization codes are one-time-use codes and expire 60 minutes after being issued.\n\nThe `Authorization` header you provide to this endpo[...]",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {},
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE_IN_PERSON"
            ]
          }
        ]
      }
    },
    "/oauth2/revoke": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "RevokeToken",
        "operationId": "RevokeToken",
        "description": "Revokes an access token generated with the OAuth flow.\n\nIf an account has more than one OAuth access token for your application, this\nendpoint revokes all of them, regardless of which token you specify. \n\n__Important:__ The `Authorization` header for this endpoint must have the\nfollowing format:\n\n```\nAuthorization: Client APPLICATION_SECRET\n```\n\nReplace `APPLICATION_SECRET` with the application secret on the **OAuth**\npage for your application in the Develope[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": null
          }
        ]
      }
    },
    "/oauth2/token": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "ObtainToken",
        "operationId": "ObtainToken",
        "description": "Returns an OAuth access token and refresh token using the `authorization_code`\nor `refresh_token` grant type.\n\nWhen `grant_type` is `authorization_code`:\n- With the [code flow](https://developer.squareup.com/docs/oauth-api/overview#code-flow),\nprovide `code`, `client_id`, and `client_secret`.\n- With the [PKCE flow](https://developer.squareup.com/docs/oauth-api/overview#pkce-flow),\nprovide `code`, `client_id`, and `code_verifier`. \n\nWhen `grant_type` is `refresh_t[...]",
        "x-release-status": "PUBLIC",
        "security": []
      }
    },
    "/oauth2/token/status": {
      "post": {
        "tags": [
          "OAuth"
        ],
        "summary": "RetrieveTokenStatus",
        "operationId": "RetrieveTokenStatus",
        "description": "Returns information about an [OAuth access token](https://developer.squareup.com/docs/build-basics/access-tokens#get-an-oauth-access-token) or an application’s [personal access token](https://developer.squareup.com/docs/build-basics/access-tokens#get-a-personal-access-token).\n\nAdd the access token to the Authorization header of the request.\n\n__Important:__ The `Authorization` header you provide to this endpoint must have the following format:\n\n```\nAuthorization: Be[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v1/{location_id}/orders": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1ListOrders",
        "operationId": "V1ListOrders",
        "description": "Provides summary information for a merchant's online store orders.",
        "x-release-status": "DEPRECATED",
        "x-visibility": "SDK_ONLY",
        "deprecated": true,
        "x-deprecation": {},
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      }
    },
    "/v1/{location_id}/orders/{order_id}": {
      "get": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1RetrieveOrder",
        "operationId": "V1RetrieveOrder",
        "description": "Provides comprehensive information for a single online store order, including the order's history.",
        "x-release-status": "DEPRECATED",
        "x-visibility": "SDK_ONLY",
        "deprecated": true,
        "x-deprecation": {},
        "security": [
          {
            "oauth2": [
              "ORDERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "V1Transactions"
        ],
        "summary": "V1UpdateOrder",
        "operationId": "V1UpdateOrder",
        "description": "Updates the details of an online store order. Every update you perform on an order corresponds to one of three actions:",
        "x-release-status": "DEPRECATED",
        "x-visibility": "SDK_ONLY",
        "deprecated": true,
        "x-deprecation": {},
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/apple-pay/domains": {
      "post": {
        "tags": [
          "ApplePay"
        ],
        "summary": "RegisterDomain",
        "operationId": "RegisterDomain",
        "description": "Activates a domain for use with Apple Pay on the Web and Square. A validation\nis performed on this domain by Apple to ensure that it is properly set up as\nan Apple Pay enabled domain.\n\nThis endpoint provides an easy way for platform developers to bulk activate\nApple Pay on the Web with Square for merchants using their platform.\n\nNote: You will need to host a valid domain verification file on your domain to support Apple Pay.  The\ncurrent version of this file is al[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/bank-accounts": {
      "get": {
        "tags": [
          "BankAccounts"
        ],
        "summary": "ListBankAccounts",
        "operationId": "ListBankAccounts",
        "description": "Returns a list of [BankAccount](entity:BankAccount) objects linked to a Square account.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bank-accounts/by-v1-id/{v1_bank_account_id}": {
      "get": {
        "tags": [
          "BankAccounts"
        ],
        "summary": "GetBankAccountByV1Id",
        "operationId": "GetBankAccountByV1Id",
        "description": "Returns details of a [BankAccount](entity:BankAccount) identified by V1 bank account ID.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bank-accounts/{bank_account_id}": {
      "get": {
        "tags": [
          "BankAccounts"
        ],
        "summary": "GetBankAccount",
        "operationId": "GetBankAccount",
        "description": "Returns details of a [BankAccount](entity:BankAccount)\nlinked to a Square account.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "BANK_ACCOUNTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "ListBookings",
        "operationId": "ListBookings",
        "description": "Retrieve a collection of bookings.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Bookings"
        ],
        "summary": "CreateBooking",
        "operationId": "CreateBooking",
        "description": "Creates a booking.\n\nThe required input must include the following:\n- `Booking.location_id`\n- `Booking.start_at`\n- `Booking.AppointmentSegment.team_member_id`\n- `Booking.AppointmentSegment.service_variation_id`\n- `Booking.AppointmentSegment.service_variation_version`\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/availability/search": {
      "post": {
        "tags": [
          "Bookings"
        ],
        "summary": "SearchAvailability",
        "operationId": "SearchAvailability",
        "description": "Searches for availabilities for booking.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/bulk-retrieve": {
      "post": {
        "tags": [
          "Bookings"
        ],
        "summary": "BulkRetrieveBookings",
        "operationId": "BulkRetrieveBookings",
        "description": "Bulk-Retrieves a list of bookings by booking IDs.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/business-booking-profile": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "RetrieveBusinessBookingProfile",
        "operationId": "RetrieveBusinessBookingProfile",
        "description": "Retrieves a seller's booking profile.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/custom-attribute-definitions": {
      "get": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "ListBookingCustomAttributeDefinitions",
        "operationId": "ListBookingCustomAttributeDefinitions",
        "description": "Get all bookings custom attribute definitions.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "CreateBookingCustomAttributeDefinition",
        "operationId": "CreateBookingCustomAttributeDefinition",
        "description": "Creates a bookings custom attribute definition.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "DeleteBookingCustomAttributeDefinition",
        "operationId": "DeleteBookingCustomAttributeDefinition",
        "description": "Deletes a bookings custom attribute definition.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "RetrieveBookingCustomAttributeDefinition",
        "operationId": "RetrieveBookingCustomAttributeDefinition",
        "description": "Retrieves a bookings custom attribute definition.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "UpdateBookingCustomAttributeDefinition",
        "operationId": "UpdateBookingCustomAttributeDefinition",
        "description": "Updates a bookings custom attribute definition.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/custom-attributes/bulk-delete": {
      "post": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "BulkDeleteBookingCustomAttributes",
        "operationId": "BulkDeleteBookingCustomAttributes",
        "description": "Bulk deletes bookings custom attributes.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "BulkUpsertBookingCustomAttributes",
        "operationId": "BulkUpsertBookingCustomAttributes",
        "description": "Bulk upserts bookings custom attributes.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/location-booking-profiles": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "ListLocationBookingProfiles",
        "operationId": "ListLocationBookingProfiles",
        "description": "Lists location booking profiles of a seller.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/location-booking-profiles/{location_id}": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "RetrieveLocationBookingProfile",
        "operationId": "RetrieveLocationBookingProfile",
        "description": "Retrieves a seller's location booking profile.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/team-member-booking-profiles": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "ListTeamMemberBookingProfiles",
        "operationId": "ListTeamMemberBookingProfiles",
        "description": "Lists booking profiles for team members.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/team-member-booking-profiles/bulk-retrieve": {
      "post": {
        "tags": [
          "Bookings"
        ],
        "summary": "BulkRetrieveTeamMemberBookingProfiles",
        "operationId": "BulkRetrieveTeamMemberBookingProfiles",
        "description": "Retrieves one or more team members' booking profiles.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/team-member-booking-profiles/{team_member_id}": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "RetrieveTeamMemberBookingProfile",
        "operationId": "RetrieveTeamMemberBookingProfile",
        "description": "Retrieves a team member's booking profile.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_BUSINESS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/{booking_id}": {
      "get": {
        "tags": [
          "Bookings"
        ],
        "summary": "RetrieveBooking",
        "operationId": "RetrieveBooking",
        "description": "Retrieves a booking.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Bookings"
        ],
        "summary": "UpdateBooking",
        "operationId": "UpdateBooking",
        "description": "Updates a booking.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/{booking_id}/cancel": {
      "post": {
        "tags": [
          "Bookings"
        ],
        "summary": "CancelBooking",
        "operationId": "CancelBooking",
        "description": "Cancels an existing booking.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/bookings/{booking_id}/custom-attributes": {
      "get": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "ListBookingCustomAttributes",
        "operationId": "ListBookingCustomAttributes",
        "description": "Lists a booking's custom attributes.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/bookings/{booking_id}/custom-attributes/{key}": {
      "delete": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "DeleteBookingCustomAttribute",
        "operationId": "DeleteBookingCustomAttribute",
        "description": "Deletes a bookings custom attribute.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "RetrieveBookingCustomAttribute",
        "operationId": "RetrieveBookingCustomAttribute",
        "description": "Retrieves a bookings custom attribute.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_READ` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_READ` and `APPOINTMENTS_READ` for the OAuth scope.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "BookingCustomAttributes"
        ],
        "summary": "UpsertBookingCustomAttribute",
        "operationId": "UpsertBookingCustomAttribute",
        "description": "Upserts a bookings custom attribute.\n\nTo call this endpoint with buyer-level permissions, set `APPOINTMENTS_WRITE` for the OAuth scope.\nTo call this endpoint with seller-level permissions, set `APPOINTMENTS_ALL_WRITE` and `APPOINTMENTS_WRITE` for the OAuth scope.\n\nFor calls to this endpoint with seller-level permissions to succeed, the seller must have subscribed to *Appointments Plus*\nor *Appointments Premium*.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "APPOINTMENTS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/cards": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "ListCards",
        "operationId": "ListCards",
        "description": "Retrieves a list of cards owned by the account making the request.\nA max of 25 cards will be returned.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": []
          }
        ]
      },
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "CreateCard",
        "operationId": "CreateCard",
        "description": "Adds a card on file to an existing merchant.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": []
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "CARD_DECLINED_VERIFICATION_REQUIRED"
          },
          {
            "error-code": "CARD_PROCESSING_NOT_ENABLED"
          },
          {
            "error-code": "CUSTOMER_NOT_FOUND"
          },
          {
            "error-code": "SOURCE_EXPIRED"
          },
          {
            "error-code": "SOURCE_USED"
          },
          {
            "error-code": "INVALID_CARD_DATA"
          }
        ]
      }
    },
    "/v2/cards/{card_id}": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "RetrieveCard",
        "operationId": "RetrieveCard",
        "description": "Retrieves details for a specific Card.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": []
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "NOT_FOUND"
          }
        ]
      }
    },
    "/v2/cards/{card_id}/disable": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "DisableCard",
        "operationId": "DisableCard",
        "description": "Disables the card, preventing any further updates or charges.\nDisabling an already disabled card is allowed but has no effect.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": []
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "NOT_FOUND"
          }
        ]
      }
    },
    "/v2/cash-drawers/shifts": {
      "get": {
        "tags": [
          "CashDrawers"
        ],
        "summary": "ListCashDrawerShifts",
        "operationId": "ListCashDrawerShifts",
        "description": "Provides the details for all of the cash drawer shifts for a location\nin a date range.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CASH_DRAWER_READ"
            ]
          }
        ]
      }
    },
    "/v2/cash-drawers/shifts/{shift_id}": {
      "get": {
        "tags": [
          "CashDrawers"
        ],
        "summary": "RetrieveCashDrawerShift",
        "operationId": "RetrieveCashDrawerShift",
        "description": "Provides the summary details for a single cash drawer shift. See\n[ListCashDrawerShiftEvents](api-endpoint:CashDrawers-ListCashDrawerShiftEvents) for a list of cash drawer shift events.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CASH_DRAWER_READ"
            ]
          }
        ]
      }
    },
    "/v2/cash-drawers/shifts/{shift_id}/events": {
      "get": {
        "tags": [
          "CashDrawers"
        ],
        "summary": "ListCashDrawerShiftEvents",
        "operationId": "ListCashDrawerShiftEvents",
        "description": "Provides a paginated list of events for a single cash drawer shift.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CASH_DRAWER_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/batch-delete": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchDeleteCatalogObjects",
        "operationId": "BatchDeleteCatalogObjects",
        "description": "Deletes a set of [CatalogItem](entity:CatalogItem)s based on the\nprovided list of target IDs and returns a set of successfully deleted IDs in\nthe response. Deletion is a cascading event such that all children of the\ntargeted object are also deleted. For example, deleting a CatalogItem will\nalso delete all of its [CatalogItemVariation](entity:CatalogItemVariation)\nchildren.\n\n`BatchDeleteCatalogObjects` succeeds even if only a portion of the targeted\nIDs can be dele[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/batch-retrieve": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchRetrieveCatalogObjects",
        "operationId": "BatchRetrieveCatalogObjects",
        "description": "Returns a set of objects based on the provided ID.\nEach [CatalogItem](entity:CatalogItem) returned in the set includes all of its\nchild information including: all of its\n[CatalogItemVariation](entity:CatalogItemVariation) objects, references to\nits [CatalogModifierList](entity:CatalogModifierList) objects, and the ids of\nany [CatalogTax](entity:CatalogTax) objects that apply to it.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/batch-upsert": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "BatchUpsertCatalogObjects",
        "operationId": "BatchUpsertCatalogObjects",
        "description": "Creates or updates up to 10,000 target objects based on the provided\nlist of objects. The target objects are grouped into batches and each batch is\ninserted/updated in an all-or-nothing manner. If an object within a batch is\nmalformed in some way, or violates a database constraint, the entire batch\ncontaining that item will be disregarded. However, other batches in the same\nrequest may still succeed. Each batch may contain up to 1,000 objects, and\nbatches will be pr[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "GENERIC_DECLINE"
          }
        ]
      }
    },
    "/v2/catalog/images": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "CreateCatalogImage",
        "operationId": "CreateCatalogImage",
        "description": "Uploads an image file to be represented by a [CatalogImage](entity:CatalogImage) object that can be linked to an existing\n[CatalogObject](entity:CatalogObject) instance. The resulting `CatalogImage` is unattached to any `CatalogObject` if the `object_id`\nis not specified.\n\nThis `CreateCatalogImage` endpoint accepts HTTP multipart/form-data requests with a JSON part and an image file part in\nJPEG, PJPEG, PNG, or GIF format. The maximum file size is 15MB.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "GENERIC_DECLINE"
          }
        ]
      }
    },
    "/v2/catalog/images/{image_id}": {
      "put": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpdateCatalogImage",
        "operationId": "UpdateCatalogImage",
        "description": "Uploads a new image file to replace the existing one in the specified [CatalogImage](entity:CatalogImage) object.\n\nThis `UpdateCatalogImage` endpoint accepts HTTP multipart/form-data requests with a JSON part and an image file part in\nJPEG, PJPEG, PNG, or GIF format. The maximum file size is 15MB.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/info": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "CatalogInfo",
        "operationId": "CatalogInfo",
        "description": "Retrieves information about the Square Catalog API, such as batch size\nlimits that can be used by the `BatchUpsertCatalogObjects` endpoint.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/list": {
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "ListCatalog",
        "operationId": "ListCatalog",
        "description": "Returns a list of all [CatalogObject](entity:CatalogObject)s of the specified types in the catalog.\n\nThe `types` parameter is specified as a comma-separated list of the [CatalogObjectType](entity:CatalogObjectType) values,\nfor example, \"`ITEM`, `ITEM_VARIATION`, `MODIFIER`, `MODIFIER_LIST`, `CATEGORY`, `DISCOUNT`, `TAX`, `IMAGE`\".\n\n__Important:__ ListCatalog does not return deleted catalog items. To retrieve\ndeleted catalog items, use [SearchCatalogObjects](api-en[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/object": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpsertCatalogObject",
        "operationId": "UpsertCatalogObject",
        "description": "Creates a new or updates the specified [CatalogObject](entity:CatalogObject).\n\nTo ensure consistency, only one update request is processed at a time per seller account.\nWhile one (batch or non-batch) update request is being processed, other (batched and non-batched)\nupdate requests are rejected with the `429` error code.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "GENERIC_DECLINE"
          },
          {
            "error-code": "INVALID_LOCATION"
          }
        ]
      }
    },
    "/v2/catalog/object/{object_id}": {
      "delete": {
        "tags": [
          "Catalog"
        ],
        "summary": "DeleteCatalogObject",
        "operationId": "DeleteCatalogObject",
        "description": "Deletes a single [CatalogObject](entity:CatalogObject) based on the\nprovided ID and returns the set of successfully deleted IDs in the response.\nDeletion is a cascading event such that all children of the targeted object\nare also deleted. For example, deleting a [CatalogItem](entity:CatalogItem)\nwill also delete all of its\n[CatalogItemVariation](entity:CatalogItemVariation) children.\n\nTo ensure consistency, only one delete request is processed at a time per seller [...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Catalog"
        ],
        "summary": "RetrieveCatalogObject",
        "operationId": "RetrieveCatalogObject",
        "description": "Returns a single [CatalogItem](entity:CatalogItem) as a\n[CatalogObject](entity:CatalogObject) based on the provided ID. The returned\nobject includes all of the relevant [CatalogItem](entity:CatalogItem)\ninformation including: [CatalogItemVariation](entity:CatalogItemVariation)\nchildren, references to its\n[CatalogModifierList](entity:CatalogModifierList) objects, and the ids of\nany [CatalogTax](entity:CatalogTax) objects that apply to it.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/search": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "SearchCatalogObjects",
        "operationId": "SearchCatalogObjects",
        "description": "Searches for [CatalogObject](entity:CatalogObject) of any type by matching supported search attribute values,\nexcluding custom attribute values on items or item variations, against one or more of the specified query filters.\n\nThis (`SearchCatalogObjects`) endpoint differs from the [SearchCatalogItems](api-endpoint:Catalog-SearchCatalogItems)\nendpoint in the following aspects:\n\n- `SearchCatalogItems` can only search for items or item variations, whereas `SearchCatalo[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/search-catalog-items": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "SearchCatalogItems",
        "operationId": "SearchCatalogItems",
        "description": "Searches for catalog items or item variations by matching supported search attribute values, including\ncustom attribute values, against one or more of the specified query filters.\n\nThis (`SearchCatalogItems`) endpoint differs from the [SearchCatalogObjects](api-endpoint:Catalog-SearchCatalogObjects)\nendpoint in the following aspects:\n\n- `SearchCatalogItems` can only search for items or item variations, whereas `SearchCatalogObjects` can search for any type of catalo[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_READ"
            ]
          }
        ]
      }
    },
    "/v2/catalog/update-item-modifier-lists": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpdateItemModifierLists",
        "operationId": "UpdateItemModifierLists",
        "description": "Updates the [CatalogModifierList](entity:CatalogModifierList) objects\nthat apply to the targeted [CatalogItem](entity:CatalogItem) without having\nto perform an upsert on the entire item.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/catalog/update-item-taxes": {
      "post": {
        "tags": [
          "Catalog"
        ],
        "summary": "UpdateItemTaxes",
        "operationId": "UpdateItemTaxes",
        "description": "Updates the [CatalogTax](entity:CatalogTax) objects that apply to the\ntargeted [CatalogItem](entity:CatalogItem) without having to perform an\nupsert on the entire item.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ITEMS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers": {
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "ListCustomers",
        "operationId": "ListCustomers",
        "description": "Lists customer profiles associated with a Square account.\n\nUnder normal operating conditions, newly created or updated customer profiles become available\nfor the listing operation in well under 30 seconds. Occasionally, propagation of the new or updated\nprofiles can take closer to one minute or longer, especially during network incidents and outages.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "CreateCustomer",
        "operationId": "CreateCustomer",
        "description": "Creates a new customer for a business.\n\nYou must provide at least one of the following values in your request to this\nendpoint:\n\n- `given_name`\n- `family_name`\n- `company_name`\n- `email_address`\n- `phone_number`",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "INVALID_EMAIL_ADDRESS"
          },
          {
            "error-code": "INVALID_PHONE_NUMBER"
          },
          {
            "error-code": "INVALID_TIME"
          },
          {
            "error-code": "VALUE_TOO_LONG"
          }
        ]
      }
    },
    "/v2/customers/bulk-create": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "BulkCreateCustomers",
        "operationId": "BulkCreateCustomers",
        "description": "Creates multiple [customer profiles](entity:Customer) for a business.\n\nThis endpoint takes a map of individual create requests and returns a map of responses.\n\nYou must provide at least one of the following values in each create request:\n\n- `given_name`\n- `family_name`\n- `company_name`\n- `email_address`\n- `phone_number`",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/bulk-delete": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "BulkDeleteCustomers",
        "operationId": "BulkDeleteCustomers",
        "description": "Deletes multiple customer profiles.\n\nThe endpoint takes a list of customer IDs and returns a map of responses.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/bulk-retrieve": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "BulkRetrieveCustomers",
        "operationId": "BulkRetrieveCustomers",
        "description": "Retrieves multiple customer profiles.\n\nThis endpoint takes a list of customer IDs and returns a map of responses.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/bulk-update": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "BulkUpdateCustomers",
        "operationId": "BulkUpdateCustomers",
        "description": "Updates multiple customer profiles.\n\nThis endpoint takes a map of individual update requests and returns a map of responses.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/custom-attribute-definitions": {
      "get": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "ListCustomerCustomAttributeDefinitions",
        "operationId": "ListCustomerCustomAttributeDefinitions",
        "description": "Lists the customer-related [custom attribute definitions](entity:CustomAttributeDefinition) that belong to a Square seller account.\n\nWhen all response pages are retrieved, the results include all custom attribute definitions\nthat are visible to the requesting application, including those that are created by other\napplications and set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that\nseller-defined custom attributes (also known as custom fields) a[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "CreateCustomerCustomAttributeDefinition",
        "operationId": "CreateCustomerCustomAttributeDefinition",
        "description": "Creates a customer-related [custom attribute definition](entity:CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to define a custom attribute that can be associated with customer profiles.\n\nA custom attribute definition specifies the `key`, `visibility`, `schema`, and other properties\nfor a custom attribute. After the definition is created, you can call\n[UpsertCustomerCustomAttribute](api-endpoint:CustomerCustomAttributes-UpsertCustomerCustom[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "DeleteCustomerCustomAttributeDefinition",
        "operationId": "DeleteCustomerCustomAttributeDefinition",
        "description": "Deletes a customer-related [custom attribute definition](entity:CustomAttributeDefinition) from a Square seller account.\n\nDeleting a custom attribute definition also deletes the corresponding custom attribute from\nall customer profiles in the seller's Customer Directory.\n\nOnly the definition owner can delete a custom attribute definition.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "RetrieveCustomerCustomAttributeDefinition",
        "operationId": "RetrieveCustomerCustomAttributeDefinition",
        "description": "Retrieves a customer-related [custom attribute definition](entity:CustomAttributeDefinition) from a Square seller account.\n\nTo retrieve a custom attribute definition created by another application, the `visibility`\nsetting must be `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\n(also known as custom fields) are always set to `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "UpdateCustomerCustomAttributeDefinition",
        "operationId": "UpdateCustomerCustomAttributeDefinition",
        "description": "Updates a customer-related [custom attribute definition](entity:CustomAttributeDefinition) for a Square seller account.\n\nUse this endpoint to update the following fields: `name`, `description`, `visibility`, or the\n`schema` for a `Selection` data type.\n\nOnly the definition owner can update a custom attribute definition. Note that sellers can view\nall custom attributes in exported customer data, including those set to `VISIBILITY_HIDDEN`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "BulkUpsertCustomerCustomAttributes",
        "operationId": "BulkUpsertCustomerCustomAttributes",
        "description": "Creates or updates [custom attributes](entity:CustomAttribute) for customer profiles as a bulk operation.\n\nUse this endpoint to set the value of one or more custom attributes for one or more customer profiles.\nA custom attribute is based on a custom attribute definition in a Square seller account, which is\ncreated using the [CreateCustomerCustomAttributeDefinition](api-endpoint:CustomerCustomAttributes-CreateCustomerCustomAttributeDefinition) endpoint.\n\nThis `BulkUp[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/groups": {
      "get": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "ListCustomerGroups",
        "operationId": "ListCustomerGroups",
        "description": "Retrieves the list of customer groups of a business.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "CreateCustomerGroup",
        "operationId": "CreateCustomerGroup",
        "description": "Creates a new customer group for a business.\n\nThe request must include the `name` value of the group.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/groups/{group_id}": {
      "delete": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "DeleteCustomerGroup",
        "operationId": "DeleteCustomerGroup",
        "description": "Deletes a customer group as identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "RetrieveCustomerGroup",
        "operationId": "RetrieveCustomerGroup",
        "description": "Retrieves a specific customer group as identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "CustomerGroups"
        ],
        "summary": "UpdateCustomerGroup",
        "operationId": "UpdateCustomerGroup",
        "description": "Updates a customer group as identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/search": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "SearchCustomers",
        "operationId": "SearchCustomers",
        "description": "Searches the customer profiles associated with a Square account using one or more supported query filters.\n\nCalling `SearchCustomers` without any explicit query filter returns all\ncustomer profiles ordered alphabetically based on `given_name` and\n`family_name`.\n\nUnder normal operating conditions, newly created or updated customer profiles become available\nfor the search operation in well under 30 seconds. Occasionally, propagation of the new or updated\nprofiles ca[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/segments": {
      "get": {
        "tags": [
          "CustomerSegments"
        ],
        "summary": "ListCustomerSegments",
        "operationId": "ListCustomerSegments",
        "description": "Retrieves the list of customer segments of a business.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/segments/{segment_id}": {
      "get": {
        "tags": [
          "CustomerSegments"
        ],
        "summary": "RetrieveCustomerSegment",
        "operationId": "RetrieveCustomerSegment",
        "description": "Retrieves a specific customer segment as identified by the `segment_id` value.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "DeleteCustomer",
        "operationId": "DeleteCustomer",
        "description": "Deletes a customer profile from a business.\n\nTo delete a customer profile that was created by merging existing profiles, you must use the ID of the newly created profile.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Customers"
        ],
        "summary": "RetrieveCustomer",
        "operationId": "RetrieveCustomer",
        "description": "Returns details for a single customer.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customers"
        ],
        "summary": "UpdateCustomer",
        "operationId": "UpdateCustomer",
        "description": "Updates a customer profile. This endpoint supports sparse updates, so only new or changed fields are required in the request.\nTo add or update a field, specify the new value. To remove a field, specify `null`.\n\nTo update a customer profile that was created by merging existing profiles, you must use the ID of the newly created profile.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "INVALID_EMAIL_ADDRESS"
          },
          {
            "error-code": "INVALID_PHONE_NUMBER"
          },
          {
            "error-code": "INVALID_TIME"
          },
          {
            "error-code": "VALUE_TOO_LONG"
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/cards": {
      "post": {
        "tags": [
          "Customers"
        ],
        "summary": "CreateCustomerCard",
        "operationId": "CreateCustomerCard",
        "description": "Adds a card on file to an existing customer.\n\nAs with charges, calls to `CreateCustomerCard` are idempotent. Multiple\ncalls with the same card nonce return the same card record that was created\nwith the provided nonce during the _first_ call.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-06-16",
          "replacedBy": "CreateCard",
          "guideUrl": "https://developer.squareup.com/docs/customers-api/what-it-does#deprecated-createcustomercard-endpoint"
        },
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "CARD_EXPIRED"
          },
          {
            "error-code": "CARD_PROCESSING_NOT_ENABLED"
          },
          {
            "error-code": "CARD_TOKEN_EXPIRED"
          },
          {
            "error-code": "CARD_TOKEN_USED"
          },
          {
            "error-code": "INVALID_CARD"
          },
          {
            "error-code": "INVALID_CARD_DATA"
          },
          {
            "error-code": "INVALID_EXPIRATION"
          },
          {
            "error-code": "UNSUPPORTED_ENTRY_METHOD"
          },
          {
            "error-code": "VERIFY_AVS_FAILURE"
          },
          {
            "error-code": "VERIFY_CVV_FAILURE"
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/cards/{card_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "DeleteCustomerCard",
        "operationId": "DeleteCustomerCard",
        "description": "Removes a card on file from a customer.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-06-16",
          "replacedBy": "DisableCard",
          "guideUrl": "https://developer.squareup.com/docs/customers-api/what-it-does#deprecated-deletecustomercard-endpoint"
        },
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/custom-attributes": {
      "get": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "ListCustomerCustomAttributes",
        "operationId": "ListCustomerCustomAttributes",
        "description": "Lists the [custom attributes](entity:CustomAttribute) associated with a customer profile.\n\nYou can use the `with_definitions` query parameter to also retrieve custom attribute definitions\nin the same call.\n\nWhen all response pages are retrieved, the results include all custom attributes that are\nvisible to the requesting application, including those that are owned by other applications\nand set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/custom-attributes/{key}": {
      "delete": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "DeleteCustomerCustomAttribute",
        "operationId": "DeleteCustomerCustomAttribute",
        "description": "Deletes a [custom attribute](entity:CustomAttribute) associated with a customer profile.\n\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\n(also known as custom fields) are always set to `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "RetrieveCustomerCustomAttribute",
        "operationId": "RetrieveCustomerCustomAttribute",
        "description": "Retrieves a [custom attribute](entity:CustomAttribute) associated with a customer profile.\n\nYou can use the `with_definition` query parameter to also retrieve the custom attribute definition\nin the same call.\n\nTo retrieve a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`. Note that seller-defined custom attributes\n(also known as custom fields) are always set to `VISIBILITY_READ[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "CustomerCustomAttributes"
        ],
        "summary": "UpsertCustomerCustomAttribute",
        "operationId": "UpsertCustomerCustomAttribute",
        "description": "Creates or updates a [custom attribute](entity:CustomAttribute) for a customer profile.\n\nUse this endpoint to set the value of a custom attribute for a specified customer profile.\nA custom attribute is based on a custom attribute definition in a Square seller account, which\nis created using the [CreateCustomerCustomAttributeDefinition](api-endpoint:CustomerCustomAttributes-CreateCustomerCustomAttributeDefinition) endpoint.\n\nTo create or update a custom attribute own[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/customers/{customer_id}/groups/{group_id}": {
      "delete": {
        "tags": [
          "Customers"
        ],
        "summary": "RemoveGroupFromCustomer",
        "operationId": "RemoveGroupFromCustomer",
        "description": "Removes a group membership from a customer.\n\nThe customer is identified by the `customer_id` value\nand the customer group is identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Customers"
        ],
        "summary": "AddGroupToCustomer",
        "operationId": "AddGroupToCustomer",
        "description": "Adds a group membership to a customer.\n\nThe customer is identified by the `customer_id` value\nand the customer group is identified by the `group_id` value.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "CUSTOMERS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/devices": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "ListDevices",
        "operationId": "ListDevices",
        "description": "List devices associated with the merchant. Currently, only Terminal API\ndevices are supported.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "DEVICES_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          }
        ]
      }
    },
    "/v2/devices/codes": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "ListDeviceCodes",
        "operationId": "ListDeviceCodes",
        "description": "Lists all DeviceCodes associated with the merchant.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DEVICE_CREDENTIAL_MANAGEMENT"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "INVALID_CURSOR"
          },
          {
            "error-code": "BAD_REQUEST"
          }
        ]
      },
      "post": {
        "tags": [
          "Devices"
        ],
        "summary": "CreateDeviceCode",
        "operationId": "CreateDeviceCode",
        "description": "Creates a DeviceCode that can be used to login to a Square Terminal device to enter the connected\nterminal mode.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DEVICE_CREDENTIAL_MANAGEMENT"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "IDEMPOTENCY_KEY_REUSED"
          },
          {
            "error-code": "INVALID_VALUE"
          },
          {
            "error-code": "UNAUTHORIZED"
          }
        ]
      }
    },
    "/v2/devices/codes/{id}": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "GetDeviceCode",
        "operationId": "GetDeviceCode",
        "description": "Retrieves DeviceCode with the associated ID.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DEVICE_CREDENTIAL_MANAGEMENT"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "NOT_FOUND"
          },
          {
            "error-code": "UNAUTHORIZED"
          }
        ]
      }
    },
    "/v2/devices/{device_id}": {
      "get": {
        "tags": [
          "Devices"
        ],
        "summary": "GetDevice",
        "operationId": "GetDevice",
        "description": "Retrieves Device with the associated `device_id`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "DEVICES_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "NOT_FOUND"
          }
        ]
      }
    },
    "/v2/disputes": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "ListDisputes",
        "operationId": "ListDisputes",
        "description": "Returns a list of disputes associated with a particular account.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_READ"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "RetrieveDispute",
        "operationId": "RetrieveDispute",
        "description": "Returns details about a specific dispute.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_READ"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/accept": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "AcceptDispute",
        "operationId": "AcceptDispute",
        "description": "Accepts the loss on a dispute. Square returns the disputed amount to the cardholder and\nupdates the dispute state to ACCEPTED.\n\nSquare debits the disputed amount from the seller’s Square account. If the Square account\ndoes not have sufficient funds, Square debits the associated bank account.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/evidence": {
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "ListDisputeEvidence",
        "operationId": "ListDisputeEvidence",
        "description": "Returns a list of evidence associated with a dispute.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_READ"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/evidence-files": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "CreateDisputeEvidenceFile",
        "operationId": "CreateDisputeEvidenceFile",
        "description": "Uploads a file to use as evidence in a dispute challenge. The endpoint accepts HTTP\nmultipart/form-data file uploads in HEIC, HEIF, JPEG, PDF, PNG, and TIFF formats.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/evidence-text": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "CreateDisputeEvidenceText",
        "operationId": "CreateDisputeEvidenceText",
        "description": "Uploads text to use as evidence for a dispute challenge.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/evidence/{evidence_id}": {
      "delete": {
        "tags": [
          "Disputes"
        ],
        "summary": "DeleteDisputeEvidence",
        "operationId": "DeleteDisputeEvidence",
        "description": "Removes specified evidence from a dispute.\nSquare does not send the bank any evidence that is removed.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Disputes"
        ],
        "summary": "RetrieveDisputeEvidence",
        "operationId": "RetrieveDisputeEvidence",
        "description": "Returns the metadata for the evidence specified in the request URL path.\n\nYou must maintain a copy of any evidence uploaded if you want to reference it later. Evidence cannot be downloaded after you upload it.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_READ"
            ]
          }
        ]
      }
    },
    "/v2/disputes/{dispute_id}/submit-evidence": {
      "post": {
        "tags": [
          "Disputes"
        ],
        "summary": "SubmitEvidence",
        "operationId": "SubmitEvidence",
        "description": "Submits evidence to the cardholder's bank.\n\nThe evidence submitted by this endpoint includes evidence uploaded\nusing the [CreateDisputeEvidenceFile](api-endpoint:Disputes-CreateDisputeEvidenceFile) and\n[CreateDisputeEvidenceText](api-endpoint:Disputes-CreateDisputeEvidenceText) endpoints and\nevidence automatically provided by Square, when available. Evidence cannot be removed from\na dispute after submission.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "DISPUTES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/employees": {
      "get": {
        "tags": [
          "Employees"
        ],
        "summary": "ListEmployees",
        "operationId": "ListEmployees",
        "description": "",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2020-08-26",
          "retirementDate": "2021-08-26",
          "replacedBy": "SearchTeamMembers",
          "guideUrl": "https://developer.squareup.com/docs/team/migrate-from-v2-employees"
        },
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/employees/{id}": {
      "get": {
        "tags": [
          "Employees"
        ],
        "summary": "RetrieveEmployee",
        "operationId": "RetrieveEmployee",
        "description": "",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2020-08-26",
          "retirementDate": "2021-08-26",
          "replacedBy": "RetrieveTeamMember",
          "guideUrl": "https://developer.squareup.com/docs/team/migrate-from-v2-employees"
        },
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/events": {
      "post": {
        "tags": [
          "Events"
        ],
        "summary": "SearchEvents",
        "operationId": "SearchEvents",
        "description": "Search for Square API events that occur within a 28-day timeframe.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/events/disable": {
      "put": {
        "tags": [
          "Events"
        ],
        "summary": "DisableEvents",
        "operationId": "DisableEvents",
        "description": "Disables events to prevent them from being searchable.\nAll events are disabled by default. You must enable events to make them searchable.\nDisabling events for a specific time period prevents them from being searchable, even if you re-enable them later.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/events/enable": {
      "put": {
        "tags": [
          "Events"
        ],
        "summary": "EnableEvents",
        "operationId": "EnableEvents",
        "description": "Enables events to make them searchable. Only events that occur while in the enabled state are searchable.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/events/types": {
      "get": {
        "tags": [
          "Events"
        ],
        "summary": "ListEventTypes",
        "operationId": "ListEventTypes",
        "description": "Lists all event types that you can subscribe to as webhooks or query using the Events API.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": []
          }
        ]
      }
    },
    "/v2/gift-cards": {
      "get": {
        "tags": [
          "GiftCards"
        ],
        "summary": "ListGiftCards",
        "operationId": "ListGiftCards",
        "description": "Lists all gift cards. You can specify optional filters to retrieve \na subset of the gift cards. Results are sorted by `created_at` in ascending order.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "CreateGiftCard",
        "operationId": "CreateGiftCard",
        "description": "Creates a digital gift card or registers a physical (plastic) gift card. The resulting gift card\nhas a `PENDING` state. To activate a gift card so that it can be redeemed for purchases, call\n[CreateGiftCardActivity](api-endpoint:GiftCardActivities-CreateGiftCardActivity) and create an `ACTIVATE`\nactivity with the initial balance. Alternatively, you can use [RefundPayment](api-endpoint:Refunds-RefundPayment)\nto refund a payment to the new gift card.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "TEMPORARY_ERROR"
          }
        ]
      }
    },
    "/v2/gift-cards/activities": {
      "get": {
        "tags": [
          "GiftCardActivities"
        ],
        "summary": "ListGiftCardActivities",
        "operationId": "ListGiftCardActivities",
        "description": "Lists gift card activities. By default, you get gift card activities for all\ngift cards in the seller's account. You can optionally specify query parameters to\nfilter the list. For example, you can get a list of gift card activities for a gift card,\nfor all gift cards in a specific region, or for activities within a time window.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "GiftCardActivities"
        ],
        "summary": "CreateGiftCardActivity",
        "operationId": "CreateGiftCardActivity",
        "description": "Creates a gift card activity to manage the balance or state of a [gift card](entity:GiftCard).\nFor example, create an `ACTIVATE` activity to activate a gift card with an initial balance before first use.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "INSUFFICIENT_FUNDS"
          },
          {
            "error-code": "PAYMENT_LIMIT_EXCEEDED"
          },
          {
            "error-code": "REFUND_AMOUNT_INVALID"
          },
          {
            "error-code": "TEMPORARY_ERROR"
          }
        ]
      }
    },
    "/v2/gift-cards/from-gan": {
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "RetrieveGiftCardFromGAN",
        "operationId": "RetrieveGiftCardFromGAN",
        "description": "Retrieves a gift card using the gift card account number (GAN).",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/from-nonce": {
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "RetrieveGiftCardFromNonce",
        "operationId": "RetrieveGiftCardFromNonce",
        "description": "Retrieves a gift card using a secure payment token that represents the gift card.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "CARD_TOKEN_EXPIRED"
          },
          {
            "error-code": "CARD_TOKEN_USED"
          }
        ]
      }
    },
    "/v2/gift-cards/{gift_card_id}/link-customer": {
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "LinkCustomerToGiftCard",
        "operationId": "LinkCustomerToGiftCard",
        "description": "Links a customer to a gift card, which is also referred to as adding a card on file.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/{gift_card_id}/unlink-customer": {
      "post": {
        "tags": [
          "GiftCards"
        ],
        "summary": "UnlinkCustomerFromGiftCard",
        "operationId": "UnlinkCustomerFromGiftCard",
        "description": "Unlinks a customer from a gift card, which is also referred to as removing a card on file.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/gift-cards/{id}": {
      "get": {
        "tags": [
          "GiftCards"
        ],
        "summary": "RetrieveGiftCard",
        "operationId": "RetrieveGiftCard",
        "description": "Retrieves a gift card using the gift card ID.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "GIFTCARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/adjustment/{adjustment_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedRetrieveInventoryAdjustment",
        "operationId": "DeprecatedRetrieveInventoryAdjustment",
        "description": "Deprecated version of [RetrieveInventoryAdjustment](api-endpoint:Inventory-RetrieveInventoryAdjustment) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-06-16",
          "retirementDate": "2023-11-15",
          "replacedBy": "RetrieveInventoryAdjustment"
        },
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/adjustments/{adjustment_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryAdjustment",
        "operationId": "RetrieveInventoryAdjustment",
        "description": "Returns the [InventoryAdjustment](entity:InventoryAdjustment) object\nwith the provided `adjustment_id`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-change": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedBatchChangeInventory",
        "operationId": "DeprecatedBatchChangeInventory",
        "description": "Deprecated version of [BatchChangeInventory](api-endpoint:Inventory-BatchChangeInventory) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-06-16",
          "retirementDate": "2023-11-15",
          "replacedBy": "BatchChangeInventory"
        },
        "security": [
          {
            "oauth2": [
              "INVENTORY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-retrieve-changes": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedBatchRetrieveInventoryChanges",
        "operationId": "DeprecatedBatchRetrieveInventoryChanges",
        "description": "Deprecated version of [BatchRetrieveInventoryChanges](api-endpoint:Inventory-BatchRetrieveInventoryChanges) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-06-16",
          "retirementDate": "2023-11-15",
          "replacedBy": "BatchRetrieveInventoryChanges"
        },
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/batch-retrieve-counts": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedBatchRetrieveInventoryCounts",
        "operationId": "DeprecatedBatchRetrieveInventoryCounts",
        "description": "Deprecated version of [BatchRetrieveInventoryCounts](api-endpoint:Inventory-BatchRetrieveInventoryCounts) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-06-16",
          "retirementDate": "2023-11-15",
          "replacedBy": "BatchRetrieveInventoryCounts"
        },
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/changes/batch-create": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchChangeInventory",
        "operationId": "BatchChangeInventory",
        "description": "Applies adjustments and counts to the provided item quantities.\n\nOn success: returns the current calculated counts for all objects\nreferenced in the request.\nOn failure: returns a list of related errors.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVENTORY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/inventory/changes/batch-retrieve": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchRetrieveInventoryChanges",
        "operationId": "BatchRetrieveInventoryChanges",
        "description": "Returns historical physical counts and adjustments based on the\nprovided filter criteria.\n\nResults are paginated and sorted in ascending order according their\n`occurred_at` timestamp (oldest first).\n\nBatchRetrieveInventoryChanges is a catch-all query endpoint for queries\nthat cannot be handled by other, simpler endpoints.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/counts/batch-retrieve": {
      "post": {
        "tags": [
          "Inventory"
        ],
        "summary": "BatchRetrieveInventoryCounts",
        "operationId": "BatchRetrieveInventoryCounts",
        "description": "Returns current counts for the provided\n[CatalogObject](entity:CatalogObject)s at the requested\n[Location](entity:Location)s.\n\nResults are paginated and sorted in descending order according to their\n`calculated_at` timestamp (newest first).\n\nWhen `updated_after` is specified, only counts that have changed since that\ntime (based on the server timestamp for the most recent change) are\nreturned. This allows clients to perform a \"sync\" operation, for example\nin re[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/physical-count/{physical_count_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "DeprecatedRetrieveInventoryPhysicalCount",
        "operationId": "DeprecatedRetrieveInventoryPhysicalCount",
        "description": "Deprecated version of [RetrieveInventoryPhysicalCount](api-endpoint:Inventory-RetrieveInventoryPhysicalCount) after the endpoint URL\nis updated to conform to the standard convention.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-06-16",
          "retirementDate": "2023-11-15",
          "replacedBy": "RetrieveInventoryPhysicalCount"
        },
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/physical-counts/{physical_count_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryPhysicalCount",
        "operationId": "RetrieveInventoryPhysicalCount",
        "description": "Returns the [InventoryPhysicalCount](entity:InventoryPhysicalCount)\nobject with the provided `physical_count_id`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/transfers/{transfer_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryTransfer",
        "operationId": "RetrieveInventoryTransfer",
        "description": "Returns the [InventoryTransfer](entity:InventoryTransfer) object\nwith the provided `transfer_id`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/{catalog_object_id}": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryCount",
        "operationId": "RetrieveInventoryCount",
        "description": "Retrieves the current calculated stock count for a given\n[CatalogObject](entity:CatalogObject) at a given set of\n[Location](entity:Location)s. Responses are paginated and unsorted.\nFor more sophisticated queries, use a batch endpoint.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/inventory/{catalog_object_id}/changes": {
      "get": {
        "tags": [
          "Inventory"
        ],
        "summary": "RetrieveInventoryChanges",
        "operationId": "RetrieveInventoryChanges",
        "description": "Returns a set of physical counts and inventory adjustments for the\nprovided [CatalogObject](entity:CatalogObject) at the requested\n[Location](entity:Location)s.\n\nYou can achieve the same result by calling [BatchRetrieveInventoryChanges](api-endpoint:Inventory-BatchRetrieveInventoryChanges)\nand having the `catalog_object_ids` list contain a single element of the `CatalogObject` ID.\n\nResults are paginated and sorted in descending order according to their\n`occurred_a[...]",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-06-16",
          "retirementDate": "2023-11-15",
          "replacedBy": "BatchRetrieveInventoryChanges"
        },
        "security": [
          {
            "oauth2": [
              "INVENTORY_READ"
            ]
          }
        ]
      }
    },
    "/v2/invoices": {
      "get": {
        "tags": [
          "Invoices"
        ],
        "summary": "ListInvoices",
        "operationId": "ListInvoices",
        "description": "Returns a list of invoices for a given location. The response \nis paginated. If truncated, the response includes a `cursor` that you    \nuse in a subsequent request to retrieve the next set of invoices.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVOICES_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "CreateInvoice",
        "operationId": "CreateInvoice",
        "description": "Creates a draft [invoice](entity:Invoice) \nfor an order created using the Orders API.\n\nA draft invoice remains in your account and no action is taken. \nYou must publish the invoice before Square can process it (send it to the customer's email address or charge the customer’s card on file).",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "INVALID_CARD"
          },
          {
            "error-code": "MERCHANT_SUBSCRIPTION_NOT_FOUND"
          }
        ]
      }
    },
    "/v2/invoices/search": {
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "SearchInvoices",
        "operationId": "SearchInvoices",
        "description": "Searches for invoices from a location specified in \nthe filter. You can optionally specify customers in the filter for whom to \nretrieve invoices. In the current implementation, you can only specify one location and \noptionally one customer.\n\nThe response is paginated. If truncated, the response includes a `cursor` \nthat you use in a subsequent request to retrieve the next set of invoices.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVOICES_READ"
            ]
          }
        ]
      }
    },
    "/v2/invoices/{invoice_id}": {
      "delete": {
        "tags": [
          "Invoices"
        ],
        "summary": "DeleteInvoice",
        "operationId": "DeleteInvoice",
        "description": "Deletes the specified invoice. When an invoice is deleted, the \nassociated order status changes to CANCELED. You can only delete a draft \ninvoice (you cannot delete a published invoice, including one that is scheduled for processing).",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Invoices"
        ],
        "summary": "GetInvoice",
        "operationId": "GetInvoice",
        "description": "Retrieves an invoice by invoice ID.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVOICES_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Invoices"
        ],
        "summary": "UpdateInvoice",
        "operationId": "UpdateInvoice",
        "description": "Updates an invoice. This endpoint supports sparse updates, so you only need\nto specify the fields you want to change along with the required `version` field.\nSome restrictions apply to updating invoices. For example, you cannot change the\n`order_id` or `location_id` field.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "CARD_DECLINED"
          },
          {
            "error-code": "INVALID_CARD"
          },
          {
            "error-code": "MERCHANT_SUBSCRIPTION_NOT_FOUND"
          }
        ]
      }
    },
    "/v2/invoices/{invoice_id}/attachments": {
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "CreateInvoiceAttachment",
        "operationId": "CreateInvoiceAttachment",
        "description": "Uploads a file and attaches it to an invoice. This endpoint accepts HTTP multipart/form-data file uploads\nwith a JSON `request` part and a `file` part. The `file` part must be a `readable stream` that contains a file\nin a supported format: GIF, JPEG, PNG, TIFF, BMP, or PDF.\n\nInvoices can have up to 10 attachments with a total file size of 25 MB. Attachments can be added only to invoices\nin the `DRAFT`, `SCHEDULED`, `UNPAID`, or `PARTIALLY_PAID` state.\n\n__NOTE:__ Wh[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVOICES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/invoices/{invoice_id}/attachments/{attachment_id}": {
      "delete": {
        "tags": [
          "Invoices"
        ],
        "summary": "DeleteInvoiceAttachment",
        "operationId": "DeleteInvoiceAttachment",
        "description": "Removes an attachment from an invoice and permanently deletes the file. Attachments can be removed only\nfrom invoices in the `DRAFT`, `SCHEDULED`, `UNPAID`, or `PARTIALLY_PAID` state.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "INVOICES_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/invoices/{invoice_id}/cancel": {
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "CancelInvoice",
        "operationId": "CancelInvoice",
        "description": "Cancels an invoice. The seller cannot collect payments for \nthe canceled invoice.\n\nYou cannot cancel an invoice in the `DRAFT` state or in a terminal state: `PAID`, `REFUNDED`, `CANCELED`, or `FAILED`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "VERSION_MISMATCH"
          }
        ]
      }
    },
    "/v2/invoices/{invoice_id}/publish": {
      "post": {
        "tags": [
          "Invoices"
        ],
        "summary": "PublishInvoice",
        "operationId": "PublishInvoice",
        "description": "Publishes the specified draft invoice. \n\nAfter an invoice is published, Square \nfollows up based on the invoice configuration. For example, Square \nsends the invoice to the customer's email address, charges the customer's card on file, or does \nnothing. Square also makes the invoice available on a Square-hosted invoice page. \n\nThe invoice `status` also changes from `DRAFT` to a status \nbased on the invoice configuration. For example, the status changes to `UNPAID`[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "ORDERS_WRITE",
              "INVOICES_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "CARD_DECLINED"
          },
          {
            "error-code": "INVALID_CARD"
          }
        ]
      }
    },
    "/v2/labor/break-types": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListBreakTypes",
        "operationId": "ListBreakTypes",
        "description": "Returns a paginated list of `BreakType` instances for a business.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "CreateBreakType",
        "operationId": "CreateBreakType",
        "description": "Creates a new `BreakType`.\n\nA `BreakType` is a template for creating `Break` objects.\nYou must provide the following values in your request to this\nendpoint:\n\n- `location_id`\n- `break_name`\n- `expected_duration`\n- `is_paid`\n\nYou can only have three `BreakType` instances per location. If you attempt to add a fourth\n`BreakType` for a location, an `INVALID_REQUEST_ERROR` \"Exceeded limit of 3 breaks per location.\"\nis returned.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/labor/break-types/{id}": {
      "delete": {
        "tags": [
          "Labor"
        ],
        "summary": "DeleteBreakType",
        "operationId": "DeleteBreakType",
        "description": "Deletes an existing `BreakType`.\n\nA `BreakType` can be deleted even if it is referenced from a `Shift`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetBreakType",
        "operationId": "GetBreakType",
        "description": "Returns a single `BreakType` specified by `id`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateBreakType",
        "operationId": "UpdateBreakType",
        "description": "Updates an existing `BreakType`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE",
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/employee-wages": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListEmployeeWages",
        "operationId": "ListEmployeeWages",
        "description": "Returns a paginated list of `EmployeeWage` instances for a business.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2020-08-26",
          "retirementDate": "TBD",
          "replacedBy": "ListTeamMemberWages",
          "guideUrl": "https://developer.squareup.com/docs/labor-api/migrate-to-teams"
        },
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/employee-wages/{id}": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetEmployeeWage",
        "operationId": "GetEmployeeWage",
        "description": "Returns a single `EmployeeWage` specified by `id`.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2020-08-26",
          "retirementDate": "TBD",
          "replacedBy": "GetTeamMemberWage",
          "guideUrl": "https://developer.squareup.com/docs/labor-api/migrate-to-teams"
        },
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/scheduled-shifts": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "CreateScheduledShift",
        "operationId": "CreateScheduledShift",
        "description": "Creates a scheduled shift by providing draft shift details such as job ID,\nteam member assignment, and start and end times.\n\nThe following `draft_shift_details` fields are required:\n- `location_id`\n- `job_id`\n- `start_at`\n- `end_at`",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "INVALID_VALUE"
          }
        ]
      }
    },
    "/v2/labor/scheduled-shifts/bulk-publish": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "BulkPublishScheduledShifts",
        "operationId": "BulkPublishScheduledShifts",
        "description": "Publishes 1 - 100 scheduled shifts. This endpoint takes a map of individual publish\nrequests and returns a map of responses. When a scheduled shift is published, Square keeps\nthe `draft_shift_details` field as is and copies it to the `published_shift_details` field.\n\nThe minimum `start_at` and maximum `end_at` timestamps of all shifts in a\n`BulkPublishScheduledShifts` request must fall within a two-week period.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "INVALID_VALUE"
          }
        ]
      }
    },
    "/v2/labor/scheduled-shifts/search": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "SearchScheduledShifts",
        "operationId": "SearchScheduledShifts",
        "description": "Returns a paginated list of scheduled shifts, with optional filter and sort settings.\nBy default, results are sorted by `start_at` in ascending order.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "EXPECTED_STRING"
          },
          {
            "error-code": "INVALID_VALUE"
          },
          {
            "error-code": "NOT_FOUND"
          }
        ]
      }
    },
    "/v2/labor/scheduled-shifts/{id}": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "RetrieveScheduledShift",
        "operationId": "RetrieveScheduledShift",
        "description": "Retrieves a scheduled shift by ID.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "NOT_FOUND"
          }
        ]
      },
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateScheduledShift",
        "operationId": "UpdateScheduledShift",
        "description": "Updates the draft shift details for a scheduled shift. This endpoint supports\nsparse updates, so only new, changed, or removed fields are required in the request.\nYou must publish the shift to make updates public.\n\nYou can make the following updates to `draft_shift_details`:\n- Change the `location_id`, `job_id`, `start_at`, and `end_at` fields.\n- Add, change, or clear the `team_member_id` and `notes` fields. To clear these fields,\nset the value to null.\n- Change t[...]",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "INVALID_VALUE"
          },
          {
            "error-code": "VERSION_MISMATCH"
          }
        ]
      }
    },
    "/v2/labor/scheduled-shifts/{id}/publish": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "PublishScheduledShift",
        "operationId": "PublishScheduledShift",
        "description": "Publishes a scheduled shift. When a scheduled shift is published, Square keeps the\n`draft_shift_details` field as is and copies it to the `published_shift_details` field.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "INVALID_VALUE"
          }
        ]
      }
    },
    "/v2/labor/shifts": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "CreateShift",
        "operationId": "CreateShift",
        "description": "Creates a new `Shift`.\n\nA `Shift` represents a complete workday for a single team member.\nYou must provide the following values in your request to this\nendpoint:\n\n- `location_id`\n- `team_member_id`\n- `start_at`\n\nAn attempt to create a new `Shift` can result in a `BAD_REQUEST` error when:\n- The `status` of the new `Shift` is `OPEN` and the team member has another\nshift with an `OPEN` status.\n- The `start_at` date is in the future.\n- The `start_at` or `end_at`[...]",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2025-05-21",
          "retirementDate": "2026-05-21",
          "replacedBy": "CreateTimecard",
          "guideUrl": "https://developer.squareup.com/docs/labor-api/what-it-does#migration-notes"
        },
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/labor/shifts/search": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "SearchShifts",
        "operationId": "SearchShifts",
        "description": "Returns a paginated list of `Shift` records for a business.\nThe list to be returned can be filtered by:\n- Location IDs\n- Team member IDs\n- Shift status (`OPEN` or `CLOSED`)\n- Shift start\n- Shift end\n- Workday details\n\nThe list can be sorted by:\n- `START_AT`\n- `END_AT`\n- `CREATED_AT`\n- `UPDATED_AT`",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2025-05-21",
          "retirementDate": "2026-05-21",
          "replacedBy": "SearchTimecards",
          "guideUrl": "https://developer.squareup.com/docs/labor-api/what-it-does#migration-notes"
        },
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/shifts/{id}": {
      "delete": {
        "tags": [
          "Labor"
        ],
        "summary": "DeleteShift",
        "operationId": "DeleteShift",
        "description": "Deletes a `Shift`.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2025-05-21",
          "retirementDate": "2026-05-21",
          "replacedBy": "DeleteTimecard",
          "guideUrl": "https://developer.squareup.com/docs/labor-api/what-it-does#migration-notes"
        },
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetShift",
        "operationId": "GetShift",
        "description": "Returns a single `Shift` specified by `id`.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2025-05-21",
          "retirementDate": "2026-05-21",
          "replacedBy": "RetrieveTimecard",
          "guideUrl": "https://developer.squareup.com/docs/labor-api/what-it-does#migration-notes"
        },
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateShift",
        "operationId": "UpdateShift",
        "description": "Updates an existing `Shift`.\n\nWhen adding a `Break` to a `Shift`, any earlier `Break` instances in the `Shift` have\nthe `end_at` property set to a valid RFC-3339 datetime string.\n\nWhen closing a `Shift`, all `Break` instances in the `Shift` must be complete with `end_at`\nset on each `Break`.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2025-05-21",
          "retirementDate": "2026-05-21",
          "replacedBy": "UpdateTimecard",
          "guideUrl": "https://developer.squareup.com/docs/labor-api/what-it-does#migration-notes"
        },
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE",
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/team-member-wages": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListTeamMemberWages",
        "operationId": "ListTeamMemberWages",
        "description": "Returns a paginated list of `TeamMemberWage` instances for a business.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/team-member-wages/{id}": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "GetTeamMemberWage",
        "operationId": "GetTeamMemberWage",
        "description": "Returns a single `TeamMemberWage` specified by `id`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "EMPLOYEES_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/timecards": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "CreateTimecard",
        "operationId": "CreateTimecard",
        "description": "Creates a new `Timecard`.\n\nA `Timecard` represents a complete workday for a single team member.\nYou must provide the following values in your request to this\nendpoint:\n\n- `location_id`\n- `team_member_id`\n- `start_at`\n\nAn attempt to create a new `Timecard` can result in a `BAD_REQUEST` error when:\n- The `status` of the new `Timecard` is `OPEN` and the team member has another\ntimecard with an `OPEN` status.\n- The `start_at` date is in the future.\n- The `start_[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "INVALID_VALUE"
          },
          {
            "error-code": "NOT_FOUND"
          }
        ]
      }
    },
    "/v2/labor/timecards/search": {
      "post": {
        "tags": [
          "Labor"
        ],
        "summary": "SearchTimecards",
        "operationId": "SearchTimecards",
        "description": "Returns a paginated list of `Timecard` records for a business.\nThe list to be returned can be filtered by:\n- Location IDs\n- Team member IDs\n- Timecard status (`OPEN` or `CLOSED`)\n- Timecard start\n- Timecard end\n- Workday details\n\nThe list can be sorted by:\n- `START_AT`\n- `END_AT`\n- `CREATED_AT`\n- `UPDATED_AT`",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/timecards/{id}": {
      "delete": {
        "tags": [
          "Labor"
        ],
        "summary": "DeleteTimecard",
        "operationId": "DeleteTimecard",
        "description": "Deletes a `Timecard`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "NOT_FOUND"
          }
        ]
      },
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "RetrieveTimecard",
        "operationId": "RetrieveTimecard",
        "description": "Returns a single `Timecard` specified by `id`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "NOT_FOUND"
          }
        ]
      },
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateTimecard",
        "operationId": "UpdateTimecard",
        "description": "Updates an existing `Timecard`.\n\nWhen adding a `Break` to a `Timecard`, any earlier `Break` instances in the `Timecard` have\nthe `end_at` property set to a valid RFC-3339 datetime string.\n\nWhen closing a `Timecard`, all `Break` instances in the `Timecard` must be complete with `end_at`\nset on each `Break`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_WRITE",
              "TIMECARDS_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          },
          {
            "error-code": "INVALID_VALUE"
          },
          {
            "error-code": "VERSION_MISMATCH"
          }
        ]
      }
    },
    "/v2/labor/workweek-configs": {
      "get": {
        "tags": [
          "Labor"
        ],
        "summary": "ListWorkweekConfigs",
        "operationId": "ListWorkweekConfigs",
        "description": "Returns a list of `WorkweekConfig` instances for a business.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/labor/workweek-configs/{id}": {
      "put": {
        "tags": [
          "Labor"
        ],
        "summary": "UpdateWorkweekConfig",
        "operationId": "UpdateWorkweekConfig",
        "description": "Updates a `WorkweekConfig`.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "TIMECARDS_SETTINGS_WRITE",
              "TIMECARDS_SETTINGS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "ListLocations",
        "operationId": "ListLocations",
        "description": "Provides details about all of the seller's [locations](https://developer.squareup.com/docs/locations-api),\nincluding those with an inactive status. Locations are listed alphabetically by `name`.",
        "x-release-status": "PUBLIC",
        "x-unitTests": [
          {
            "expectedResponse": {
              "statusCode": "200",
              "x-allowExtraHeaders": true,
              "x-arrayCheckCount": false,
              "x-arrayOrderedMatching": false,
              "x-bodyMatchMode": "NONE",
              "x-matchResponseSchema": true
            },
            "x-testEnabled": true,
            "x-testName": "ListLocations",
            "x-testShouldPass": true
          }
        ],
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Locations"
        ],
        "summary": "CreateLocation",
        "operationId": "CreateLocation",
        "description": "Creates a [location](https://developer.squareup.com/docs/locations-api).\nCreating new locations allows for separate configuration of receipt layouts, item prices,\nand sales reports. Developers can use locations to separate sales activity through applications\nthat integrate with Square from sales activity elsewhere in a seller's account.\nLocations created programmatically with the Locations API last forever and\nare visible to the seller for their own management. There[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          }
        ]
      }
    },
    "/v2/locations/custom-attribute-definitions": {
      "get": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "ListLocationCustomAttributeDefinitions",
        "operationId": "ListLocationCustomAttributeDefinitions",
        "description": "Lists the location-related [custom attribute definitions](entity:CustomAttributeDefinition) that belong to a Square seller account.\nWhen all response pages are retrieved, the results include all custom attribute definitions\nthat are visible to the requesting application, including those that are created by other\napplications and set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "CreateLocationCustomAttributeDefinition",
        "operationId": "CreateLocationCustomAttributeDefinition",
        "description": "Creates a location-related [custom attribute definition](entity:CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to define a custom attribute that can be associated with locations.\nA custom attribute definition specifies the `key`, `visibility`, `schema`, and other properties\nfor a custom attribute. After the definition is created, you can call\n[UpsertLocationCustomAttribute](api-endpoint:LocationCustomAttributes-UpsertLocationCustomAttribute)[...]",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "DeleteLocationCustomAttributeDefinition",
        "operationId": "DeleteLocationCustomAttributeDefinition",
        "description": "Deletes a location-related [custom attribute definition](entity:CustomAttributeDefinition) from a Square seller account.\nDeleting a custom attribute definition also deletes the corresponding custom attribute from\nall locations.\nOnly the definition owner can delete a custom attribute definition.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "RetrieveLocationCustomAttributeDefinition",
        "operationId": "RetrieveLocationCustomAttributeDefinition",
        "description": "Retrieves a location-related [custom attribute definition](entity:CustomAttributeDefinition) from a Square seller account.\nTo retrieve a custom attribute definition created by another application, the `visibility`\nsetting must be `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "UpdateLocationCustomAttributeDefinition",
        "operationId": "UpdateLocationCustomAttributeDefinition",
        "description": "Updates a location-related [custom attribute definition](entity:CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to update the following fields: `name`, `description`, `visibility`, or the\n`schema` for a `Selection` data type.\nOnly the definition owner can update a custom attribute definition.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/custom-attributes/bulk-delete": {
      "post": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "BulkDeleteLocationCustomAttributes",
        "operationId": "BulkDeleteLocationCustomAttributes",
        "description": "Deletes [custom attributes](entity:CustomAttribute) for locations as a bulk operation.\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "BulkUpsertLocationCustomAttributes",
        "operationId": "BulkUpsertLocationCustomAttributes",
        "description": "Creates or updates [custom attributes](entity:CustomAttribute) for locations as a bulk operation.\nUse this endpoint to set the value of one or more custom attributes for one or more locations.\nA custom attribute is based on a custom attribute definition in a Square seller account, which is\ncreated using the [CreateLocationCustomAttributeDefinition](api-endpoint:LocationCustomAttributes-CreateLocationCustomAttributeDefinition) endpoint.\nThis `BulkUpsertLocationCustomAt[...]",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "RetrieveLocation",
        "operationId": "RetrieveLocation",
        "description": "Retrieves details of a single location. Specify \"main\"\nas the location ID to retrieve details of the [main location](https://developer.squareup.com/docs/locations-api#about-the-main-location).",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "NOT_FOUND"
          }
        ]
      },
      "put": {
        "tags": [
          "Locations"
        ],
        "summary": "UpdateLocation",
        "operationId": "UpdateLocation",
        "description": "Updates a [location](https://developer.squareup.com/docs/locations-api).",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "BAD_REQUEST"
          }
        ]
      }
    },
    "/v2/locations/{location_id}/checkouts": {
      "post": {
        "tags": [
          "Checkout"
        ],
        "summary": "CreateCheckout",
        "operationId": "CreateCheckout",
        "description": "Links a `checkoutId` to a `checkout_page_url` that customers are\ndirected to in order to provide their payment information using a\npayment processing workflow hosted on connect.squareup.com. \n\n\nNOTE: The Checkout API has been updated with new features. \nFor more information, see [Checkout API highlights](https://developer.squareup.com/docs/checkout-api#checkout-api-highlights).",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2022-08-17",
          "retirementDate": "TBD",
          "replacedBy": "CreatePaymentLink",
          "guideUrl": "https://developer.squareup.com/docs/migrate-from-v1/guides/v1-checkout"
        },
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE",
              "ORDERS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "AMOUNT_TOO_HIGH"
          },
          {
            "error-code": "CARD_PROCESSING_NOT_ENABLED"
          },
          {
            "error-code": "ORDER_EXPIRED"
          }
        ]
      }
    },
    "/v2/locations/{location_id}/custom-attributes": {
      "get": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "ListLocationCustomAttributes",
        "operationId": "ListLocationCustomAttributes",
        "description": "Lists the [custom attributes](entity:CustomAttribute) associated with a location.\nYou can use the `with_definitions` query parameter to also retrieve custom attribute definitions\nin the same call.\nWhen all response pages are retrieved, the results include all custom attributes that are\nvisible to the requesting application, including those that are owned by other applications\nand set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/custom-attributes/{key}": {
      "delete": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "DeleteLocationCustomAttribute",
        "operationId": "DeleteLocationCustomAttribute",
        "description": "Deletes a [custom attribute](entity:CustomAttribute) associated with a location.\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "RetrieveLocationCustomAttribute",
        "operationId": "RetrieveLocationCustomAttribute",
        "description": "Retrieves a [custom attribute](entity:CustomAttribute) associated with a location.\nYou can use the `with_definition` query parameter to also retrieve the custom attribute definition\nin the same call.\nTo retrieve a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "LocationCustomAttributes"
        ],
        "summary": "UpsertLocationCustomAttribute",
        "operationId": "UpsertLocationCustomAttribute",
        "description": "Creates or updates a [custom attribute](entity:CustomAttribute) for a location.\nUse this endpoint to set the value of a custom attribute for a specified location.\nA custom attribute is based on a custom attribute definition in a Square seller account, which\nis created using the [CreateLocationCustomAttributeDefinition](api-endpoint:LocationCustomAttributes-CreateLocationCustomAttributeDefinition) endpoint.\nTo create or update a custom attribute owned by another applic[...]",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "ListTransactions",
        "operationId": "ListTransactions",
        "description": "Lists transactions for a particular location.\n\nTransactions include payment information from sales and exchanges and refund\ninformation from returns and exchanges.\n\nMax results per [page](https://developer.squareup.com/docs/working-with-apis/pagination): 50",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2019-08-15",
          "retirementDate": "TBD",
          "replacedBy": "SearchOrders",
          "guideUrl": "https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api"
        },
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}": {
      "get": {
        "tags": [
          "Transactions"
        ],
        "summary": "RetrieveTransaction",
        "operationId": "RetrieveTransaction",
        "description": "Retrieves details for a single transaction.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2019-08-15",
          "retirementDate": "TBD",
          "replacedBy": "BatchRetrieveOrders",
          "guideUrl": "https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api"
        },
        "security": [
          {
            "oauth2": [
              "PAYMENTS_READ"
            ]
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/capture": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "CaptureTransaction",
        "operationId": "CaptureTransaction",
        "description": "Captures a transaction that was created with the [Charge](api-endpoint:Transactions-Charge)\nendpoint with a `delay_capture` value of `true`.\n\n\nSee [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)\nfor more information.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2019-08-15",
          "retirementDate": "TBD",
          "replacedBy": "CompletePayment",
          "guideUrl": "https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api"
        },
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "DELAYED_TRANSACTION_CANCELED"
          },
          {
            "error-code": "DELAYED_TRANSACTION_EXPIRED"
          }
        ]
      }
    },
    "/v2/locations/{location_id}/transactions/{transaction_id}/void": {
      "post": {
        "tags": [
          "Transactions"
        ],
        "summary": "VoidTransaction",
        "operationId": "VoidTransaction",
        "description": "Cancels a transaction that was created with the [Charge](api-endpoint:Transactions-Charge)\nendpoint with a `delay_capture` value of `true`.\n\n\nSee [Delayed capture transactions](https://developer.squareup.com/docs/payments/transactions/overview#delayed-capture)\nfor more information.",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2019-08-15",
          "retirementDate": "TBD",
          "replacedBy": "CancelPayment",
          "guideUrl": "https://developer.squareup.com/docs/payments-api/migrate-from-transactions-api"
        },
        "security": [
          {
            "oauth2": [
              "PAYMENTS_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "DELAYED_TRANSACTION_CAPTURED"
          },
          {
            "error-code": "DELAYED_TRANSACTION_EXPIRED"
          }
        ]
      }
    },
    "/v2/loyalty/accounts": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CreateLoyaltyAccount",
        "operationId": "CreateLoyaltyAccount",
        "description": "Creates a loyalty account. To create a loyalty account, you must provide the `program_id` and a `mapping` with the `phone_number` of the buyer.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "INVALID_PHONE_NUMBER"
          }
        ]
      }
    },
    "/v2/loyalty/accounts/search": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "SearchLoyaltyAccounts",
        "operationId": "SearchLoyaltyAccounts",
        "description": "Searches for loyalty accounts in a loyalty program.\n\nYou can search for a loyalty account using the phone number or customer ID associated with the account. To return all loyalty accounts, specify an empty `query` object or omit it entirely.\n\nSearch results are sorted by `created_at` in ascending order.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/accounts/{account_id}": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RetrieveLoyaltyAccount",
        "operationId": "RetrieveLoyaltyAccount",
        "description": "Retrieves a loyalty account.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/accounts/{account_id}/accumulate": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "AccumulateLoyaltyPoints",
        "operationId": "AccumulateLoyaltyPoints",
        "description": "Adds points earned from a purchase to a [loyalty account](entity:LoyaltyAccount).\n\n- If you are using the Orders API to manage orders, provide the `order_id`. Square reads the order\nto compute the points earned from both the base loyalty program and an associated\n[loyalty promotion](entity:LoyaltyPromotion). For purchases that qualify for multiple accrual\nrules, Square computes points based on the accrual rule that grants the most points.\nFor purchases that qualify [...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/accounts/{account_id}/adjust": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "AdjustLoyaltyPoints",
        "operationId": "AdjustLoyaltyPoints",
        "description": "Adds points to or subtracts points from a buyer's account.\n\nUse this endpoint only when you need to manually adjust points. Otherwise, in your application flow, you call\n[AccumulateLoyaltyPoints](api-endpoint:Loyalty-AccumulateLoyaltyPoints)\nto add points when a buyer pays for the purchase.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/events/search": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "SearchLoyaltyEvents",
        "operationId": "SearchLoyaltyEvents",
        "description": "Searches for loyalty events.\n\nA Square loyalty program maintains a ledger of events that occur during the lifetime of a\nbuyer's loyalty account. Each change in the point balance\n(for example, points earned, points redeemed, and points expired) is\nrecorded in the ledger. Using this endpoint, you can search the ledger for events.\n\nSearch results are sorted by `created_at` in descending order.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "ListLoyaltyPrograms",
        "operationId": "ListLoyaltyPrograms",
        "description": "Returns a list of loyalty programs in the seller's account.\nLoyalty programs define how buyers can earn points and redeem points for rewards. Square sellers can have only one loyalty program, which is created and managed from the Seller Dashboard. For more information, see [Loyalty Program Overview](https://developer.squareup.com/docs/loyalty/overview).\n\n\nReplaced with [RetrieveLoyaltyProgram](api-endpoint:Loyalty-RetrieveLoyaltyProgram) when used with the keyword `ma[...]",
        "x-release-status": "DEPRECATED",
        "deprecated": true,
        "x-deprecation": {
          "deprecationDate": "2021-05-13",
          "replacedBy": "RetrieveLoyaltyProgram",
          "guideUrl": "https://developer.squareup.com/docs/loyalty-api/overview#migration-notes"
        },
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "UNSUPPORTED_LOYALTY_REWARD_TIER"
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RetrieveLoyaltyProgram",
        "operationId": "RetrieveLoyaltyProgram",
        "description": "Retrieves the loyalty program in a seller's account, specified by the program ID or the keyword `main`.\n\nLoyalty programs define how buyers can earn points and redeem points for rewards. Square sellers can have only one loyalty program, which is created and managed from the Seller Dashboard. For more information, see [Loyalty Program Overview](https://developer.squareup.com/docs/loyalty/overview).",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ],
        "x-endpoint-errors": [
          {
            "error-code": "UNSUPPORTED_LOYALTY_REWARD_TIER"
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}/calculate": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CalculateLoyaltyPoints",
        "operationId": "CalculateLoyaltyPoints",
        "description": "Calculates the number of points a buyer can earn from a purchase. Applications might call this endpoint\nto display the points to the buyer.\n\n- If you are using the Orders API to manage orders, provide the `order_id` and (optional) `loyalty_account_id`.\nSquare reads the order to compute the points earned from the base loyalty program and an associated\n[loyalty promotion](entity:LoyaltyPromotion).\n\n- If you are not using the Orders API to manage orders, provide `tran[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}/promotions": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "ListLoyaltyPromotions",
        "operationId": "ListLoyaltyPromotions",
        "description": "Lists the loyalty promotions associated with a [loyalty program](entity:LoyaltyProgram).\nResults are sorted by the `created_at` date in descending order (newest to oldest).",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CreateLoyaltyPromotion",
        "operationId": "CreateLoyaltyPromotion",
        "description": "Creates a loyalty promotion for a [loyalty program](entity:LoyaltyProgram). A loyalty promotion\nenables buyers to earn points in addition to those earned from the base loyalty program.\n\nThis endpoint sets the loyalty promotion to the `ACTIVE` or `SCHEDULED` status, depending on the\n`available_time` setting. A loyalty program can have a maximum of 10 loyalty promotions with an\n`ACTIVE` or `SCHEDULED` status.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}/promotions/{promotion_id}": {
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RetrieveLoyaltyPromotion",
        "operationId": "RetrieveLoyaltyPromotion",
        "description": "Retrieves a loyalty promotion.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/programs/{program_id}/promotions/{promotion_id}/cancel": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CancelLoyaltyPromotion",
        "operationId": "CancelLoyaltyPromotion",
        "description": "Cancels a loyalty promotion. Use this endpoint to cancel an `ACTIVE` promotion earlier than the\nend date, cancel an `ACTIVE` promotion when an end date is not specified, or cancel a `SCHEDULED` promotion.\nBecause updating a promotion is not supported, you can also use this endpoint to cancel a promotion before\nyou create a new one.\n\nThis endpoint sets the loyalty promotion to the `CANCELED` state",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/rewards": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "CreateLoyaltyReward",
        "operationId": "CreateLoyaltyReward",
        "description": "Creates a loyalty reward. In the process, the endpoint does following:\n\n- Uses the `reward_tier_id` in the request to determine the number of points\nto lock for this reward.\n- If the request includes `order_id`, it adds the reward and related discount to the order.\n\nAfter a reward is created, the points are locked and\nnot available for the buyer to redeem another reward.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/rewards/search": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "SearchLoyaltyRewards",
        "operationId": "SearchLoyaltyRewards",
        "description": "Searches for loyalty rewards. This endpoint accepts a request with no query filters and returns results for all loyalty accounts.\nIf you include a `query` object, `loyalty_account_id` is required and `status` is  optional.\n\nIf you know a reward ID, use the\n[RetrieveLoyaltyReward](api-endpoint:Loyalty-RetrieveLoyaltyReward) endpoint.\n\nSearch results are sorted by `updated_at` in descending order.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/rewards/{reward_id}": {
      "delete": {
        "tags": [
          "Loyalty"
        ],
        "summary": "DeleteLoyaltyReward",
        "operationId": "DeleteLoyaltyReward",
        "description": "Deletes a loyalty reward by doing the following:\n\n- Returns the loyalty points back to the loyalty account.\n- If an order ID was specified when the reward was created\n(see [CreateLoyaltyReward](api-endpoint:Loyalty-CreateLoyaltyReward)),\nit updates the order by removing the reward and related\ndiscounts.\n\nYou cannot delete a reward that has reached the terminal state (REDEEMED).",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RetrieveLoyaltyReward",
        "operationId": "RetrieveLoyaltyReward",
        "description": "Retrieves a loyalty reward.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_READ"
            ]
          }
        ]
      }
    },
    "/v2/loyalty/rewards/{reward_id}/redeem": {
      "post": {
        "tags": [
          "Loyalty"
        ],
        "summary": "RedeemLoyaltyReward",
        "operationId": "RedeemLoyaltyReward",
        "description": "Redeems a loyalty reward.\n\nThe endpoint sets the reward to the `REDEEMED` terminal state.\n\nIf you are using your own order processing system (not using the\nOrders API), you call this endpoint after the buyer paid for the\npurchase.\n\nAfter the reward reaches the terminal state, it cannot be deleted.\nIn other words, points used for the reward cannot be returned\nto the account.",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "LOYALTY_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants": {
      "get": {
        "tags": [
          "Merchants"
        ],
        "summary": "ListMerchants",
        "operationId": "ListMerchants",
        "description": "Provides details about the merchant associated with a given access token.\n\nThe access token used to connect your application to a Square seller is associated\nwith a single merchant. That means that `ListMerchants` returns a list\nwith a single `Merchant` object. You can specify your personal access token\nto get your own merchant information or specify an OAuth token to get the\ninformation for the merchant that granted your application access.\n\nIf you know the merch[...]",
        "x-release-status": "PUBLIC",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      }
    },
    "/v2/merchants/custom-attribute-definitions": {
      "get": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "ListMerchantCustomAttributeDefinitions",
        "operationId": "ListMerchantCustomAttributeDefinitions",
        "description": "Lists the merchant-related [custom attribute definitions](entity:CustomAttributeDefinition) that belong to a Square seller account.\nWhen all response pages are retrieved, the results include all custom attribute definitions\nthat are visible to the requesting application, including those that are created by other\napplications and set to `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "CreateMerchantCustomAttributeDefinition",
        "operationId": "CreateMerchantCustomAttributeDefinition",
        "description": "Creates a merchant-related [custom attribute definition](entity:CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to define a custom attribute that can be associated with a merchant connecting to your application.\nA custom attribute definition specifies the `key`, `visibility`, `schema`, and other properties\nfor a custom attribute. After the definition is created, you can call\n[UpsertMerchantCustomAttribute](api-endpoint:MerchantCustomAttribute[...]",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants/custom-attribute-definitions/{key}": {
      "delete": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "DeleteMerchantCustomAttributeDefinition",
        "operationId": "DeleteMerchantCustomAttributeDefinition",
        "description": "Deletes a merchant-related [custom attribute definition](entity:CustomAttributeDefinition) from a Square seller account.\nDeleting a custom attribute definition also deletes the corresponding custom attribute from\nthe merchant.\nOnly the definition owner can delete a custom attribute definition.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "RetrieveMerchantCustomAttributeDefinition",
        "operationId": "RetrieveMerchantCustomAttributeDefinition",
        "description": "Retrieves a merchant-related [custom attribute definition](entity:CustomAttributeDefinition) from a Square seller account.\nTo retrieve a custom attribute definition created by another application, the `visibility`\nsetting must be `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_READ"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "UpdateMerchantCustomAttributeDefinition",
        "operationId": "UpdateMerchantCustomAttributeDefinition",
        "description": "Updates a merchant-related [custom attribute definition](entity:CustomAttributeDefinition) for a Square seller account.\nUse this endpoint to update the following fields: `name`, `description`, `visibility`, or the\n`schema` for a `Selection` data type.\nOnly the definition owner can update a custom attribute definition.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants/custom-attributes/bulk-delete": {
      "post": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "BulkDeleteMerchantCustomAttributes",
        "operationId": "BulkDeleteMerchantCustomAttributes",
        "description": "Deletes [custom attributes](entity:CustomAttribute) for a merchant as a bulk operation.\nTo delete a custom attribute owned by another application, the `visibility` setting must be\n`VISIBILITY_READ_WRITE_VALUES`.",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
    "/v2/merchants/custom-attributes/bulk-upsert": {
      "post": {
        "tags": [
          "MerchantCustomAttributes"
        ],
        "summary": "BulkUpsertMerchantCustomAttributes",
        "operationId": "BulkUpsertMerchantCustomAttributes",
        "description": "Creates or updates [custom attributes](entity:CustomAttribute) for a merchant as a bulk operation.\nUse this endpoint to set the value of one or more custom attributes for a merchant.\nA custom attribute is based on a custom attribute definition in a Square seller account, which is\ncreated using the [CreateMerchantCustomAttributeDefinition](api-endpoint:MerchantCustomAttributes-CreateMerchantCustomAttributeDefinition) endpoint.\nThis `BulkUpsertMerchantCustomAttributes` [...]",
        "x-release-status": "BETA",
        "security": [
          {
            "oauth2": [
              "MERCHANT_PROFILE_WRITE"
            ]
          }
        ]
      }
    },
[...]
