/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         promotionId: "promotion_id",
 *         programId: "program_id"
 *     }
 */
export interface CancelPromotionsRequest {
    /**
     * The ID of the [loyalty promotion](entity:LoyaltyPromotion) to cancel. You can cancel a
     * promotion that has an `ACTIVE` or `SCHEDULED` status.
     */
    promotionId: string;
    /**
     * The ID of the base [loyalty program](entity:LoyaltyProgram).
     */
    programId: string;
}
