/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         promotion_id: "promotion_id",
 *         program_id: "program_id"
 *     }
 */
export interface GetPromotionsRequest {
    /**
     * The ID of the [loyalty promotion](entity:LoyaltyPromotion) to retrieve.
     */
    promotion_id: string;
    /**
     * The ID of the base [loyalty program](entity:LoyaltyProgram). To get the program ID,
     * call [RetrieveLoyaltyProgram](api-endpoint:Loyalty-RetrieveLoyaltyProgram) using the `main` keyword.
     */
    program_id: string;
}
