/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../../../index.js";

/**
 * @example
 *     {
 *         idempotency_key: "cd9e25dc-d9f2-4430-aedb-61605070e95f",
 *         quick_pay: {
 *             name: "Auto Detailing",
 *             price_money: {
 *                 amount: BigInt("10000"),
 *                 currency: "USD"
 *             },
 *             location_id: "A9Y43N9ABXZBP"
 *         }
 *     }
 */
export interface CreatePaymentLinkRequest {
    /**
     * A unique string that identifies this `CreatePaymentLinkRequest` request.
     * If you do not provide a unique string (or provide an empty string as the value),
     * the endpoint treats each request as independent.
     *
     * For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency).
     */
    idempotency_key?: string;
    /**
     * A description of the payment link. You provide this optional description that is useful in your
     * application context. It is not used anywhere.
     */
    description?: string;
    /**
     * Describes an ad hoc item and price for which to generate a quick pay checkout link.
     * For more information,
     * see [Quick Pay Checkout](https://developer.squareup.com/docs/checkout-api/quick-pay-checkout).
     */
    quick_pay?: Square.QuickPay;
    /**
     * Describes the `Order` for which to create a checkout link.
     * For more information,
     * see [Square Order Checkout](https://developer.squareup.com/docs/checkout-api/square-order-checkout).
     */
    order?: Square.Order;
    /**
     * Describes optional fields to add to the resulting checkout page.
     * For more information,
     * see [Optional Checkout Configurations](https://developer.squareup.com/docs/checkout-api/optional-checkout-configurations).
     */
    checkout_options?: Square.CheckoutOptions;
    /**
     * Describes fields to prepopulate in the resulting checkout page.
     * For more information, see [Prepopulate the shipping address](https://developer.squareup.com/docs/checkout-api/optional-checkout-configurations#prepopulate-the-shipping-address).
     */
    pre_populated_data?: Square.PrePopulatedData;
    /** A note for the payment. After processing the payment, Square adds this note to the resulting `Payment`. */
    payment_note?: string;
}
