/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         payment_link: {
 *             version: 1,
 *             checkout_options: {
 *                 ask_for_shipping_address: true
 *             }
 *         }
 *     }
 */
export interface UpdatePaymentLinkRequest {
    /**
     * The ID of the payment link to update.
     */
    id: string;
    /**
     * The `payment_link` object describing the updates to apply.
     * For more information, see [Update a payment link](https://developer.squareup.com/docs/checkout-api/manage-checkout#update-a-payment-link).
     */
    payment_link: Square.PaymentLink;
}
