/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         programId: "program_id"
 *     }
 */
export interface ProgramsGetRequest {
    /**
     * The ID of the loyalty program or the keyword `main`. Either value can be used to retrieve the single loyalty program that belongs to the seller.
     */
    programId: string;
}
