/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         shift: {
 *             location_id: "PAA1RJZZKXBFG",
 *             start_at: "2019-01-25T03:11:00-05:00",
 *             end_at: "2019-01-25T13:11:00-05:00",
 *             wage: {
 *                 title: "Bartender",
 *                 hourly_rate: {
 *                     amount: BigInt("1500"),
 *                     currency: "USD"
 *                 },
 *                 tip_eligible: true
 *             },
 *             breaks: [{
 *                     id: "X7GAQYVVRRG6P",
 *                     start_at: "2019-01-25T06:11:00-05:00",
 *                     end_at: "2019-01-25T06:16:00-05:00",
 *                     break_type_id: "REGS1EQR1TPZ5",
 *                     name: "Tea Break",
 *                     expected_duration: "PT5M",
 *                     is_paid: true
 *                 }],
 *             version: 1,
 *             team_member_id: "ormj0jJJZ5OZIzxrZYJI",
 *             declared_cash_tip_money: {
 *                 amount: BigInt("500"),
 *                 currency: "USD"
 *             }
 *         }
 *     }
 */
export interface UpdateShiftRequest {
    /**
     * The ID of the object being updated.
     */
    id: string;
    /** The updated `Shift` object. */
    shift: Square.Shift;
}
