/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../index";

/**
 * @example
 *     {
 *         transferOrderId: "transfer_order_id",
 *         idempotencyKey: "EXAMPLE_IDEMPOTENCY_KEY_101",
 *         receipt: {
 *             lineItems: [{
 *                     transferOrderLineUid: "transfer_order_line_uid",
 *                     quantityReceived: "3",
 *                     quantityDamaged: "1",
 *                     quantityCanceled: "1"
 *                 }, {
 *                     transferOrderLineUid: "transfer_order_line_uid",
 *                     quantityReceived: "2",
 *                     quantityCanceled: "1"
 *                 }]
 *         },
 *         version: BigInt("1753118664873")
 *     }
 */
export interface ReceiveTransferOrderRequest {
    /**
     * The ID of the transfer order to receive items for
     */
    transferOrderId: string;
    /** A unique key to make this request idempotent */
    idempotencyKey: string;
    /** The receipt details */
    receipt: Square.TransferOrderGoodsReceipt;
    /** Version for optimistic concurrency */
    version?: bigint;
}
