/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../../../index.js";

/**
 * @example
 *     {
 *         id: "id",
 *         workweek_config: {
 *             start_of_week: "MON",
 *             start_of_day_local_time: "10:00",
 *             version: 10
 *         }
 *     }
 */
export interface UpdateWorkweekConfigRequest {
    /**
     * The UUID for the `WorkweekConfig` object being updated.
     */
    id: string;
    /** The updated `WorkweekConfig` object. */
    workweek_config: Square.WorkweekConfig;
}
