// This file was auto-generated by Fern from our API Definition.

import { SquareClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("SubscriptionsClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            subscriptions: [
                {
                    id: "wbhk_b35f6b3145074cf9ad513610786c19d5",
                    name: "Example Webhook Subscription",
                    enabled: true,
                    event_types: ["payment.created", "payment.updated"],
                    notification_url: "https://example-webhook-url.com",
                    api_version: "2021-12-15",
                    signature_key: "signature_key",
                    created_at: "2022-01-10 23:29:48 +0000 UTC",
                    updated_at: "2022-01-10 23:29:48 +0000 UTC",
                },
            ],
            cursor: "cursor",
        };
        server
            .mockEndpoint({ once: false })
            .get("/v2/webhooks/subscriptions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            subscriptions: [
                {
                    id: "wbhk_b35f6b3145074cf9ad513610786c19d5",
                    name: "Example Webhook Subscription",
                    enabled: true,
                    eventTypes: ["payment.created", "payment.updated"],
                    notificationUrl: "https://example-webhook-url.com",
                    apiVersion: "2021-12-15",
                    signatureKey: "signature_key",
                    createdAt: "2022-01-10 23:29:48 +0000 UTC",
                    updatedAt: "2022-01-10 23:29:48 +0000 UTC",
                },
            ],
            cursor: "cursor",
        };
        const page = await client.webhooks.subscriptions.list({
            cursor: "cursor",
            includeDisabled: true,
            sortOrder: "DESC",
            limit: 1,
        });

        expect(expected.subscriptions).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.subscriptions).toEqual(nextPage.data);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            idempotency_key: "63f84c6c-2200-4c99-846c-2670a1311fbf",
            subscription: {
                name: "Example Webhook Subscription",
                event_types: ["payment.created", "payment.updated"],
                notification_url: "https://example-webhook-url.com",
                api_version: "2021-12-15",
            },
        };
        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            subscription: {
                id: "wbhk_b35f6b3145074cf9ad513610786c19d5",
                name: "Example Webhook Subscription",
                enabled: true,
                event_types: ["payment.created", "payment.updated"],
                notification_url: "https://example-webhook-url.com",
                api_version: "2021-12-15",
                signature_key: "1k9bIJKCeTmSQwyagtNRLg",
                created_at: "2022-01-10 23:29:48 +0000 UTC",
                updated_at: "2022-01-10 23:29:48 +0000 UTC",
            },
        };
        server
            .mockEndpoint()
            .post("/v2/webhooks/subscriptions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.subscriptions.create({
            idempotencyKey: "63f84c6c-2200-4c99-846c-2670a1311fbf",
            subscription: {
                name: "Example Webhook Subscription",
                eventTypes: ["payment.created", "payment.updated"],
                notificationUrl: "https://example-webhook-url.com",
                apiVersion: "2021-12-15",
            },
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            subscription: {
                id: "wbhk_b35f6b3145074cf9ad513610786c19d5",
                name: "Example Webhook Subscription",
                enabled: true,
                eventTypes: ["payment.created", "payment.updated"],
                notificationUrl: "https://example-webhook-url.com",
                apiVersion: "2021-12-15",
                signatureKey: "1k9bIJKCeTmSQwyagtNRLg",
                createdAt: "2022-01-10 23:29:48 +0000 UTC",
                updatedAt: "2022-01-10 23:29:48 +0000 UTC",
            },
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            subscription: {
                id: "wbhk_b35f6b3145074cf9ad513610786c19d5",
                name: "Example Webhook Subscription",
                enabled: true,
                event_types: ["payment.created", "payment.updated"],
                notification_url: "https://example-webhook-url.com",
                api_version: "2021-12-15",
                signature_key: "1k9bIJKCeTmSQwyagtNRLg",
                created_at: "2022-01-10 23:29:48 +0000 UTC",
                updated_at: "2022-01-10 23:29:48 +0000 UTC",
            },
        };
        server
            .mockEndpoint()
            .get("/v2/webhooks/subscriptions/subscription_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.subscriptions.get({
            subscriptionId: "subscription_id",
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            subscription: {
                id: "wbhk_b35f6b3145074cf9ad513610786c19d5",
                name: "Example Webhook Subscription",
                enabled: true,
                eventTypes: ["payment.created", "payment.updated"],
                notificationUrl: "https://example-webhook-url.com",
                apiVersion: "2021-12-15",
                signatureKey: "1k9bIJKCeTmSQwyagtNRLg",
                createdAt: "2022-01-10 23:29:48 +0000 UTC",
                updatedAt: "2022-01-10 23:29:48 +0000 UTC",
            },
        });
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { subscription: { name: "Updated Example Webhook Subscription", enabled: false } };
        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            subscription: {
                id: "wbhk_b35f6b3145074cf9ad513610786c19d5",
                name: "Updated Example Webhook Subscription",
                enabled: false,
                event_types: ["payment.created", "payment.updated"],
                notification_url: "https://example-webhook-url.com",
                api_version: "2021-12-15",
                signature_key: "signature_key",
                created_at: "2022-01-10 23:29:48 +0000 UTC",
                updated_at: "2022-01-10 23:45:51 +0000 UTC",
            },
        };
        server
            .mockEndpoint()
            .put("/v2/webhooks/subscriptions/subscription_id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.subscriptions.update({
            subscriptionId: "subscription_id",
            subscription: {
                name: "Updated Example Webhook Subscription",
                enabled: false,
            },
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            subscription: {
                id: "wbhk_b35f6b3145074cf9ad513610786c19d5",
                name: "Updated Example Webhook Subscription",
                enabled: false,
                eventTypes: ["payment.created", "payment.updated"],
                notificationUrl: "https://example-webhook-url.com",
                apiVersion: "2021-12-15",
                signatureKey: "signature_key",
                createdAt: "2022-01-10 23:29:48 +0000 UTC",
                updatedAt: "2022-01-10 23:45:51 +0000 UTC",
            },
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
        };
        server
            .mockEndpoint()
            .delete("/v2/webhooks/subscriptions/subscription_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.subscriptions.delete({
            subscriptionId: "subscription_id",
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
        });
    });

    test("updateSignatureKey", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { idempotency_key: "ed80ae6b-0654-473b-bbab-a39aee89a60d" };
        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            signature_key: "1k9bIJKCeTmSQwyagtNRLg",
        };
        server
            .mockEndpoint()
            .post("/v2/webhooks/subscriptions/subscription_id/signature-key")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.subscriptions.updateSignatureKey({
            subscriptionId: "subscription_id",
            idempotencyKey: "ed80ae6b-0654-473b-bbab-a39aee89a60d",
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            signatureKey: "1k9bIJKCeTmSQwyagtNRLg",
        });
    });

    test("test", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = { event_type: "payment.created" };
        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            subscription_test_result: {
                id: "23eed5a9-2b12-403e-b212-7e2889aea0f6",
                status_code: 404,
                payload: { key: "value" },
                created_at: "2022-01-11 00:06:48.322945116 +0000 UTC m=+3863.054453746",
                updated_at: "2022-01-11 00:06:48.322945116 +0000 UTC m=+3863.054453746",
                notification_url: "notification_url",
                passes_filter: true,
            },
            notification_url: "notification_url",
            status_code: 1,
            passes_filter: true,
            payload: { key: "value" },
        };
        server
            .mockEndpoint()
            .post("/v2/webhooks/subscriptions/subscription_id/test")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.webhooks.subscriptions.test({
            subscriptionId: "subscription_id",
            eventType: "payment.created",
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            subscriptionTestResult: {
                id: "23eed5a9-2b12-403e-b212-7e2889aea0f6",
                statusCode: 404,
                payload: {
                    key: "value",
                },
                createdAt: "2022-01-11 00:06:48.322945116 +0000 UTC m=+3863.054453746",
                updatedAt: "2022-01-11 00:06:48.322945116 +0000 UTC m=+3863.054453746",
                notificationUrl: "notification_url",
                passesFilter: true,
            },
            notificationUrl: "notification_url",
            statusCode: 1,
            passesFilter: true,
            payload: {
                key: "value",
            },
        });
    });
});
