/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         shift_id: "shift_id",
 *         location_id: "location_id"
 *     }
 */
export interface GetShiftsRequest {
    /**
     * The shift ID.
     */
    shift_id: string;
    /**
     * The ID of the location to retrieve cash drawer shifts from.
     */
    location_id: string;
}
