/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         subscriptionId: "subscription_id"
 *     }
 */
export interface DeleteSubscriptionsRequest {
    /**
     * [REQUIRED] The ID of the [Subscription](entity:WebhookSubscription) to delete.
     */
    subscriptionId: string;
}
