/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Square from "../../../../../api/index";
import * as core from "../../../../../core";

export const RevokeTokenRequest: core.serialization.Schema<
    serializers.RevokeTokenRequest.Raw,
    Square.RevokeTokenRequest
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string().optionalNullable()),
    accessToken: core.serialization.property("access_token", core.serialization.string().optionalNullable()),
    merchantId: core.serialization.property("merchant_id", core.serialization.string().optionalNullable()),
    revokeOnlyAccessToken: core.serialization.property(
        "revoke_only_access_token",
        core.serialization.boolean().optionalNullable(),
    ),
});

export declare namespace RevokeTokenRequest {
    export interface Raw {
        client_id?: (string | null) | null;
        access_token?: (string | null) | null;
        merchant_id?: (string | null) | null;
        revoke_only_access_token?: (boolean | null) | null;
    }
}
