/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Square from "../../../../../api/index";
import * as core from "../../../../../core";
import { CreateOrderRequest } from "../../../../types/CreateOrderRequest";
import { Address } from "../../../../types/Address";
import { ChargeRequestAdditionalRecipient } from "../../../../types/ChargeRequestAdditionalRecipient";

export const CreateCheckoutRequest: core.serialization.Schema<
    serializers.CreateCheckoutRequest.Raw,
    Omit<Square.CreateCheckoutRequest, "locationId">
> = core.serialization.object({
    idempotencyKey: core.serialization.property("idempotency_key", core.serialization.string()),
    order: CreateOrderRequest,
    askForShippingAddress: core.serialization.property(
        "ask_for_shipping_address",
        core.serialization.boolean().optional(),
    ),
    merchantSupportEmail: core.serialization.property("merchant_support_email", core.serialization.string().optional()),
    prePopulateBuyerEmail: core.serialization.property(
        "pre_populate_buyer_email",
        core.serialization.string().optional(),
    ),
    prePopulateShippingAddress: core.serialization.property("pre_populate_shipping_address", Address.optional()),
    redirectUrl: core.serialization.property("redirect_url", core.serialization.string().optional()),
    additionalRecipients: core.serialization.property(
        "additional_recipients",
        core.serialization.list(ChargeRequestAdditionalRecipient).optional(),
    ),
    note: core.serialization.string().optional(),
});

export declare namespace CreateCheckoutRequest {
    export interface Raw {
        idempotency_key: string;
        order: CreateOrderRequest.Raw;
        ask_for_shipping_address?: boolean | null;
        merchant_support_email?: string | null;
        pre_populate_buyer_email?: string | null;
        pre_populate_shipping_address?: Address.Raw | null;
        redirect_url?: string | null;
        additional_recipients?: ChargeRequestAdditionalRecipient.Raw[] | null;
        note?: string | null;
    }
}
