/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface BreakTypesDeleteRequest {
    /**
     * The UUID for the `BreakType` being deleted.
     */
    id: string;
}
