// This file was auto-generated by Fern from our API Definition.

import { SquareClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("ActivitiesClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            gift_card_activities: [
                {
                    id: "gcact_897698f894b44b3db46c6147e26a0e19",
                    type: "REDEEM",
                    location_id: "81FN9BNFZTKS4",
                    created_at: "2021-06-02T22:26:38.000Z",
                    gift_card_id: "gftc:6d55a72470d940c6ba09c0ab8ad08d20",
                    gift_card_gan: "7783320002929081",
                    gift_card_balance_money: { amount: BigInt(700), currency: "USD" },
                    redeem_activity_details: { amount_money: { amount: BigInt(300), currency: "USD" } },
                    clear_balance_activity_details: { reason: "SUSPICIOUS_ACTIVITY" },
                    deactivate_activity_details: { reason: "SUSPICIOUS_ACTIVITY" },
                    adjust_increment_activity_details: { amount_money: {}, reason: "COMPLIMENTARY" },
                    adjust_decrement_activity_details: { amount_money: {}, reason: "SUSPICIOUS_ACTIVITY" },
                    unlinked_activity_refund_activity_details: { amount_money: {} },
                    import_activity_details: { amount_money: {} },
                    block_activity_details: { reason: "CHARGEBACK_BLOCK" },
                    unblock_activity_details: { reason: "CHARGEBACK_UNBLOCK" },
                    import_reversal_activity_details: { amount_money: {} },
                    transfer_balance_to_activity_details: {
                        transfer_from_gift_card_id: "transfer_from_gift_card_id",
                        amount_money: {},
                    },
                    transfer_balance_from_activity_details: {
                        transfer_to_gift_card_id: "transfer_to_gift_card_id",
                        amount_money: {},
                    },
                },
                {
                    id: "gcact_b968ebfc7d46437b945be7b9e09123b4",
                    type: "ACTIVATE",
                    location_id: "81FN9BNFZTKS4",
                    created_at: "2021-05-20T22:26:54.000Z",
                    gift_card_id: "gftc:6d55a72470d940c6ba09c0ab8ad08d20",
                    gift_card_gan: "7783320002929081",
                    gift_card_balance_money: { amount: BigInt(1000), currency: "USD" },
                    activate_activity_details: {
                        amount_money: { amount: BigInt(1000), currency: "USD" },
                        order_id: "jJNGHm4gLI6XkFbwtiSLqK72KkAZY",
                        line_item_uid: "eIWl7X0nMuO9Ewbh0ChIx",
                    },
                    redeem_activity_details: { amount_money: {} },
                    clear_balance_activity_details: { reason: "SUSPICIOUS_ACTIVITY" },
                    deactivate_activity_details: { reason: "SUSPICIOUS_ACTIVITY" },
                    adjust_increment_activity_details: { amount_money: {}, reason: "COMPLIMENTARY" },
                    adjust_decrement_activity_details: { amount_money: {}, reason: "SUSPICIOUS_ACTIVITY" },
                    unlinked_activity_refund_activity_details: { amount_money: {} },
                    import_activity_details: { amount_money: {} },
                    block_activity_details: { reason: "CHARGEBACK_BLOCK" },
                    unblock_activity_details: { reason: "CHARGEBACK_UNBLOCK" },
                    import_reversal_activity_details: { amount_money: {} },
                    transfer_balance_to_activity_details: {
                        transfer_from_gift_card_id: "transfer_from_gift_card_id",
                        amount_money: {},
                    },
                    transfer_balance_from_activity_details: {
                        transfer_to_gift_card_id: "transfer_to_gift_card_id",
                        amount_money: {},
                    },
                },
            ],
            cursor: "cursor",
        };
        server
            .mockEndpoint({ once: false })
            .get("/v2/gift-cards/activities")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const page = await client.giftCards.activities.list({
            giftCardId: "gift_card_id",
            type: "type",
            locationId: "location_id",
            beginTime: "begin_time",
            endTime: "end_time",
            limit: 1,
            cursor: "cursor",
            sortOrder: "sort_order",
        });
        expect(page.data).toEqual([]);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ maxRetries: 0, token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            idempotency_key: "U16kfr-kA70er-q4Rsym-7U7NnY",
            gift_card_activity: {
                type: "ACTIVATE",
                location_id: "81FN9BNFZTKS4",
                gift_card_id: "gftc:6d55a72470d940c6ba09c0ab8ad08d20",
                activate_activity_details: {
                    order_id: "jJNGHm4gLI6XkFbwtiSLqK72KkAZY",
                    line_item_uid: "eIWl7X0nMuO9Ewbh0ChIx",
                },
            },
        };
        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            gift_card_activity: {
                id: "gcact_c8f8cbf1f24b448d8ecf39ed03f97864",
                type: "ACTIVATE",
                location_id: "81FN9BNFZTKS4",
                created_at: "2021-05-20T22:26:54.000Z",
                gift_card_id: "gftc:6d55a72470d940c6ba09c0ab8ad08d20",
                gift_card_gan: "7783320002929081",
                gift_card_balance_money: { amount: BigInt(1000), currency: "USD" },
                load_activity_details: {
                    order_id: "order_id",
                    line_item_uid: "line_item_uid",
                    reference_id: "reference_id",
                    buyer_payment_instrument_ids: ["buyer_payment_instrument_ids"],
                },
                activate_activity_details: {
                    amount_money: { amount: BigInt(1000), currency: "USD" },
                    order_id: "jJNGHm4gLI6XkFbwtiSLqK72KkAZY",
                    line_item_uid: "eIWl7X0nMuO9Ewbh0ChIx",
                    reference_id: "reference_id",
                    buyer_payment_instrument_ids: ["buyer_payment_instrument_ids"],
                },
                redeem_activity_details: {
                    amount_money: {},
                    payment_id: "payment_id",
                    reference_id: "reference_id",
                    status: "PENDING",
                },
                clear_balance_activity_details: { reason: "SUSPICIOUS_ACTIVITY" },
                deactivate_activity_details: { reason: "SUSPICIOUS_ACTIVITY" },
                adjust_increment_activity_details: { amount_money: {}, reason: "COMPLIMENTARY" },
                adjust_decrement_activity_details: { amount_money: {}, reason: "SUSPICIOUS_ACTIVITY" },
                refund_activity_details: {
                    redeem_activity_id: "redeem_activity_id",
                    reference_id: "reference_id",
                    payment_id: "payment_id",
                },
                unlinked_activity_refund_activity_details: {
                    amount_money: {},
                    reference_id: "reference_id",
                    payment_id: "payment_id",
                },
                import_activity_details: { amount_money: {} },
                block_activity_details: { reason: "CHARGEBACK_BLOCK" },
                unblock_activity_details: { reason: "CHARGEBACK_UNBLOCK" },
                import_reversal_activity_details: { amount_money: {} },
                transfer_balance_to_activity_details: {
                    transfer_from_gift_card_id: "transfer_from_gift_card_id",
                    amount_money: {},
                },
                transfer_balance_from_activity_details: {
                    transfer_to_gift_card_id: "transfer_to_gift_card_id",
                    amount_money: {},
                },
            },
        };
        server
            .mockEndpoint()
            .post("/v2/gift-cards/activities")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.giftCards.activities.create({
            idempotencyKey: "U16kfr-kA70er-q4Rsym-7U7NnY",
            giftCardActivity: {
                type: "ACTIVATE",
                locationId: "81FN9BNFZTKS4",
                giftCardId: "gftc:6d55a72470d940c6ba09c0ab8ad08d20",
                activateActivityDetails: {
                    orderId: "jJNGHm4gLI6XkFbwtiSLqK72KkAZY",
                    lineItemUid: "eIWl7X0nMuO9Ewbh0ChIx",
                },
            },
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            giftCardActivity: {
                id: "gcact_c8f8cbf1f24b448d8ecf39ed03f97864",
                type: "ACTIVATE",
                locationId: "81FN9BNFZTKS4",
                createdAt: "2021-05-20T22:26:54.000Z",
                giftCardId: "gftc:6d55a72470d940c6ba09c0ab8ad08d20",
                giftCardGan: "7783320002929081",
                giftCardBalanceMoney: {
                    amount: BigInt("1000"),
                    currency: "USD",
                },
                loadActivityDetails: {
                    orderId: "order_id",
                    lineItemUid: "line_item_uid",
                    referenceId: "reference_id",
                    buyerPaymentInstrumentIds: ["buyer_payment_instrument_ids"],
                },
                activateActivityDetails: {
                    amountMoney: {
                        amount: BigInt("1000"),
                        currency: "USD",
                    },
                    orderId: "jJNGHm4gLI6XkFbwtiSLqK72KkAZY",
                    lineItemUid: "eIWl7X0nMuO9Ewbh0ChIx",
                    referenceId: "reference_id",
                    buyerPaymentInstrumentIds: ["buyer_payment_instrument_ids"],
                },
                redeemActivityDetails: {
                    amountMoney: {},
                    paymentId: "payment_id",
                    referenceId: "reference_id",
                    status: "PENDING",
                },
                clearBalanceActivityDetails: {
                    reason: "SUSPICIOUS_ACTIVITY",
                },
                deactivateActivityDetails: {
                    reason: "SUSPICIOUS_ACTIVITY",
                },
                adjustIncrementActivityDetails: {
                    amountMoney: {},
                    reason: "COMPLIMENTARY",
                },
                adjustDecrementActivityDetails: {
                    amountMoney: {},
                    reason: "SUSPICIOUS_ACTIVITY",
                },
                refundActivityDetails: {
                    redeemActivityId: "redeem_activity_id",
                    referenceId: "reference_id",
                    paymentId: "payment_id",
                },
                unlinkedActivityRefundActivityDetails: {
                    amountMoney: {},
                    referenceId: "reference_id",
                    paymentId: "payment_id",
                },
                importActivityDetails: {
                    amountMoney: {},
                },
                blockActivityDetails: {
                    reason: "CHARGEBACK_BLOCK",
                },
                unblockActivityDetails: {
                    reason: "CHARGEBACK_UNBLOCK",
                },
                importReversalActivityDetails: {
                    amountMoney: {},
                },
                transferBalanceToActivityDetails: {
                    transferFromGiftCardId: "transfer_from_gift_card_id",
                    amountMoney: {},
                },
                transferBalanceFromActivityDetails: {
                    transferToGiftCardId: "transfer_to_gift_card_id",
                    amountMoney: {},
                },
            },
        });
    });
});
