// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

export interface BankAccountDisabledEventObject {
    /** The disabled bank account. */
    bankAccount?: Square.BankAccount;
}
