/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

/**
 * Published when Square sets the status of a
 * [BankAccount](entity:BankAccount) to `DISABLED`.
 */
export interface BankAccountDisabledEvent {
    /** The ID of the target merchant associated with the event. */
    merchantId?: string | null;
    /** The ID of the target location associated with the event. */
    locationId?: string | null;
    /** The type of event this represents, `"bank_account.disabled"`. */
    type?: string | null;
    /** A unique ID for the event. */
    eventId?: string | null;
    /** Timestamp of when the event was disabled, in RFC 3339 format. */
    createdAt?: string;
    /** Data associated with the event. */
    data?: Square.BankAccountDisabledEventData;
}
