/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

export interface BankAccountVerifiedEventObject {
    /** The verified bank account. */
    bankAccount?: Square.BankAccount;
}
