/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

/**
 * Represents an output from a call to [BulkUpdateVendors](api-endpoint:Vendors-BulkUpdateVendors).
 */
export interface BatchUpdateVendorsResponse {
    /** Errors encountered when the request fails. */
    errors?: Square.Error_[];
    /**
     * A set of [UpdateVendorResponse](entity:UpdateVendorResponse) objects encapsulating successfully created [Vendor](entity:Vendor)
     * objects or error responses for failed attempts. The set is represented by a collection of `Vendor`-ID/`UpdateVendorResponse`-object or
     * `Vendor`-ID/error-object pairs.
     */
    responses?: Record<string, Square.UpdateVendorResponse>;
}
