/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * Defines the fields that are included in the response body of
 * a request to the [CaptureTransaction](api-endpoint:Transactions-CaptureTransaction) endpoint.
 */
export interface CaptureTransactionResponse {
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
}
