/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

export interface CatalogObjectImage extends Square.CatalogObjectBase {
    /** Structured data for a `CatalogImage`, set for CatalogObjects of type `IMAGE`. */
    imageData?: Square.CatalogImage;
}
