// This file was auto-generated by Fern from our API Definition.

/** Item level overrides for bool attributes */
export const CatalogModifierToggleOverrideType = {
    No: "NO",
    Yes: "YES",
    NotSet: "NOT_SET",
} as const;
export type CatalogModifierToggleOverrideType =
    (typeof CatalogModifierToggleOverrideType)[keyof typeof CatalogModifierToggleOverrideType];
