// This file was auto-generated by Fern from our API Definition.

export interface CatalogVersionUpdatedEventCatalogVersion {
    /** Last modification timestamp in RFC 3339 format. */
    updatedAt?: string;
}
