/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Supported timings when a pending change, as an action, takes place to a subscription.
 */
export type ChangeTiming = "IMMEDIATE" | "END_OF_BILLING_CYCLE";
export const ChangeTiming = {
    Immediate: "IMMEDIATE",
    EndOfBillingCycle: "END_OF_BILLING_CYCLE",
} as const;
