// This file was auto-generated by Fern from our API Definition.

export const CheckoutLocationSettingsBrandingButtonShape = {
    Squared: "SQUARED",
    Rounded: "ROUNDED",
    Pill: "PILL",
} as const;
export type CheckoutLocationSettingsBrandingButtonShape =
    (typeof CheckoutLocationSettingsBrandingButtonShape)[keyof typeof CheckoutLocationSettingsBrandingButtonShape];
