// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * Defines the fields that are included in the response body of
 * a request to the [CloneOrder](api-endpoint:Orders-CloneOrder) endpoint.
 */
export interface CloneOrderResponse {
    /** The cloned order. */
    order?: Square.Order;
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
}
