/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * The response to the request to create a `BreakType`. The response contains
 * the created `BreakType` object and might contain a set of `Error` objects if
 * the request resulted in errors.
 */
export interface CreateBreakTypeResponse {
    /** The `BreakType` that was created by the request. */
    break_type?: Square.BreakType;
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
}
