/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

/**
 * Represents a [DeleteBookingCustomAttributeDefinition](api-endpoint:BookingCustomAttributes-DeleteBookingCustomAttributeDefinition) response
 * containing error messages when errors occurred during the request. The successful response does not contain any payload.
 */
export interface DeleteBookingCustomAttributeDefinitionResponse {
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
}
