/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details about the device that took the payment.
 */
export interface DeviceDetails {
    /** The Square-issued ID of the device. */
    device_id?: string | null;
    /** The Square-issued installation ID for the device. */
    device_installation_id?: string | null;
    /** The name of the device set by the seller. */
    device_name?: string | null;
}
