/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

export interface DisputeCreatedEventObject {
    /** The dispute object. */
    object?: Square.Dispute;
}
