/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * Response object returned by `GetBankAccount`.
 */
export interface GetBankAccountResponse {
    /** Information on errors encountered during the request. */
    errors?: Square.Error_[];
    /** The requested `BankAccount` object. */
    bank_account?: Square.BankAccount;
}
