// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * A response that contains a `GiftCard` object. If the request resulted in errors,
 * the response contains a set of `Error` objects.
 */
export interface GetGiftCardFromNonceResponse {
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
    /** The retrieved gift card. */
    giftCard?: Square.GiftCard;
}
