/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

export interface GetInventoryAdjustmentResponse {
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
    /** The requested [InventoryAdjustment](entity:InventoryAdjustment). */
    adjustment?: Square.InventoryAdjustment;
}
