/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

/**
 * Represents a [RetrieveLoyaltyPromotionPromotions](api-endpoint:Loyalty-RetrieveLoyaltyPromotion) response.
 */
export interface GetLoyaltyPromotionResponse {
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
    /** The retrieved loyalty promotion. */
    loyaltyPromotion?: Square.LoyaltyPromotion;
}
