// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

export interface GetTeamMemberBookingProfileResponse {
    /** The returned team member booking profile. */
    teamMemberBookingProfile?: Square.TeamMemberBookingProfile;
    /** Errors that occurred during the request. */
    errors?: Square.Error_[];
}
