/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates the reason for deducting money from a [gift card](entity:GiftCard).
 */
export type GiftCardActivityAdjustDecrementReason =
    | "SUSPICIOUS_ACTIVITY"
    | "BALANCE_ACCIDENTALLY_INCREASED"
    | "SUPPORT_ISSUE"
    | "PURCHASE_WAS_REFUNDED";
export const GiftCardActivityAdjustDecrementReason = {
    SuspiciousActivity: "SUSPICIOUS_ACTIVITY",
    BalanceAccidentallyIncreased: "BALANCE_ACCIDENTALLY_INCREASED",
    SupportIssue: "SUPPORT_ISSUE",
    PurchaseWasRefunded: "PURCHASE_WAS_REFUNDED",
} as const;
