// This file was auto-generated by Fern from our API Definition.

/** Indicates the gift card type. */
export const GiftCardType = {
    Physical: "PHYSICAL",
    Digital: "DIGITAL",
} as const;
export type GiftCardType = (typeof GiftCardType)[keyof typeof GiftCardType];
