/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * The data associated with a `gift_card.activity.updated` event.
 */
export interface GiftCardActivityUpdatedEventData {
    /** The type of object affected by the event. For this event, the value is `gift_card_activity`. */
    type?: string | null;
    /** The ID of the updated gift card activity. */
    id?: string;
    /** An object that contains the updated gift card activity. */
    object?: Square.GiftCardActivityUpdatedEventObject;
}
