/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * Represents an action performed on a [gift card](entity:GiftCard) that affects its state or balance.
 * A gift card activity contains information about a specific activity type. For example, a `REDEEM` activity
 * includes a `redeem_activity_details` field that contains information about the redemption.
 */
export interface GiftCardActivity {
    /** The Square-assigned ID of the gift card activity. */
    id?: string;
    /**
     * The type of gift card activity.
     * See [Type](#type-type) for possible values
     */
    type: Square.GiftCardActivityType;
    /** The ID of the [business location](entity:Location) where the activity occurred. */
    location_id: string;
    /** The timestamp when the gift card activity was created, in RFC 3339 format. */
    created_at?: string;
    /**
     * The gift card ID. When creating a gift card activity, `gift_card_id` is not required if
     * `gift_card_gan` is specified.
     */
    gift_card_id?: string | null;
    /**
     * The gift card account number (GAN). When creating a gift card activity, `gift_card_gan`
     * is not required if `gift_card_id` is specified.
     */
    gift_card_gan?: string | null;
    /** The final balance on the gift card after the action is completed. */
    gift_card_balance_money?: Square.Money;
    /** Additional details about a `LOAD` activity, which is used to reload money onto a gift card. */
    load_activity_details?: Square.GiftCardActivityLoad;
    /**
     * Additional details about an `ACTIVATE` activity, which is used to activate a gift card with
     * an initial balance.
     */
    activate_activity_details?: Square.GiftCardActivityActivate;
    /**
     * Additional details about a `REDEEM` activity, which is used to redeem a gift card for a purchase.
     *
     * For applications that process payments using the Square Payments API, Square creates a `REDEEM` activity that
     * updates the gift card balance after the corresponding [CreatePayment](api-endpoint:Payments-CreatePayment)
     * request is completed. Applications that use a custom payment processing system must call
     * [CreateGiftCardActivity](api-endpoint:GiftCardActivities-CreateGiftCardActivity) to create the `REDEEM` activity.
     */
    redeem_activity_details?: Square.GiftCardActivityRedeem;
    /** Additional details about a `CLEAR_BALANCE` activity, which is used to set the balance of a gift card to zero. */
    clear_balance_activity_details?: Square.GiftCardActivityClearBalance;
    /** Additional details about a `DEACTIVATE` activity, which is used to deactivate a gift card. */
    deactivate_activity_details?: Square.GiftCardActivityDeactivate;
    /**
     * Additional details about an `ADJUST_INCREMENT` activity, which is used to add money to a gift card
     * outside of a typical `ACTIVATE`, `LOAD`, or `REFUND` activity flow.
     */
    adjust_increment_activity_details?: Square.GiftCardActivityAdjustIncrement;
    /**
     * Additional details about an `ADJUST_DECREMENT` activity, which is used to deduct money from a gift
     * card outside of a typical `REDEEM` activity flow.
     */
    adjust_decrement_activity_details?: Square.GiftCardActivityAdjustDecrement;
    /**
     * Additional details about a `REFUND` activity, which is used to add money to a gift card when
     * refunding a payment.
     *
     * For applications that refund payments to a gift card using the Square Refunds API, Square automatically
     * creates a `REFUND` activity that updates the gift card balance after a [RefundPayment](api-endpoint:Refunds-RefundPayment)
     * request is completed. Applications that use a custom processing system must call
     * [CreateGiftCardActivity](api-endpoint:GiftCardActivities-CreateGiftCardActivity) to create the `REFUND` activity.
     */
    refund_activity_details?: Square.GiftCardActivityRefund;
    /**
     * Additional details about an `UNLINKED_ACTIVITY_REFUND` activity. This activity is used to add money
     * to a gift card when refunding a payment that was processed using a custom payment processing system
     * and not linked to the gift card.
     */
    unlinked_activity_refund_activity_details?: Square.GiftCardActivityUnlinkedActivityRefund;
    /**
     * Additional details about an `IMPORT` activity, which Square uses to import a third-party
     * gift card with a balance.
     */
    import_activity_details?: Square.GiftCardActivityImport;
    /** Additional details about a `BLOCK` activity, which Square uses to temporarily block a gift card. */
    block_activity_details?: Square.GiftCardActivityBlock;
    /** Additional details about an `UNBLOCK` activity, which Square uses to unblock a gift card. */
    unblock_activity_details?: Square.GiftCardActivityUnblock;
    /**
     * Additional details about an `IMPORT_REVERSAL` activity, which Square uses to reverse the
     * import of a third-party gift card.
     */
    import_reversal_activity_details?: Square.GiftCardActivityImportReversal;
    /**
     * Additional details about a `TRANSFER_BALANCE_TO` activity, which Square uses to add money to
     * a gift card as the result of a transfer from another gift card.
     */
    transfer_balance_to_activity_details?: Square.GiftCardActivityTransferBalanceTo;
    /**
     * Additional details about a `TRANSFER_BALANCE_FROM` activity, which Square uses to deduct money from
     * a gift as the result of a transfer to another gift card.
     */
    transfer_balance_from_activity_details?: Square.GiftCardActivityTransferBalanceFrom;
}
