/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * Published when a [gift card activity](entity:GiftCardActivity) is updated.
 * Subscribe to this event to be notified about the following changes:
 * - An update to the `REDEEM` activity for a gift card redemption made from a Square product (such as Square Point of Sale).
 * These redemptions are initially assigned a `PENDING` state, but then change to a `COMPLETED` or `CANCELED` state.
 * - An update to the `IMPORT` activity for an imported gift card when the balance is later adjusted by Square.
 */
export interface GiftCardActivityUpdatedEvent {
    /** The ID of the Square seller associated with the event. */
    merchant_id?: string | null;
    /** The type of event. For this event, the value is `gift_card.activity.updated`. */
    type?: string | null;
    /**
     * The unique ID of the event, which is used for
     * [idempotency support](https://developer.squareup.com/docs/webhooks/step4manage#webhooks-best-practices).
     */
    event_id?: string | null;
    /** The timestamp of when the event was created, in RFC 3339 format. */
    created_at?: string;
    /** The data associated with the event. */
    data?: Square.GiftCardActivityUpdatedEventData;
}
