// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * An additional seller-defined and customer-facing field to include on the invoice. For more information,
 * see [Custom fields](https://developer.squareup.com/docs/invoices-api/overview#custom-fields).
 *
 * Adding custom fields to an invoice requires an
 * [Invoices Plus subscription](https://developer.squareup.com/docs/invoices-api/overview#invoices-plus-subscription).
 */
export interface InvoiceCustomField {
    /** The label or title of the custom field. This field is required for a custom field. */
    label?: string | null;
    /** The text of the custom field. If omitted, only the label is rendered. */
    value?: string | null;
    /**
     * The location of the custom field on the invoice. This field is required for a custom field.
     * See [InvoiceCustomFieldPlacement](#type-invoicecustomfieldplacement) for possible values
     */
    placement?: Square.InvoiceCustomFieldPlacement;
}
