// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

export interface JobUpdatedEventData {
    /** Name of the affected object’s type, `"job"`. */
    type?: string | null;
    /** ID of the updated job. */
    id?: string;
    /** An object containing the updated job. */
    object?: Square.JobUpdatedEventObject;
}
