// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

export interface ListCashDrawerShiftsResponse {
    /**
     * Opaque cursor for fetching the next page of results. Cursor is not
     * present in the last page of results.
     */
    cursor?: string;
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
    /**
     * A collection of CashDrawerShiftSummary objects for shifts that match
     * the query.
     */
    cashDrawerShifts?: Square.CashDrawerShiftSummary[];
}
