// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * Represents a `ListSites` response. The response can include either `sites` or `errors`.
 */
export interface ListSitesResponse {
    /** Any errors that occurred during the request. */
    errors?: Square.Error_[];
    /** The sites that belong to the seller. */
    sites?: Square.Site[];
}
