/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * Response object returned by ListBankAccounts.
 */
export interface ListBankAccountsResponse {
    /** Information on errors encountered during the request. */
    errors?: Square.Error_[];
    /** List of BankAccounts associated with this account. */
    bank_accounts?: Square.BankAccount[];
    /**
     * When a response is truncated, it includes a cursor that you can
     * use in a subsequent request to fetch next set of bank accounts.
     * If empty, this is the final response.
     *
     * For more information, see [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination).
     */
    cursor?: string;
}
