// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

export interface LoadResponse {
    pivotQuery?: Record<string, unknown>;
    slowQuery?: boolean;
    queryType?: string;
    results: Square.LoadResult[];
}
