/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

/**
 * Published when a location [custom attribute definition](entity:CustomAttributeDefinition)
 * that is visible to the subscribing application is updated. A custom attribute definition can only be updated
 * by the application that created it. A notification is sent when your application updates a custom attribute
 * definition or when another application updates a custom attribute definition whose `visibility` is
 * `VISIBILITY_READ_ONLY` or `VISIBILITY_READ_WRITE_VALUES`.
 */
export interface LocationCustomAttributeDefinitionVisibleUpdatedEvent {
    /** The ID of the seller associated with the event that triggered the event notification. */
    merchantId?: string | null;
    /** The type of this event. The value is `"location.custom_attribute_definition.visible.updated"`. */
    type?: string | null;
    /** A unique ID for the event notification. */
    eventId?: string | null;
    /** The timestamp that indicates when the event notification was created, in RFC 3339 format. */
    createdAt?: string;
    /** The data associated with the event that triggered the event notification. */
    data?: Square.CustomAttributeDefinitionEventData;
}
