/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * Represents one of a business' [locations](https://developer.squareup.com/docs/locations-api).
 */
export interface Location {
    /** A short generated string of letters and numbers that uniquely identifies this location instance. */
    id?: string;
    /**
     * The name of the location.
     * This information appears in the Seller Dashboard as the nickname.
     * A location name must be unique within a seller account.
     */
    name?: string | null;
    /** The physical address of the location. */
    address?: Square.Address;
    /**
     * The [IANA time zone](https://www.iana.org/time-zones) identifier for
     * the time zone of the location. For example, `America/Los_Angeles`.
     */
    timezone?: string | null;
    /**
     * The Square features that are enabled for the location.
     * See [LocationCapability](entity:LocationCapability) for possible values.
     * See [LocationCapability](#type-locationcapability) for possible values
     */
    capabilities?: Square.LocationCapability[];
    /**
     * The status of the location.
     * See [LocationStatus](#type-locationstatus) for possible values
     */
    status?: Square.LocationStatus;
    /**
     * The time when the location was created, in RFC 3339 format.
     * For more information, see [Working with Dates](https://developer.squareup.com/docs/build-basics/working-with-dates).
     */
    created_at?: string;
    /** The ID of the merchant that owns the location. */
    merchant_id?: string;
    /**
     * The country of the location, in the two-letter format of ISO 3166. For example, `US` or `JP`.
     *
     * See [Country](entity:Country) for possible values.
     * See [Country](#type-country) for possible values
     */
    country?: Square.Country;
    /**
     * The language associated with the location, in
     * [BCP 47 format](https://tools.ietf.org/html/bcp47#appendix-A).
     * For more information, see [Language Preferences](https://developer.squareup.com/docs/build-basics/general-considerations/language-preferences).
     */
    language_code?: string | null;
    /**
     * The currency used for all transactions at this location,
     * in ISO 4217 format. For example, the currency code for US dollars is `USD`.
     * See [Currency](entity:Currency) for possible values.
     * See [Currency](#type-currency) for possible values
     */
    currency?: Square.Currency;
    /** The phone number of the location. For example, `+1 855-700-6000`. */
    phone_number?: string | null;
    /** The name of the location's overall business. This name is present on receipts and other customer-facing branding, and can be changed no more than three times in a twelve-month period. */
    business_name?: string | null;
    /**
     * The type of the location.
     * See [LocationType](#type-locationtype) for possible values
     */
    type?: Square.LocationType;
    /** The website URL of the location.  For example, `https://squareup.com`. */
    website_url?: string | null;
    /** The hours of operation for the location. */
    business_hours?: Square.BusinessHours;
    /** The email address of the location. This can be unique to the location and is not always the email address for the business owner or administrator. */
    business_email?: string | null;
    /** The description of the location. For example, `Main Street location`. */
    description?: string | null;
    /** The Twitter username of the location without the '@' symbol. For example, `Square`. */
    twitter_username?: string | null;
    /** The Instagram username of the location without the '@' symbol. For example, `square`. */
    instagram_username?: string | null;
    /** The Facebook profile URL of the location. The URL should begin with 'facebook.com/'. For example, `https://www.facebook.com/square`. */
    facebook_url?: string | null;
    /** The physical coordinates (latitude and longitude) of the location. */
    coordinates?: Square.Coordinates;
    /**
     * The URL of the logo image for the location. When configured in the Seller
     * Dashboard (Receipts section), the logo appears on transactions (such as receipts and invoices) that Square generates on behalf of the seller.
     * This image should have a roughly square (1:1) aspect ratio and should be at least 200x200 pixels.
     */
    logo_url?: string;
    /** The URL of the Point of Sale background image for the location. */
    pos_background_url?: string;
    /**
     * A four-digit number that describes the kind of goods or services sold at the location.
     * The [merchant category code (MCC)](https://developer.squareup.com/docs/locations-api#initialize-a-merchant-category-code) of the location as standardized by ISO 18245.
     * For example, `5045`, for a location that sells computer goods and software.
     */
    mcc?: string | null;
    /**
     * The URL of a full-format logo image for the location. When configured in the Seller
     * Dashboard (Receipts section), the logo appears on transactions (such as receipts and invoices) that Square generates on behalf of the seller.
     * This image can be wider than it is tall and should be at least 1280x648 pixels.
     */
    full_format_logo_url?: string;
    /** The tax IDs for this location. */
    tax_ids?: Square.TaxIds;
}
