// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * An object that contains the loyalty program associated with a `loyalty.program.updated` event.
 */
export interface LoyaltyProgramUpdatedEventObject {
    /** The loyalty program that was updated. */
    loyaltyProgram?: Square.LoyaltyProgram;
}
