/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Unit of area used to measure a quantity.
 */
export type MeasurementUnitArea =
    | "IMPERIAL_ACRE"
    | "IMPERIAL_SQUARE_INCH"
    | "IMPERIAL_SQUARE_FOOT"
    | "IMPERIAL_SQUARE_YARD"
    | "IMPERIAL_SQUARE_MILE"
    | "METRIC_SQUARE_CENTIMETER"
    | "METRIC_SQUARE_METER"
    | "METRIC_SQUARE_KILOMETER";
export const MeasurementUnitArea = {
    ImperialAcre: "IMPERIAL_ACRE",
    ImperialSquareInch: "IMPERIAL_SQUARE_INCH",
    ImperialSquareFoot: "IMPERIAL_SQUARE_FOOT",
    ImperialSquareYard: "IMPERIAL_SQUARE_YARD",
    ImperialSquareMile: "IMPERIAL_SQUARE_MILE",
    MetricSquareCentimeter: "METRIC_SQUARE_CENTIMETER",
    MetricSquareMeter: "METRIC_SQUARE_METER",
    MetricSquareKilometer: "METRIC_SQUARE_KILOMETER",
} as const;
