/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

export interface MerchantSettingsUpdatedEventObject {
    /** The updated merchant settings. */
    merchant_settings?: Square.CheckoutMerchantSettings;
}
