/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * Location-specific overrides for specified properties of a `CatalogModifier` object.
 */
export interface ModifierLocationOverrides {
    /** The ID of the `Location` object representing the location. This can include a deactivated location. */
    location_id?: string | null;
    /**
     * The overridden price at the specified location. If this is unspecified, the modifier price is not overridden.
     * The modifier becomes free of charge at the specified location, when this `price_money` field is set to 0.
     */
    price_money?: Square.Money;
    /**
     * Indicates whether the modifier is sold out at the specified location or not. As an example, for cheese (modifier) burger (item), when the modifier is sold out, it is the cheese, but not the burger, that is sold out.
     * The seller can manually set this sold out status. Attempts by an application to set this attribute are ignored.
     */
    sold_out?: boolean;
}
