// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * The set of line items, service charges, taxes, discounts, tips, and other items being returned in an order.
 */
export interface OrderReturn {
    /** A unique ID that identifies the return only within this order. */
    uid?: string | null;
    /**
     * An order that contains the original sale of these return line items. This is unset
     * for unlinked returns.
     */
    sourceOrderId?: string | null;
    /** A collection of line items that are being returned. */
    returnLineItems?: Square.OrderReturnLineItem[] | null;
    /** A collection of service charges that are being returned. */
    returnServiceCharges?: Square.OrderReturnServiceCharge[] | null;
    /**
     * A collection of references to taxes being returned for an order, including the total
     * applied tax amount to be returned. The taxes must reference a top-level tax ID from the source
     * order.
     */
    returnTaxes?: Square.OrderReturnTax[];
    /**
     * A collection of references to discounts being returned for an order, including the total
     * applied discount amount to be returned. The discounts must reference a top-level discount ID
     * from the source order.
     */
    returnDiscounts?: Square.OrderReturnDiscount[];
    /** A collection of references to tips being returned for an order. */
    returnTips?: Square.OrderReturnTip[] | null;
    /**
     * A positive or negative rounding adjustment to the total value being returned. Adjustments are commonly
     * used to apply cash rounding when the minimum unit of the account is smaller than the lowest
     * physical denomination of the currency.
     */
    roundingAdjustment?: Square.OrderRoundingAdjustment;
    /** An aggregate monetary value being returned by this return entry. */
    returnAmounts?: Square.OrderMoneyAmounts;
}
