// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

export interface OrderFulfillmentUpdatedObject {
    /** Information about the updated order fulfillment. */
    orderFulfillmentUpdated?: Square.OrderFulfillmentUpdated;
}
