// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * An accounting of the amount owed the seller and record of the actual transfer to their
 * external bank account or to the Square balance.
 */
export interface Payout {
    /** A unique ID for the payout. */
    id: string;
    /**
     * Indicates the payout status.
     * See [PayoutStatus](#type-payoutstatus) for possible values
     */
    status?: Square.PayoutStatus;
    /** The ID of the location associated with the payout. */
    locationId: string;
    /** The timestamp of when the payout was created and submitted for deposit to the seller's banking destination, in RFC 3339 format. */
    createdAt?: string;
    /** The timestamp of when the payout was last updated, in RFC 3339 format. */
    updatedAt?: string;
    /** The amount of money involved in the payout. A positive amount indicates a deposit, and a negative amount indicates a withdrawal. This amount is never zero. */
    amountMoney?: Square.Money;
    /**
     * Information about the banking destination (such as a bank account, Square checking account, or debit card)
     * against which the payout was made.
     */
    destination?: Square.Destination;
    /**
     * The version number, which is incremented each time an update is made to this payout record.
     * The version number helps developers receive event notifications or feeds out of order.
     */
    version?: number;
    /**
     * Indicates the payout type.
     * See [PayoutType](#type-payouttype) for possible values
     */
    type?: Square.PayoutType;
    /** A list of transfer fees and any taxes on the fees assessed by Square for this payout. */
    payoutFee?: Square.PayoutFee[] | null;
    /** The calendar date, in ISO 8601 format (YYYY-MM-DD), when the payout is due to arrive in the seller’s banking destination. */
    arrivalDate?: string | null;
    /** A unique ID for each `Payout` object that might also appear on the seller’s bank statement. You can use this ID to automate the process of reconciling each payout with the corresponding line item on the bank statement. */
    endToEndId?: string | null;
}
