// This file was auto-generated by Fern from our API Definition.

/** Indicates the Square product used to generate a change. */
export const Product = {
    SquarePos: "SQUARE_POS",
    ExternalApi: "EXTERNAL_API",
    Billing: "BILLING",
    Appointments: "APPOINTMENTS",
    Invoices: "INVOICES",
    OnlineStore: "ONLINE_STORE",
    Payroll: "PAYROLL",
    Dashboard: "DASHBOARD",
    ItemLibraryImport: "ITEM_LIBRARY_IMPORT",
    Other: "OTHER",
} as const;
export type Product = (typeof Product)[keyof typeof Product];
