// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * Defines sort criteria for a [SearchScheduledShifts](api-endpoint:Labor-SearchScheduledShifts)
 * request.
 */
export interface ScheduledShiftSort {
    /**
     * The field to sort on. The default value is `START_AT`.
     * See [ScheduledShiftSortField](#type-scheduledshiftsortfield) for possible values
     */
    field?: Square.ScheduledShiftSortField;
    /**
     * The order in which results are returned. The default value is `ASC`.
     * See [SortOrder](#type-sortorder) for possible values
     */
    order?: Square.SortOrder;
}
