// This file was auto-generated by Fern from our API Definition.

/**
 * Represents shift details for draft and published versions of a [scheduled shift](entity:ScheduledShift),
 * such as job ID, team member assignment, and start and end times.
 */
export interface ScheduledShiftDetails {
    /** The ID of the [team member](entity:TeamMember) scheduled for the shift. */
    teamMemberId?: string | null;
    /** The ID of the [location](entity:Location) the shift is scheduled for. */
    locationId?: string | null;
    /** The ID of the [job](entity:Job) the shift is scheduled for. */
    jobId?: string | null;
    /**
     * The start time of the shift, in RFC 3339 format in the time zone &plus;
     * offset of the shift location specified in `location_id`. Precision up to the minute
     * is respected; seconds are truncated.
     */
    startAt?: string | null;
    /**
     * The end time for the shift, in RFC 3339 format in the time zone &plus;
     * offset of the shift location specified in `location_id`. Precision up to the minute
     * is respected; seconds are truncated.
     */
    endAt?: string | null;
    /** Optional notes for the shift. */
    notes?: string | null;
    /**
     * Indicates whether the draft shift version is deleted. If set to `true` when the shift
     * is published, the entire scheduled shift (including the published shift) is deleted and
     * cannot be accessed using any endpoint.
     */
    isDeleted?: boolean | null;
    /**
     * The time zone of the shift location, calculated based on the `location_id`. This field
     * is provided for convenience.
     */
    timezone?: string;
}
