/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

export interface SearchTerminalRefundsResponse {
    /** Information about errors encountered during the request. */
    errors?: Square.Error_[];
    /** The requested search result of `TerminalRefund` objects. */
    refunds?: Square.TerminalRefund[];
    /**
     * The pagination cursor to be used in a subsequent request. If empty,
     * this is the final response.
     *
     * See [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination) for more information.
     */
    cursor?: string;
}
