/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

/**
 * The query used to search for buyer-accessible availabilities of bookings.
 */
export interface SearchAvailabilityQuery {
    /** The query filter to search for buyer-accessible availabilities of existing bookings. */
    filter: Square.SearchAvailabilityFilter;
}
