// This file was auto-generated by Fern from our API Definition.

export interface Segment {
    name: string;
    title: string;
    description?: string;
    shortTitle: string;
    meta?: Record<string, unknown>;
}
