/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

/**
 * A `Shift` search query filter parameter that sets a range of days that
 * a `Shift` must start or end in before passing the filter condition.
 *
 * Deprecated at Square API version 2025-05-21. See the [migration notes](https://developer.squareup.com/docs/labor-api/what-it-does#migration-notes).
 */
export interface ShiftWorkday {
    /** Dates for fetching the shifts. */
    dateRange?: Square.DateRange;
    /**
     * The strategy on which the dates are applied.
     * See [ShiftWorkdayMatcher](#type-shiftworkdaymatcher) for possible values
     */
    matchShiftsBy?: Square.ShiftWorkdayMatcher;
    /**
     * Location-specific timezones convert workdays to datetime filters.
     * Every location included in the query must have a timezone or this field
     * must be provided as a fallback. Format: the IANA timezone database
     * identifier for the relevant timezone.
     */
    defaultTimezone?: string | null;
}
