/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Represents a Square Online site, which is an online store for a Square seller.
 */
export interface Site {
    /** The Square-assigned ID of the site. */
    id?: string;
    /** The title of the site. */
    site_title?: string | null;
    /** The domain of the site (without the protocol). For example, `mysite1.square.site`. */
    domain?: string | null;
    /** Indicates whether the site is published. */
    is_published?: boolean | null;
    /** The timestamp of when the site was created, in RFC 3339 format. */
    created_at?: string;
    /** The timestamp of when the site was last updated, in RFC 3339 format. */
    updated_at?: string;
}
