// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

export interface TeamMemberCreatedEventObject {
    /** The created team member. */
    teamMember?: Square.TeamMember;
}
