/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The booking profile of a seller's team member, including the team member's ID, display name, description and whether the team member can be booked as a service provider.
 */
export interface TeamMemberBookingProfile {
    /** The ID of the [TeamMember](entity:TeamMember) object for the team member associated with the booking profile. */
    team_member_id?: string;
    /** The description of the team member. */
    description?: string;
    /** The display name of the team member. */
    display_name?: string;
    /** Indicates whether the team member can be booked through the Bookings API or the seller's online booking channel or site (`true`) or not (`false`). */
    is_bookable?: boolean | null;
    /** The URL of the team member's image for the bookings profile. */
    profile_image_url?: string;
}
