/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index.js";

export interface TeamMemberCreatedEventData {
    /** Name of the affected object’s type, `"team_member"`. */
    type?: string | null;
    /** ID of the created team member. */
    id?: string;
    /** An object containing the created team member. */
    object?: Square.TeamMemberCreatedEventObject;
}
