// This file was auto-generated by Fern from our API Definition.

export const TenderBuyNowPayLaterDetailsStatus = {
    Authorized: "AUTHORIZED",
    Captured: "CAPTURED",
    Voided: "VOIDED",
    Failed: "FAILED",
} as const;
export type TenderBuyNowPayLaterDetailsStatus =
    (typeof TenderBuyNowPayLaterDetailsStatus)[keyof typeof TenderBuyNowPayLaterDetailsStatus];
