/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates the method used to enter the card's details.
 */
export type TenderCardDetailsEntryMethod = "SWIPED" | "KEYED" | "EMV" | "ON_FILE" | "CONTACTLESS";
export const TenderCardDetailsEntryMethod = {
    Swiped: "SWIPED",
    Keyed: "KEYED",
    Emv: "EMV",
    OnFile: "ON_FILE",
    Contactless: "CONTACTLESS",
} as const;
