/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../index";

export interface TransferOrderUpdatedEventObject {
    /** The updated transfer_order. */
    transferOrder?: Square.TransferOrder;
}
