// This file was auto-generated by Fern from our API Definition.

export const V1OrderState = {
    Pending: "PENDING",
    Open: "OPEN",
    Completed: "COMPLETED",
    Canceled: "CANCELED",
    Refunded: "REFUNDED",
    Rejected: "REJECTED",
} as const;
export type V1OrderState = (typeof V1OrderState)[keyof typeof V1OrderState];
