// This file was auto-generated by Fern from our API Definition.

export const V1TenderEntryMethod = {
    Manual: "MANUAL",
    Scanned: "SCANNED",
    SquareCash: "SQUARE_CASH",
    SquareWallet: "SQUARE_WALLET",
    Swiped: "SWIPED",
    WebForm: "WEB_FORM",
    Other: "OTHER",
} as const;
export type V1TenderEntryMethod = (typeof V1TenderEntryMethod)[keyof typeof V1TenderEntryMethod];
