// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../index";

/**
 * Published when a [Vendor](entity:Vendor) is created.
 */
export interface VendorCreatedEvent {
    /** The ID of a seller associated with this event. */
    merchantId?: string | null;
    /** The ID of a location associated with the event, if the event is associated with the location of the seller. */
    locationId?: string | null;
    /** The type of this event. The value is `"vendor.created".` */
    type?: string | null;
    /** A unique ID for this event. */
    eventId?: string | null;
    /** The RFC 3339-formatted time when the underlying event data object is created. */
    createdAt?: string;
    /** The data associated with this event. */
    data?: Square.VendorCreatedEventData;
}
