// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         locationId: "location_id"
 *     }
 */
export interface RetrieveLocationSettingsRequest {
    /** The ID of the location for which to retrieve settings. */
    locationId: string;
}
