/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../index";

/**
 * @example
 *     {
 *         teamMembers: {
 *             "AFMwA08kR-MIF-3Vs0OE": {
 *                 teamMember: {
 *                     referenceId: "reference_id_2",
 *                     isOwner: false,
 *                     status: "ACTIVE",
 *                     givenName: "Jane",
 *                     familyName: "Smith",
 *                     emailAddress: "jane_smith@gmail.com",
 *                     phoneNumber: "+14159223334",
 *                     assignedLocations: {
 *                         assignmentType: "ALL_CURRENT_AND_FUTURE_LOCATIONS"
 *                     }
 *                 }
 *             },
 *             "fpgteZNMaf0qOK-a4t6P": {
 *                 teamMember: {
 *                     referenceId: "reference_id_1",
 *                     isOwner: false,
 *                     status: "ACTIVE",
 *                     givenName: "Joe",
 *                     familyName: "Doe",
 *                     emailAddress: "joe_doe@gmail.com",
 *                     phoneNumber: "+14159283333",
 *                     assignedLocations: {
 *                         assignmentType: "EXPLICIT_LOCATIONS",
 *                         locationIds: ["YSGH2WBKG94QZ", "GA2Y9HSJ8KRYT"]
 *                     }
 *                 }
 *             }
 *         }
 *     }
 */
export interface BatchUpdateTeamMembersRequest {
    /**
     * The data used to update the `TeamMember` objects. Each key is the `team_member_id` that maps to the `UpdateTeamMemberRequest`.
     * The maximum number of update objects is 25.
     *
     * For each team member, include the fields to add, change, or clear. Fields can be cleared using a null value.
     * To update `wage_setting.job_assignments`, you must provide the complete list of job assignments. If needed,
     * call [ListJobs](api-endpoint:Team-ListJobs) to get the required `job_id` values.
     */
    teamMembers: Record<string, Square.UpdateTeamMemberRequest>;
}
