/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         bank_account_id: "bank_account_id"
 *     }
 */
export interface GetBankAccountsRequest {
    /**
     * Square-issued ID of the desired `BankAccount`.
     */
    bank_account_id: string;
}
