// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";
import { Order } from "../../../../types/Order";
import { OrderReward } from "../../../../types/OrderReward";

export const CalculateOrderRequest: core.serialization.Schema<
    serializers.CalculateOrderRequest.Raw,
    Square.CalculateOrderRequest
> = core.serialization.object({
    order: Order,
    proposedRewards: core.serialization.property(
        "proposed_rewards",
        core.serialization.list(OrderReward).optionalNullable(),
    ),
});

export declare namespace CalculateOrderRequest {
    export interface Raw {
        order: Order.Raw;
        proposed_rewards?: (OrderReward.Raw[] | null | undefined) | null;
    }
}
