/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         booking_ids: ["booking_ids"]
 *     }
 */
export interface BulkRetrieveBookingsRequest {
    /** A non-empty list of [Booking](entity:Booking) IDs specifying bookings to retrieve. */
    booking_ids: string[];
}
