/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         checkout_id: "checkout_id"
 *     }
 */
export interface GetCheckoutsRequest {
    /**
     * The unique ID for the desired `TerminalCheckout`.
     */
    checkout_id: string;
}
