/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../index.js";

/**
 * @example
 *     {
 *         job: {
 *             title: "Cashier",
 *             is_tip_eligible: true
 *         },
 *         idempotency_key: "idempotency-key-0"
 *     }
 */
export interface CreateJobRequest {
    /** The job to create. The `title` field is required and `is_tip_eligible` defaults to true. */
    job: Square.Job;
    /**
     * A unique identifier for the `CreateJob` request. Keys can be any valid string,
     * but must be unique for each request. For more information, see
     * [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency).
     */
    idempotency_key: string;
}
