/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../index.js";

/**
 * @example
 *     {
 *         job_id: "job_id",
 *         job: {
 *             title: "Cashier 1",
 *             is_tip_eligible: true
 *         }
 *     }
 */
export interface UpdateJobRequest {
    /**
     * The ID of the job to update.
     */
    job_id: string;
    /**
     * The job with the updated fields, either `title`, `is_tip_eligible`, or both. Only changed fields need
     * to be included in the request. Optionally include `version` to enable optimistic concurrency control.
     */
    job: Square.Job;
}
