/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         new_plan_variation_id: "FQ7CDXXWSLUJRPM3GFJSJGZ7",
 *         old_plan_variation_id: "6JHXF3B2CW3YKHDV4XEM674H",
 *         location_id: "S8GWD5R9QB376"
 *     }
 */
export interface BulkSwapPlanRequest {
    /**
     * The ID of the new subscription plan variation.
     *
     * This field is required.
     */
    new_plan_variation_id: string;
    /**
     * The ID of the plan variation whose subscriptions should be swapped. Active subscriptions
     * using this plan variation will be subscribed to the new plan variation on their next billing
     * day.
     */
    old_plan_variation_id: string;
    /** The ID of the location to associate with the swapped subscriptions. */
    location_id: string;
}
