/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         subscription_id: "subscription_id"
 *     }
 */
export interface CancelSubscriptionsRequest {
    /**
     * The ID of the subscription to cancel.
     */
    subscription_id: string;
}
