// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         subscriptionId: "subscription_id",
 *         actionId: "action_id"
 *     }
 */
export interface DeleteActionSubscriptionsRequest {
    /** The ID of the subscription the targeted action is to act upon. */
    subscriptionId: string;
    /** The ID of the targeted action to be deleted. */
    actionId: string;
}
