// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const AchDetails: core.serialization.ObjectSchema<serializers.AchDetails.Raw, Square.AchDetails> =
    core.serialization.object({
        routingNumber: core.serialization.property("routing_number", core.serialization.string().optionalNullable()),
        accountNumberSuffix: core.serialization.property(
            "account_number_suffix",
            core.serialization.string().optionalNullable(),
        ),
        accountType: core.serialization.property("account_type", core.serialization.string().optionalNullable()),
    });

export declare namespace AchDetails {
    export interface Raw {
        routing_number?: (string | null | undefined) | null;
        account_number_suffix?: (string | null | undefined) | null;
        account_type?: (string | null | undefined) | null;
    }
}
