/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { AppointmentSegment } from "./AppointmentSegment";

export const Availability: core.serialization.ObjectSchema<serializers.Availability.Raw, Square.Availability> =
    core.serialization.object({
        startAt: core.serialization.property("start_at", core.serialization.string().optionalNullable()),
        locationId: core.serialization.property("location_id", core.serialization.string().optional()),
        appointmentSegments: core.serialization.property(
            "appointment_segments",
            core.serialization.list(AppointmentSegment).optionalNullable(),
        ),
    });

export declare namespace Availability {
    export interface Raw {
        start_at?: (string | null) | null;
        location_id?: string | null;
        appointment_segments?: (AppointmentSegment.Raw[] | null) | null;
    }
}
