/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { BankAccount } from "./BankAccount";

export const BankAccountCreatedEventObject: core.serialization.ObjectSchema<
    serializers.BankAccountCreatedEventObject.Raw,
    Square.BankAccountCreatedEventObject
> = core.serialization.object({
    bankAccount: core.serialization.property("bank_account", BankAccount.optional()),
});

export declare namespace BankAccountCreatedEventObject {
    export interface Raw {
        bank_account?: BankAccount.Raw | null;
    }
}
