// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { BatchUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse } from "./BatchUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse";
import { Error_ } from "./Error_";

export const BatchUpsertCustomerCustomAttributesResponse: core.serialization.ObjectSchema<
    serializers.BatchUpsertCustomerCustomAttributesResponse.Raw,
    Square.BatchUpsertCustomerCustomAttributesResponse
> = core.serialization.object({
    values: core.serialization
        .record(
            core.serialization.string(),
            BatchUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse,
        )
        .optional(),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace BatchUpsertCustomerCustomAttributesResponse {
    export interface Raw {
        values?: Record<
            string,
            BatchUpsertCustomerCustomAttributesResponseCustomerCustomAttributeUpsertResponse.Raw
        > | null;
        errors?: Error_.Raw[] | null;
    }
}
