// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const BatchRetrieveInventoryChangesSortField: core.serialization.Schema<
    serializers.BatchRetrieveInventoryChangesSortField.Raw,
    Square.BatchRetrieveInventoryChangesSortField
> = core.serialization.stringLiteral("OCCURRED_AT");

export declare namespace BatchRetrieveInventoryChangesSortField {
    export type Raw = "OCCURRED_AT";
}
