// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CreateVendorResponse } from "./CreateVendorResponse";
import { Error_ } from "./Error_";

export const BatchCreateVendorsResponse: core.serialization.ObjectSchema<
    serializers.BatchCreateVendorsResponse.Raw,
    Square.BatchCreateVendorsResponse
> = core.serialization.object({
    errors: core.serialization.list(Error_).optional(),
    responses: core.serialization.record(core.serialization.string(), CreateVendorResponse).optional(),
});

export declare namespace BatchCreateVendorsResponse {
    export interface Raw {
        errors?: Error_.Raw[] | null;
        responses?: Record<string, CreateVendorResponse.Raw> | null;
    }
}
