// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CreateTeamMemberResponse } from "./CreateTeamMemberResponse";
import { Error_ } from "./Error_";

export const BatchCreateTeamMembersResponse: core.serialization.ObjectSchema<
    serializers.BatchCreateTeamMembersResponse.Raw,
    Square.BatchCreateTeamMembersResponse
> = core.serialization.object({
    teamMembers: core.serialization.property(
        "team_members",
        core.serialization.record(core.serialization.string(), CreateTeamMemberResponse).optional(),
    ),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace BatchCreateTeamMembersResponse {
    export interface Raw {
        team_members?: Record<string, CreateTeamMemberResponse.Raw> | null;
        errors?: Error_.Raw[] | null;
    }
}
