/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";

export const BulkDeleteOrderCustomAttributesRequestDeleteCustomAttribute: core.serialization.ObjectSchema<
    serializers.BulkDeleteOrderCustomAttributesRequestDeleteCustomAttribute.Raw,
    Square.BulkDeleteOrderCustomAttributesRequestDeleteCustomAttribute
> = core.serialization.object({
    key: core.serialization.string().optional(),
    orderId: core.serialization.property("order_id", core.serialization.string()),
});

export declare namespace BulkDeleteOrderCustomAttributesRequestDeleteCustomAttribute {
    export interface Raw {
        key?: string | null;
        order_id: string;
    }
}
