/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { CustomAttribute } from "./CustomAttribute";

export const BulkUpsertOrderCustomAttributesRequestUpsertCustomAttribute: core.serialization.ObjectSchema<
    serializers.BulkUpsertOrderCustomAttributesRequestUpsertCustomAttribute.Raw,
    Square.BulkUpsertOrderCustomAttributesRequestUpsertCustomAttribute
> = core.serialization.object({
    customAttribute: core.serialization.property("custom_attribute", CustomAttribute),
    idempotencyKey: core.serialization.property("idempotency_key", core.serialization.string().optionalNullable()),
    orderId: core.serialization.property("order_id", core.serialization.string()),
});

export declare namespace BulkUpsertOrderCustomAttributesRequestUpsertCustomAttribute {
    export interface Raw {
        custom_attribute: CustomAttribute.Raw;
        idempotency_key?: (string | null) | null;
        order_id: string;
    }
}
