// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const BusinessAppointmentSettingsBookingLocationType: core.serialization.Schema<
    serializers.BusinessAppointmentSettingsBookingLocationType.Raw,
    Square.BusinessAppointmentSettingsBookingLocationType
> = core.serialization.enum_(["BUSINESS_LOCATION", "CUSTOMER_LOCATION", "PHONE"]);

export declare namespace BusinessAppointmentSettingsBookingLocationType {
    export type Raw = "BUSINESS_LOCATION" | "CUSTOMER_LOCATION" | "PHONE";
}
