// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CardCreatedEventData } from "./CardCreatedEventData";

export const CardCreatedEvent: core.serialization.ObjectSchema<
    serializers.CardCreatedEvent.Raw,
    Square.CardCreatedEvent
> = core.serialization.object({
    merchantId: core.serialization.property("merchant_id", core.serialization.string().optionalNullable()),
    type: core.serialization.string().optionalNullable(),
    eventId: core.serialization.property("event_id", core.serialization.string().optionalNullable()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    data: CardCreatedEventData.optional(),
});

export declare namespace CardCreatedEvent {
    export interface Raw {
        merchant_id?: (string | null | undefined) | null;
        type?: (string | null | undefined) | null;
        event_id?: (string | null | undefined) | null;
        created_at?: string | null;
        data?: CardCreatedEventData.Raw | null;
    }
}
