// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CardCreatedEventObject } from "./CardCreatedEventObject";

export const CardCreatedEventData: core.serialization.ObjectSchema<
    serializers.CardCreatedEventData.Raw,
    Square.CardCreatedEventData
> = core.serialization.object({
    type: core.serialization.string().optionalNullable(),
    id: core.serialization.string().optional(),
    object: CardCreatedEventObject.optional(),
});

export declare namespace CardCreatedEventData {
    export interface Raw {
        type?: (string | null | undefined) | null;
        id?: string | null;
        object?: CardCreatedEventObject.Raw | null;
    }
}
