/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { CatalogItemFoodAndBeverageDetailsDietaryPreference } from "./CatalogItemFoodAndBeverageDetailsDietaryPreference";
import { CatalogItemFoodAndBeverageDetailsIngredient } from "./CatalogItemFoodAndBeverageDetailsIngredient";

export const CatalogItemFoodAndBeverageDetails: core.serialization.ObjectSchema<
    serializers.CatalogItemFoodAndBeverageDetails.Raw,
    Square.CatalogItemFoodAndBeverageDetails
> = core.serialization.object({
    calorieCount: core.serialization.property("calorie_count", core.serialization.number().optionalNullable()),
    dietaryPreferences: core.serialization.property(
        "dietary_preferences",
        core.serialization.list(CatalogItemFoodAndBeverageDetailsDietaryPreference).optionalNullable(),
    ),
    ingredients: core.serialization.list(CatalogItemFoodAndBeverageDetailsIngredient).optionalNullable(),
});

export declare namespace CatalogItemFoodAndBeverageDetails {
    export interface Raw {
        calorie_count?: (number | null) | null;
        dietary_preferences?: (CatalogItemFoodAndBeverageDetailsDietaryPreference.Raw[] | null) | null;
        ingredients?: (CatalogItemFoodAndBeverageDetailsIngredient.Raw[] | null) | null;
    }
}
