// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const CatalogCustomAttributeDefinitionSellerVisibility: core.serialization.Schema<
    serializers.CatalogCustomAttributeDefinitionSellerVisibility.Raw,
    Square.CatalogCustomAttributeDefinitionSellerVisibility
> = core.serialization.enum_(["SELLER_VISIBILITY_HIDDEN", "SELLER_VISIBILITY_READ_WRITE_VALUES"]);

export declare namespace CatalogCustomAttributeDefinitionSellerVisibility {
    export type Raw = "SELLER_VISIBILITY_HIDDEN" | "SELLER_VISIBILITY_READ_WRITE_VALUES";
}
