// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const CatalogItemOptionForItem: core.serialization.ObjectSchema<
    serializers.CatalogItemOptionForItem.Raw,
    Square.CatalogItemOptionForItem
> = core.serialization.object({
    itemOptionId: core.serialization.property("item_option_id", core.serialization.string().optionalNullable()),
});

export declare namespace CatalogItemOptionForItem {
    export interface Raw {
        item_option_id?: (string | null | undefined) | null;
    }
}
