/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";

export const CatalogQueryExact: core.serialization.ObjectSchema<
    serializers.CatalogQueryExact.Raw,
    Square.CatalogQueryExact
> = core.serialization.object({
    attributeName: core.serialization.property("attribute_name", core.serialization.string()),
    attributeValue: core.serialization.property("attribute_value", core.serialization.string()),
});

export declare namespace CatalogQueryExact {
    export interface Raw {
        attribute_name: string;
        attribute_value: string;
    }
}
