/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { CatalogCustomAttributeDefinitionType } from "./CatalogCustomAttributeDefinitionType";
import { SourceApplication } from "./SourceApplication";
import { CatalogObjectType } from "./CatalogObjectType";
import { CatalogCustomAttributeDefinitionSellerVisibility } from "./CatalogCustomAttributeDefinitionSellerVisibility";
import { CatalogCustomAttributeDefinitionAppVisibility } from "./CatalogCustomAttributeDefinitionAppVisibility";
import { CatalogCustomAttributeDefinitionStringConfig } from "./CatalogCustomAttributeDefinitionStringConfig";
import { CatalogCustomAttributeDefinitionNumberConfig } from "./CatalogCustomAttributeDefinitionNumberConfig";
import { CatalogCustomAttributeDefinitionSelectionConfig } from "./CatalogCustomAttributeDefinitionSelectionConfig";

export const CatalogCustomAttributeDefinition: core.serialization.ObjectSchema<
    serializers.CatalogCustomAttributeDefinition.Raw,
    Square.CatalogCustomAttributeDefinition
> = core.serialization.object({
    type: CatalogCustomAttributeDefinitionType,
    name: core.serialization.string(),
    description: core.serialization.string().optionalNullable(),
    sourceApplication: core.serialization.property("source_application", SourceApplication.optional()),
    allowedObjectTypes: core.serialization.property("allowed_object_types", core.serialization.list(CatalogObjectType)),
    sellerVisibility: core.serialization.property(
        "seller_visibility",
        CatalogCustomAttributeDefinitionSellerVisibility.optional(),
    ),
    appVisibility: core.serialization.property(
        "app_visibility",
        CatalogCustomAttributeDefinitionAppVisibility.optional(),
    ),
    stringConfig: core.serialization.property("string_config", CatalogCustomAttributeDefinitionStringConfig.optional()),
    numberConfig: core.serialization.property("number_config", CatalogCustomAttributeDefinitionNumberConfig.optional()),
    selectionConfig: core.serialization.property(
        "selection_config",
        CatalogCustomAttributeDefinitionSelectionConfig.optional(),
    ),
    customAttributeUsageCount: core.serialization.property(
        "custom_attribute_usage_count",
        core.serialization.number().optional(),
    ),
    key: core.serialization.string().optionalNullable(),
});

export declare namespace CatalogCustomAttributeDefinition {
    export interface Raw {
        type: CatalogCustomAttributeDefinitionType.Raw;
        name: string;
        description?: (string | null) | null;
        source_application?: SourceApplication.Raw | null;
        allowed_object_types: CatalogObjectType.Raw[];
        seller_visibility?: CatalogCustomAttributeDefinitionSellerVisibility.Raw | null;
        app_visibility?: CatalogCustomAttributeDefinitionAppVisibility.Raw | null;
        string_config?: CatalogCustomAttributeDefinitionStringConfig.Raw | null;
        number_config?: CatalogCustomAttributeDefinitionNumberConfig.Raw | null;
        selection_config?: CatalogCustomAttributeDefinitionSelectionConfig.Raw | null;
        custom_attribute_usage_count?: number | null;
        key?: (string | null) | null;
    }
}
