/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";

export const CatalogDiscountType: core.serialization.Schema<
    serializers.CatalogDiscountType.Raw,
    Square.CatalogDiscountType
> = core.serialization.enum_(["FIXED_PERCENTAGE", "FIXED_AMOUNT", "VARIABLE_PERCENTAGE", "VARIABLE_AMOUNT"]);

export declare namespace CatalogDiscountType {
    export type Raw = "FIXED_PERCENTAGE" | "FIXED_AMOUNT" | "VARIABLE_PERCENTAGE" | "VARIABLE_AMOUNT";
}
