// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { CheckoutMerchantSettingsPaymentMethodsAfterpayClearpayEligibilityRange } from "./CheckoutMerchantSettingsPaymentMethodsAfterpayClearpayEligibilityRange";

export const CheckoutMerchantSettingsPaymentMethodsAfterpayClearpay: core.serialization.ObjectSchema<
    serializers.CheckoutMerchantSettingsPaymentMethodsAfterpayClearpay.Raw,
    Square.CheckoutMerchantSettingsPaymentMethodsAfterpayClearpay
> = core.serialization.object({
    orderEligibilityRange: core.serialization.property(
        "order_eligibility_range",
        CheckoutMerchantSettingsPaymentMethodsAfterpayClearpayEligibilityRange.optional(),
    ),
    itemEligibilityRange: core.serialization.property(
        "item_eligibility_range",
        CheckoutMerchantSettingsPaymentMethodsAfterpayClearpayEligibilityRange.optional(),
    ),
    enabled: core.serialization.boolean().optional(),
});

export declare namespace CheckoutMerchantSettingsPaymentMethodsAfterpayClearpay {
    export interface Raw {
        order_eligibility_range?: CheckoutMerchantSettingsPaymentMethodsAfterpayClearpayEligibilityRange.Raw | null;
        item_eligibility_range?: CheckoutMerchantSettingsPaymentMethodsAfterpayClearpayEligibilityRange.Raw | null;
        enabled?: boolean | null;
    }
}
