// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Error_ } from "./Error_";
import { InventoryAdjustmentReason } from "./InventoryAdjustmentReason";

export const CreateInventoryAdjustmentReasonResponse: core.serialization.ObjectSchema<
    serializers.CreateInventoryAdjustmentReasonResponse.Raw,
    Square.CreateInventoryAdjustmentReasonResponse
> = core.serialization.object({
    errors: core.serialization.list(Error_).optional(),
    adjustmentReason: core.serialization.property("adjustment_reason", InventoryAdjustmentReason.optional()),
});

export declare namespace CreateInventoryAdjustmentReasonResponse {
    export interface Raw {
        errors?: Error_.Raw[] | null;
        adjustment_reason?: InventoryAdjustmentReason.Raw | null;
    }
}
