/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { Error_ } from "./Error_";
import { LoyaltyPromotion } from "./LoyaltyPromotion";

export const CreateLoyaltyPromotionResponse: core.serialization.ObjectSchema<
    serializers.CreateLoyaltyPromotionResponse.Raw,
    Square.CreateLoyaltyPromotionResponse
> = core.serialization.object({
    errors: core.serialization.list(Error_).optional(),
    loyaltyPromotion: core.serialization.property("loyalty_promotion", LoyaltyPromotion.optional()),
});

export declare namespace CreateLoyaltyPromotionResponse {
    export interface Raw {
        errors?: Error_.Raw[] | null;
        loyalty_promotion?: LoyaltyPromotion.Raw | null;
    }
}
