// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Error_ } from "./Error_";
import { Job } from "./Job";

export const CreateJobResponse: core.serialization.ObjectSchema<
    serializers.CreateJobResponse.Raw,
    Square.CreateJobResponse
> = core.serialization.object({
    job: Job.optional(),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace CreateJobResponse {
    export interface Raw {
        job?: Job.Raw | null;
        errors?: Error_.Raw[] | null;
    }
}
