/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";

export const DestinationDetailsExternalRefundDetails: core.serialization.ObjectSchema<
    serializers.DestinationDetailsExternalRefundDetails.Raw,
    Square.DestinationDetailsExternalRefundDetails
> = core.serialization.object({
    type: core.serialization.string(),
    source: core.serialization.string(),
    sourceId: core.serialization.property("source_id", core.serialization.string().optionalNullable()),
});

export declare namespace DestinationDetailsExternalRefundDetails {
    export interface Raw {
        type: string;
        source: string;
        source_id?: (string | null) | null;
    }
}
