// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { BankAccount } from "./BankAccount";
import { Error_ } from "./Error_";

export const DisableBankAccountResponse: core.serialization.ObjectSchema<
    serializers.DisableBankAccountResponse.Raw,
    Square.DisableBankAccountResponse
> = core.serialization.object({
    bankAccount: core.serialization.property("bank_account", BankAccount.optional()),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace DisableBankAccountResponse {
    export interface Raw {
        bank_account?: BankAccount.Raw | null;
        errors?: Error_.Raw[] | null;
    }
}
