// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const FilterValue: core.serialization.ObjectSchema<serializers.FilterValue.Raw, Square.FilterValue> =
    core.serialization.object({
        all: core.serialization.list(core.serialization.string()).optionalNullable(),
        any: core.serialization.list(core.serialization.string()).optionalNullable(),
        none: core.serialization.list(core.serialization.string()).optionalNullable(),
    });

export declare namespace FilterValue {
    export interface Raw {
        all?: (string[] | null | undefined) | null;
        any?: (string[] | null | undefined) | null;
        none?: (string[] | null | undefined) | null;
    }
}
