// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { FulfillmentRecipient } from "./FulfillmentRecipient";

export const FulfillmentShipmentDetails: core.serialization.ObjectSchema<
    serializers.FulfillmentShipmentDetails.Raw,
    Square.FulfillmentShipmentDetails
> = core.serialization.object({
    recipient: FulfillmentRecipient.optional(),
    carrier: core.serialization.string().optionalNullable(),
    shippingNote: core.serialization.property("shipping_note", core.serialization.string().optionalNullable()),
    shippingType: core.serialization.property("shipping_type", core.serialization.string().optionalNullable()),
    trackingNumber: core.serialization.property("tracking_number", core.serialization.string().optionalNullable()),
    trackingUrl: core.serialization.property("tracking_url", core.serialization.string().optionalNullable()),
    placedAt: core.serialization.property("placed_at", core.serialization.string().optional()),
    inProgressAt: core.serialization.property("in_progress_at", core.serialization.string().optional()),
    packagedAt: core.serialization.property("packaged_at", core.serialization.string().optional()),
    expectedShippedAt: core.serialization.property(
        "expected_shipped_at",
        core.serialization.string().optionalNullable(),
    ),
    shippedAt: core.serialization.property("shipped_at", core.serialization.string().optional()),
    canceledAt: core.serialization.property("canceled_at", core.serialization.string().optionalNullable()),
    cancelReason: core.serialization.property("cancel_reason", core.serialization.string().optionalNullable()),
    failedAt: core.serialization.property("failed_at", core.serialization.string().optional()),
    failureReason: core.serialization.property("failure_reason", core.serialization.string().optionalNullable()),
});

export declare namespace FulfillmentShipmentDetails {
    export interface Raw {
        recipient?: FulfillmentRecipient.Raw | null;
        carrier?: (string | null | undefined) | null;
        shipping_note?: (string | null | undefined) | null;
        shipping_type?: (string | null | undefined) | null;
        tracking_number?: (string | null | undefined) | null;
        tracking_url?: (string | null | undefined) | null;
        placed_at?: string | null;
        in_progress_at?: string | null;
        packaged_at?: string | null;
        expected_shipped_at?: (string | null | undefined) | null;
        shipped_at?: string | null;
        canceled_at?: (string | null | undefined) | null;
        cancel_reason?: (string | null | undefined) | null;
        failed_at?: string | null;
        failure_reason?: (string | null | undefined) | null;
    }
}
