// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { BankAccount } from "./BankAccount";
import { Error_ } from "./Error_";

export const GetBankAccountResponse: core.serialization.ObjectSchema<
    serializers.GetBankAccountResponse.Raw,
    Square.GetBankAccountResponse
> = core.serialization.object({
    errors: core.serialization.list(Error_).optional(),
    bankAccount: core.serialization.property("bank_account", BankAccount.optional()),
});

export declare namespace GetBankAccountResponse {
    export interface Raw {
        errors?: Error_.Raw[] | null;
        bank_account?: BankAccount.Raw | null;
    }
}
