/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { Order } from "./Order";
import { Error_ } from "./Error_";

export const GetOrderResponse: core.serialization.ObjectSchema<
    serializers.GetOrderResponse.Raw,
    Square.GetOrderResponse
> = core.serialization.object({
    order: Order.optional(),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace GetOrderResponse {
    export interface Raw {
        order?: Order.Raw | null;
        errors?: Error_.Raw[] | null;
    }
}
