// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const GetVendorRequest: core.serialization.Schema<serializers.GetVendorRequest.Raw, Square.GetVendorRequest> =
    core.serialization.unknown();

export declare namespace GetVendorRequest {
    export type Raw = unknown;
}
