/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";

export const GetWebhookSubscriptionRequest: core.serialization.Schema<
    serializers.GetWebhookSubscriptionRequest.Raw,
    Square.GetWebhookSubscriptionRequest
> = core.serialization.unknown();

export declare namespace GetWebhookSubscriptionRequest {
    export type Raw = unknown;
}
