// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const GiftCardActivityClearBalanceReason: core.serialization.Schema<
    serializers.GiftCardActivityClearBalanceReason.Raw,
    Square.GiftCardActivityClearBalanceReason
> = core.serialization.enum_(["SUSPICIOUS_ACTIVITY", "REUSE_GIFTCARD", "UNKNOWN_REASON"]);

export declare namespace GiftCardActivityClearBalanceReason {
    export type Raw = "SUSPICIOUS_ACTIVITY" | "REUSE_GIFTCARD" | "UNKNOWN_REASON";
}
