/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { GiftCardActivityUpdatedEventObject } from "./GiftCardActivityUpdatedEventObject";

export const GiftCardActivityUpdatedEventData: core.serialization.ObjectSchema<
    serializers.GiftCardActivityUpdatedEventData.Raw,
    Square.GiftCardActivityUpdatedEventData
> = core.serialization.object({
    type: core.serialization.string().optionalNullable(),
    id: core.serialization.string().optional(),
    object: GiftCardActivityUpdatedEventObject.optional(),
});

export declare namespace GiftCardActivityUpdatedEventData {
    export interface Raw {
        type?: (string | null) | null;
        id?: string | null;
        object?: GiftCardActivityUpdatedEventObject.Raw | null;
    }
}
