// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { GiftCardActivityAdjustIncrementReason } from "./GiftCardActivityAdjustIncrementReason";
import { Money } from "./Money";

export const GiftCardActivityAdjustIncrement: core.serialization.ObjectSchema<
    serializers.GiftCardActivityAdjustIncrement.Raw,
    Square.GiftCardActivityAdjustIncrement
> = core.serialization.object({
    amountMoney: core.serialization.property("amount_money", Money),
    reason: GiftCardActivityAdjustIncrementReason,
});

export declare namespace GiftCardActivityAdjustIncrement {
    export interface Raw {
        amount_money: Money.Raw;
        reason: GiftCardActivityAdjustIncrementReason.Raw;
    }
}
