/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { InventoryCount } from "./InventoryCount";

export const InventoryCountUpdatedEventObject: core.serialization.ObjectSchema<
    serializers.InventoryCountUpdatedEventObject.Raw,
    Square.InventoryCountUpdatedEventObject
> = core.serialization.object({
    inventoryCounts: core.serialization.property(
        "inventory_counts",
        core.serialization.list(InventoryCount).optionalNullable(),
    ),
});

export declare namespace InventoryCountUpdatedEventObject {
    export interface Raw {
        inventory_counts?: (InventoryCount.Raw[] | null) | null;
    }
}
