/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { Shift } from "./Shift";

export const LaborShiftUpdatedEventObject: core.serialization.ObjectSchema<
    serializers.LaborShiftUpdatedEventObject.Raw,
    Square.LaborShiftUpdatedEventObject
> = core.serialization.object({
    shift: Shift.optional(),
});

export declare namespace LaborShiftUpdatedEventObject {
    export interface Raw {
        shift?: Shift.Raw | null;
    }
}
