// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const LinkFormat: core.serialization.ObjectSchema<serializers.LinkFormat.Raw, Square.LinkFormat> =
    core.serialization.object({
        label: core.serialization.string(),
        type: core.serialization.stringLiteral("link"),
    });

export declare namespace LinkFormat {
    export interface Raw {
        label: string;
        type: "link";
    }
}
