/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { Error_ } from "./Error_";
import { Dispute } from "./Dispute";

export const ListDisputesResponse: core.serialization.ObjectSchema<
    serializers.ListDisputesResponse.Raw,
    Square.ListDisputesResponse
> = core.serialization.object({
    errors: core.serialization.list(Error_).optional(),
    disputes: core.serialization.list(Dispute).optional(),
    cursor: core.serialization.string().optional(),
});

export declare namespace ListDisputesResponse {
    export interface Raw {
        errors?: Error_.Raw[] | null;
        disputes?: Dispute.Raw[] | null;
        cursor?: string | null;
    }
}
