// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Error_ } from "./Error_";
import { Payout } from "./Payout";

export const ListPayoutsResponse: core.serialization.ObjectSchema<
    serializers.ListPayoutsResponse.Raw,
    Square.ListPayoutsResponse
> = core.serialization.object({
    payouts: core.serialization.list(Payout).optional(),
    cursor: core.serialization.string().optional(),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace ListPayoutsResponse {
    export interface Raw {
        payouts?: Payout.Raw[] | null;
        cursor?: string | null;
        errors?: Error_.Raw[] | null;
    }
}
