// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const LoadResultAnnotation: core.serialization.ObjectSchema<
    serializers.LoadResultAnnotation.Raw,
    Square.LoadResultAnnotation
> = core.serialization.object({
    measures: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    dimensions: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    segments: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    timeDimensions: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
});

export declare namespace LoadResultAnnotation {
    export interface Raw {
        measures: Record<string, unknown>;
        dimensions: Record<string, unknown>;
        segments: Record<string, unknown>;
        timeDimensions: Record<string, unknown>;
    }
}
