// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { LocationSettingsUpdatedEventObject } from "./LocationSettingsUpdatedEventObject";

export const LocationSettingsUpdatedEventData: core.serialization.ObjectSchema<
    serializers.LocationSettingsUpdatedEventData.Raw,
    Square.LocationSettingsUpdatedEventData
> = core.serialization.object({
    type: core.serialization.string().optionalNullable(),
    id: core.serialization.string().optional(),
    object: LocationSettingsUpdatedEventObject.optional(),
});

export declare namespace LocationSettingsUpdatedEventData {
    export interface Raw {
        type?: (string | null | undefined) | null;
        id?: string | null;
        object?: LocationSettingsUpdatedEventObject.Raw | null;
    }
}
