// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const LoyaltyProgramAccrualRuleType: core.serialization.Schema<
    serializers.LoyaltyProgramAccrualRuleType.Raw,
    Square.LoyaltyProgramAccrualRuleType
> = core.serialization.enum_(["VISIT", "SPEND", "ITEM_VARIATION", "CATEGORY"]);

export declare namespace LoyaltyProgramAccrualRuleType {
    export type Raw = "VISIT" | "SPEND" | "ITEM_VARIATION" | "CATEGORY";
}
