// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Format } from "./Format";
import { FormatDescription } from "./FormatDescription";

export const Measure: core.serialization.ObjectSchema<serializers.Measure.Raw, Square.Measure> =
    core.serialization.object({
        name: core.serialization.string(),
        title: core.serialization.string().optional(),
        shortTitle: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        type: core.serialization.string(),
        aggType: core.serialization.string().optional(),
        meta: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        format: Format.optional(),
        formatDescription: FormatDescription.optional(),
        currency: core.serialization.string().optional(),
        aliasMember: core.serialization.string().optional(),
    });

export declare namespace Measure {
    export interface Raw {
        name: string;
        title?: string | null;
        shortTitle?: string | null;
        description?: string | null;
        type: string;
        aggType?: string | null;
        meta?: Record<string, unknown> | null;
        format?: Format.Raw | null;
        formatDescription?: FormatDescription.Raw | null;
        currency?: string | null;
        aliasMember?: string | null;
    }
}
