/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";

export const MeasurementUnitUnitType: core.serialization.Schema<
    serializers.MeasurementUnitUnitType.Raw,
    Square.MeasurementUnitUnitType
> = core.serialization.enum_(["TYPE_CUSTOM", "TYPE_AREA", "TYPE_LENGTH", "TYPE_VOLUME", "TYPE_WEIGHT", "TYPE_GENERIC"]);

export declare namespace MeasurementUnitUnitType {
    export type Raw = "TYPE_CUSTOM" | "TYPE_AREA" | "TYPE_LENGTH" | "TYPE_VOLUME" | "TYPE_WEIGHT" | "TYPE_GENERIC";
}
