// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Currency } from "./Currency";

export const Money: core.serialization.ObjectSchema<serializers.Money.Raw, Square.Money> = core.serialization.object({
    amount: core.serialization.bigint().optionalNullable(),
    currency: Currency.optional(),
});

export declare namespace Money {
    export interface Raw {
        amount?: ((bigint | number) | null | undefined) | null;
        currency?: Currency.Raw | null;
    }
}
