// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const OrderLineItemPricingBlocklistsBlockedDiscount: core.serialization.ObjectSchema<
    serializers.OrderLineItemPricingBlocklistsBlockedDiscount.Raw,
    Square.OrderLineItemPricingBlocklistsBlockedDiscount
> = core.serialization.object({
    uid: core.serialization.string().optionalNullable(),
    discountUid: core.serialization.property("discount_uid", core.serialization.string().optionalNullable()),
    discountCatalogObjectId: core.serialization.property(
        "discount_catalog_object_id",
        core.serialization.string().optionalNullable(),
    ),
});

export declare namespace OrderLineItemPricingBlocklistsBlockedDiscount {
    export interface Raw {
        uid?: (string | null | undefined) | null;
        discount_uid?: (string | null | undefined) | null;
        discount_catalog_object_id?: (string | null | undefined) | null;
    }
}
