// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Money } from "./Money";
import { OrderLineItemTaxScope } from "./OrderLineItemTaxScope";
import { OrderLineItemTaxType } from "./OrderLineItemTaxType";

export const OrderLineItemTax: core.serialization.ObjectSchema<
    serializers.OrderLineItemTax.Raw,
    Square.OrderLineItemTax
> = core.serialization.object({
    uid: core.serialization.string().optionalNullable(),
    catalogObjectId: core.serialization.property("catalog_object_id", core.serialization.string().optionalNullable()),
    catalogVersion: core.serialization.property("catalog_version", core.serialization.bigint().optionalNullable()),
    name: core.serialization.string().optionalNullable(),
    type: OrderLineItemTaxType.optional(),
    percentage: core.serialization.string().optionalNullable(),
    metadata: core.serialization
        .record(core.serialization.string(), core.serialization.string().optionalNullable())
        .optionalNullable(),
    appliedMoney: core.serialization.property("applied_money", Money.optional()),
    scope: OrderLineItemTaxScope.optional(),
    autoApplied: core.serialization.property("auto_applied", core.serialization.boolean().optional()),
});

export declare namespace OrderLineItemTax {
    export interface Raw {
        uid?: (string | null | undefined) | null;
        catalog_object_id?: (string | null | undefined) | null;
        catalog_version?: ((bigint | number) | null | undefined) | null;
        name?: (string | null | undefined) | null;
        type?: OrderLineItemTaxType.Raw | null;
        percentage?: (string | null | undefined) | null;
        metadata?: (Record<string, (string | null | undefined) | null | undefined> | null | undefined) | null;
        applied_money?: Money.Raw | null;
        scope?: OrderLineItemTaxScope.Raw | null;
        auto_applied?: boolean | null;
    }
}
