// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { OrderCreatedObject } from "./OrderCreatedObject";

export const OrderCreatedEventData: core.serialization.ObjectSchema<
    serializers.OrderCreatedEventData.Raw,
    Square.OrderCreatedEventData
> = core.serialization.object({
    type: core.serialization.string().optionalNullable(),
    id: core.serialization.string().optional(),
    object: OrderCreatedObject.optional(),
});

export declare namespace OrderCreatedEventData {
    export interface Raw {
        type?: (string | null | undefined) | null;
        id?: string | null;
        object?: OrderCreatedObject.Raw | null;
    }
}
