// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const OrderLineItemDiscountType: core.serialization.Schema<
    serializers.OrderLineItemDiscountType.Raw,
    Square.OrderLineItemDiscountType
> = core.serialization.enum_([
    "UNKNOWN_DISCOUNT",
    "FIXED_PERCENTAGE",
    "FIXED_AMOUNT",
    "VARIABLE_PERCENTAGE",
    "VARIABLE_AMOUNT",
]);

export declare namespace OrderLineItemDiscountType {
    export type Raw =
        | "UNKNOWN_DISCOUNT"
        | "FIXED_PERCENTAGE"
        | "FIXED_AMOUNT"
        | "VARIABLE_PERCENTAGE"
        | "VARIABLE_AMOUNT";
}
