// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializerTypes from "../index";
import { serialization as serializers } from "../lazy";
import { Order } from "./Order";

export const PaymentLinkRelatedResources: core.serialization.ObjectSchema<
    serializerTypes.PaymentLinkRelatedResources.Raw,
    Square.PaymentLinkRelatedResources
> = core.serialization.object({
    orders: core.serialization.list(Order).optionalNullable(),
    subscriptionPlans: core.serialization.property(
        "subscription_plans",
        core.serialization.list(core.serialization.lazy(() => serializers.CatalogObject)).optionalNullable(),
    ),
});

export declare namespace PaymentLinkRelatedResources {
    export interface Raw {
        orders?: (Order.Raw[] | null | undefined) | null;
        subscription_plans?: (serializerTypes.CatalogObject.Raw[] | null | undefined) | null;
    }
}
