// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { PaymentCreatedEventObject } from "./PaymentCreatedEventObject";

export const PaymentCreatedEventData: core.serialization.ObjectSchema<
    serializers.PaymentCreatedEventData.Raw,
    Square.PaymentCreatedEventData
> = core.serialization.object({
    type: core.serialization.string().optionalNullable(),
    id: core.serialization.string().optional(),
    object: PaymentCreatedEventObject.optional(),
});

export declare namespace PaymentCreatedEventData {
    export interface Raw {
        type?: (string | null | undefined) | null;
        id?: string | null;
        object?: PaymentCreatedEventObject.Raw | null;
    }
}
