/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { PayoutStatus } from "./PayoutStatus";
import { Money } from "./Money";
import { Destination } from "./Destination";
import { PayoutType } from "./PayoutType";
import { PayoutFee } from "./PayoutFee";

export const Payout: core.serialization.ObjectSchema<serializers.Payout.Raw, Square.Payout> = core.serialization.object(
    {
        id: core.serialization.string(),
        status: PayoutStatus.optional(),
        locationId: core.serialization.property("location_id", core.serialization.string()),
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.string().optional()),
        amountMoney: core.serialization.property("amount_money", Money.optional()),
        destination: Destination.optional(),
        version: core.serialization.number().optional(),
        type: PayoutType.optional(),
        payoutFee: core.serialization.property("payout_fee", core.serialization.list(PayoutFee).optionalNullable()),
        arrivalDate: core.serialization.property("arrival_date", core.serialization.string().optionalNullable()),
        endToEndId: core.serialization.property("end_to_end_id", core.serialization.string().optionalNullable()),
    },
);

export declare namespace Payout {
    export interface Raw {
        id: string;
        status?: PayoutStatus.Raw | null;
        location_id: string;
        created_at?: string | null;
        updated_at?: string | null;
        amount_money?: Money.Raw | null;
        destination?: Destination.Raw | null;
        version?: number | null;
        type?: PayoutType.Raw | null;
        payout_fee?: (PayoutFee.Raw[] | null) | null;
        arrival_date?: (string | null) | null;
        end_to_end_id?: (string | null) | null;
    }
}
