// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Error_ } from "./Error_";

export const RetrieveTokenStatusResponse: core.serialization.ObjectSchema<
    serializers.RetrieveTokenStatusResponse.Raw,
    Square.RetrieveTokenStatusResponse
> = core.serialization.object({
    scopes: core.serialization.list(core.serialization.string()).optional(),
    expiresAt: core.serialization.property("expires_at", core.serialization.string().optional()),
    clientId: core.serialization.property("client_id", core.serialization.string().optional()),
    merchantId: core.serialization.property("merchant_id", core.serialization.string().optional()),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace RetrieveTokenStatusResponse {
    export interface Raw {
        scopes?: string[] | null;
        expires_at?: string | null;
        client_id?: string | null;
        merchant_id?: string | null;
        errors?: Error_.Raw[] | null;
    }
}
