/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { RiskEvaluationRiskLevel } from "./RiskEvaluationRiskLevel";

export const RiskEvaluation: core.serialization.ObjectSchema<serializers.RiskEvaluation.Raw, Square.RiskEvaluation> =
    core.serialization.object({
        createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
        riskLevel: core.serialization.property("risk_level", RiskEvaluationRiskLevel.optional()),
    });

export declare namespace RiskEvaluation {
    export interface Raw {
        created_at?: string | null;
        risk_level?: RiskEvaluationRiskLevel.Raw | null;
    }
}
