// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { Error_ } from "./Error_";
import { TransferOrder } from "./TransferOrder";

export const SearchTransferOrdersResponse: core.serialization.ObjectSchema<
    serializers.SearchTransferOrdersResponse.Raw,
    Square.SearchTransferOrdersResponse
> = core.serialization.object({
    transferOrders: core.serialization.property("transfer_orders", core.serialization.list(TransferOrder).optional()),
    cursor: core.serialization.string().optional(),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace SearchTransferOrdersResponse {
    export interface Raw {
        transfer_orders?: TransferOrder.Raw[] | null;
        cursor?: string | null;
        errors?: Error_.Raw[] | null;
    }
}
