/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { Product } from "./Product";

export const SourceApplication: core.serialization.ObjectSchema<
    serializers.SourceApplication.Raw,
    Square.SourceApplication
> = core.serialization.object({
    product: Product.optional(),
    applicationId: core.serialization.property("application_id", core.serialization.string().optionalNullable()),
    name: core.serialization.string().optionalNullable(),
});

export declare namespace SourceApplication {
    export interface Raw {
        product?: Product.Raw | null;
        application_id?: (string | null) | null;
        name?: (string | null) | null;
    }
}
