// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const SubscriptionStatus: core.serialization.Schema<
    serializers.SubscriptionStatus.Raw,
    Square.SubscriptionStatus
> = core.serialization.enum_(["PENDING", "ACTIVE", "CANCELED", "DEACTIVATED", "PAUSED", "COMPLETED"]);

export declare namespace SubscriptionStatus {
    export type Raw = "PENDING" | "ACTIVE" | "CANCELED" | "DEACTIVATED" | "PAUSED" | "COMPLETED";
}
