/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { SubscriptionEventInfoCode } from "./SubscriptionEventInfoCode";

export const SubscriptionEventInfo: core.serialization.ObjectSchema<
    serializers.SubscriptionEventInfo.Raw,
    Square.SubscriptionEventInfo
> = core.serialization.object({
    detail: core.serialization.string().optionalNullable(),
    code: SubscriptionEventInfoCode.optional(),
});

export declare namespace SubscriptionEventInfo {
    export interface Raw {
        detail?: (string | null) | null;
        code?: SubscriptionEventInfoCode.Raw | null;
    }
}
