/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { TeamMemberWageSettingUpdatedEventObject } from "./TeamMemberWageSettingUpdatedEventObject";

export const TeamMemberWageSettingUpdatedEventData: core.serialization.ObjectSchema<
    serializers.TeamMemberWageSettingUpdatedEventData.Raw,
    Square.TeamMemberWageSettingUpdatedEventData
> = core.serialization.object({
    type: core.serialization.string().optionalNullable(),
    id: core.serialization.string().optional(),
    object: TeamMemberWageSettingUpdatedEventObject.optional(),
});

export declare namespace TeamMemberWageSettingUpdatedEventData {
    export interface Raw {
        type?: (string | null) | null;
        id?: string | null;
        object?: TeamMemberWageSettingUpdatedEventObject.Raw | null;
    }
}
