/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { Money } from "./Money";

export const TenderCashDetails: core.serialization.ObjectSchema<
    serializers.TenderCashDetails.Raw,
    Square.TenderCashDetails
> = core.serialization.object({
    buyerTenderedMoney: core.serialization.property("buyer_tendered_money", Money.optional()),
    changeBackMoney: core.serialization.property("change_back_money", Money.optional()),
});

export declare namespace TenderCashDetails {
    export interface Raw {
        buyer_tendered_money?: Money.Raw | null;
        change_back_money?: Money.Raw | null;
    }
}
