// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { TerminalCheckout } from "./TerminalCheckout";

export const TerminalCheckoutUpdatedEventObject: core.serialization.ObjectSchema<
    serializers.TerminalCheckoutUpdatedEventObject.Raw,
    Square.TerminalCheckoutUpdatedEventObject
> = core.serialization.object({
    checkout: TerminalCheckout.optional(),
});

export declare namespace TerminalCheckoutUpdatedEventObject {
    export interface Raw {
        checkout?: TerminalCheckout.Raw | null;
    }
}
