// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";
import { TerminalActionActionType } from "./TerminalActionActionType";
import { TimeRange } from "./TimeRange";

export const TerminalActionQueryFilter: core.serialization.ObjectSchema<
    serializers.TerminalActionQueryFilter.Raw,
    Square.TerminalActionQueryFilter
> = core.serialization.object({
    deviceId: core.serialization.property("device_id", core.serialization.string().optionalNullable()),
    createdAt: core.serialization.property("created_at", TimeRange.optional()),
    status: core.serialization.string().optionalNullable(),
    type: TerminalActionActionType.optional(),
});

export declare namespace TerminalActionQueryFilter {
    export interface Raw {
        device_id?: (string | null | undefined) | null;
        created_at?: TimeRange.Raw | null;
        status?: (string | null | undefined) | null;
        type?: TerminalActionActionType.Raw | null;
    }
}
