// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const TransactionType: core.serialization.Schema<serializers.TransactionType.Raw, Square.TransactionType> =
    core.serialization.enum_(["DEBIT", "CREDIT"]);

export declare namespace TransactionType {
    export type Raw = "DEBIT" | "CREDIT";
}
