// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../api/index";
import * as core from "../../core";
import type * as serializers from "../index";

export const UpdateTransferOrderLineData: core.serialization.ObjectSchema<
    serializers.UpdateTransferOrderLineData.Raw,
    Square.UpdateTransferOrderLineData
> = core.serialization.object({
    uid: core.serialization.string().optionalNullable(),
    itemVariationId: core.serialization.property("item_variation_id", core.serialization.string().optionalNullable()),
    quantityOrdered: core.serialization.property("quantity_ordered", core.serialization.string().optionalNullable()),
    remove: core.serialization.boolean().optionalNullable(),
});

export declare namespace UpdateTransferOrderLineData {
    export interface Raw {
        uid?: (string | null | undefined) | null;
        item_variation_id?: (string | null | undefined) | null;
        quantity_ordered?: (string | null | undefined) | null;
        remove?: (boolean | null | undefined) | null;
    }
}
