/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { UpdateTransferOrderLineData } from "./UpdateTransferOrderLineData";

export const UpdateTransferOrderData: core.serialization.ObjectSchema<
    serializers.UpdateTransferOrderData.Raw,
    Square.UpdateTransferOrderData
> = core.serialization.object({
    sourceLocationId: core.serialization.property("source_location_id", core.serialization.string().optionalNullable()),
    destinationLocationId: core.serialization.property(
        "destination_location_id",
        core.serialization.string().optionalNullable(),
    ),
    expectedAt: core.serialization.property("expected_at", core.serialization.string().optionalNullable()),
    notes: core.serialization.string().optionalNullable(),
    trackingNumber: core.serialization.property("tracking_number", core.serialization.string().optionalNullable()),
    lineItems: core.serialization.property(
        "line_items",
        core.serialization.list(UpdateTransferOrderLineData).optionalNullable(),
    ),
});

export declare namespace UpdateTransferOrderData {
    export interface Raw {
        source_location_id?: (string | null) | null;
        destination_location_id?: (string | null) | null;
        expected_at?: (string | null) | null;
        notes?: (string | null) | null;
        tracking_number?: (string | null) | null;
        line_items?: (UpdateTransferOrderLineData.Raw[] | null) | null;
    }
}
