/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { Booking } from "./Booking";
import { Error_ } from "./Error_";

export const UpdateBookingResponse: core.serialization.ObjectSchema<
    serializers.UpdateBookingResponse.Raw,
    Square.UpdateBookingResponse
> = core.serialization.object({
    booking: Booking.optional(),
    errors: core.serialization.list(Error_).optional(),
});

export declare namespace UpdateBookingResponse {
    export interface Raw {
        booking?: Booking.Raw | null;
        errors?: Error_.Raw[] | null;
    }
}
