/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as Square from "../../api/index";
import * as core from "../../core";
import { VendorUpdatedEventObjectOperation } from "./VendorUpdatedEventObjectOperation";
import { Vendor } from "./Vendor";

export const VendorUpdatedEventObject: core.serialization.ObjectSchema<
    serializers.VendorUpdatedEventObject.Raw,
    Square.VendorUpdatedEventObject
> = core.serialization.object({
    operation: VendorUpdatedEventObjectOperation.optional(),
    vendor: Vendor.optional(),
});

export declare namespace VendorUpdatedEventObject {
    export interface Raw {
        operation?: VendorUpdatedEventObjectOperation.Raw | null;
        vendor?: Vendor.Raw | null;
    }
}
