// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";

export const CreateMobileAuthorizationCodeRequest: core.serialization.Schema<
    serializers.CreateMobileAuthorizationCodeRequest.Raw,
    Square.CreateMobileAuthorizationCodeRequest
> = core.serialization.object({
    locationId: core.serialization.property("location_id", core.serialization.string().optional()),
});

export declare namespace CreateMobileAuthorizationCodeRequest {
    export interface Raw {
        location_id?: string | null;
    }
}
