/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../index";

/**
 * @example
 *     {
 *         cursor: "cursor",
 *         limit: 1,
 *         sortField: "DEFAULT",
 *         sortOrder: "DESC",
 *         count: true
 *     }
 */
export interface ListCustomersRequest {
    /**
     * A pagination cursor returned by a previous call to this endpoint.
     * Provide this cursor to retrieve the next set of results for your original query.
     *
     * For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
     */
    cursor?: string | null;
    /**
     * The maximum number of results to return in a single page. This limit is advisory. The response might contain more or fewer results.
     * If the specified limit is less than 1 or greater than 100, Square returns a `400 VALUE_TOO_LOW` or `400 VALUE_TOO_HIGH` error. The default value is 100.
     *
     * For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
     */
    limit?: number | null;
    /**
     * Indicates how customers should be sorted.
     *
     * The default value is `DEFAULT`.
     */
    sortField?: Square.CustomerSortField | null;
    /**
     * Indicates whether customers should be sorted in ascending (`ASC`) or
     * descending (`DESC`) order.
     *
     * The default value is `ASC`.
     */
    sortOrder?: Square.SortOrder | null;
    /**
     * Indicates whether to return the total count of customers in the `count` field of the response.
     *
     * The default value is `false`.
     */
    count?: boolean | null;
}
