/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Square from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface SearchEventsRequest {
    /**
     * A pagination cursor returned by a previous call to this endpoint. Provide this cursor to retrieve the next set of events for your original query.
     *
     * For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
     */
    cursor?: string;
    /**
     * The maximum number of events to return in a single page. The response might contain fewer events. The default value is 100, which is also the maximum allowed value.
     *
     * For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination).
     *
     * Default: 100
     */
    limit?: number;
    /** The filtering and sorting criteria for the search request. To retrieve additional pages using a cursor, you must use the original query. */
    query?: Square.SearchEventsQuery;
}
