/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../../index";
import * as Square from "../../../../../../../api/index";
import * as core from "../../../../../../../core";

export const TestWebhookSubscriptionRequest: core.serialization.Schema<
    serializers.webhooks.TestWebhookSubscriptionRequest.Raw,
    Omit<Square.webhooks.TestWebhookSubscriptionRequest, "subscriptionId">
> = core.serialization.object({
    eventType: core.serialization.property("event_type", core.serialization.string().optionalNullable()),
});

export declare namespace TestWebhookSubscriptionRequest {
    export interface Raw {
        event_type?: (string | null) | null;
    }
}
