/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { SquareClient } from "../../src/Client";

describe("Devices", () => {
    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            device: {
                id: "device:995CS397A6475287",
                attributes: {
                    type: "TERMINAL",
                    manufacturer: "Square",
                    model: "T2",
                    name: "Square Terminal 995",
                    manufacturers_id: "995CS397A6475287",
                    updated_at: "2023-09-29T13:12:22.365049321Z",
                    version: "5.41.0085",
                    merchant_token: "MLCHXZCBWFGDW",
                },
                components: [
                    {
                        type: "APPLICATION",
                        application_details: {
                            application_type: "TERMINAL_API",
                            version: "6.25",
                            session_location: "LMN2K7S3RTOU3",
                        },
                    },
                    { type: "CARD_READER", card_reader_details: { version: "3.53.70" } },
                    { type: "BATTERY", battery_details: { visible_percent: 5, external_power: "AVAILABLE_CHARGING" } },
                    {
                        type: "WIFI",
                        wifi_details: {
                            active: true,
                            ssid: "Staff Network",
                            ip_address_v4: "10.0.0.7",
                            secure_connection: "WPA/WPA2 PSK",
                            signal_strength: { value: 2 },
                        },
                    },
                    { type: "ETHERNET", ethernet_details: { active: false } },
                ],
                status: { category: "AVAILABLE" },
            },
        };
        server
            .mockEndpoint()
            .get("/v2/devices/device_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.devices.get({
            device_id: "device_id",
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            device: {
                id: "device:995CS397A6475287",
                attributes: {
                    type: "TERMINAL",
                    manufacturer: "Square",
                    model: "T2",
                    name: "Square Terminal 995",
                    manufacturers_id: "995CS397A6475287",
                    updated_at: "2023-09-29T13:12:22.365049321Z",
                    version: "5.41.0085",
                    merchant_token: "MLCHXZCBWFGDW",
                },
                components: [
                    {
                        type: "APPLICATION",
                        application_details: {
                            application_type: "TERMINAL_API",
                            version: "6.25",
                            session_location: "LMN2K7S3RTOU3",
                        },
                    },
                    {
                        type: "CARD_READER",
                        card_reader_details: {
                            version: "3.53.70",
                        },
                    },
                    {
                        type: "BATTERY",
                        battery_details: {
                            visible_percent: 5,
                            external_power: "AVAILABLE_CHARGING",
                        },
                    },
                    {
                        type: "WIFI",
                        wifi_details: {
                            active: true,
                            ssid: "Staff Network",
                            ip_address_v4: "10.0.0.7",
                            secure_connection: "WPA/WPA2 PSK",
                            signal_strength: {
                                value: 2,
                            },
                        },
                    },
                    {
                        type: "ETHERNET",
                        ethernet_details: {
                            active: false,
                        },
                    },
                ],
                status: {
                    category: "AVAILABLE",
                },
            },
        });
    });
});
