/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         item_ids: ["H42BRLUJ5KTZTTMPVSLFAACQ", "2JXOBJIHCWBQ4NZ3RIXQGJA6"],
 *         modifier_lists_to_enable: ["H42BRLUJ5KTZTTMPVSLFAACQ", "2JXOBJIHCWBQ4NZ3RIXQGJA6"],
 *         modifier_lists_to_disable: ["7WRC16CJZDVLSNDQ35PP6YAD"]
 *     }
 */
export interface UpdateItemModifierListsRequest {
    /** The IDs of the catalog items associated with the CatalogModifierList objects being updated. */
    item_ids: string[];
    /**
     * The IDs of the CatalogModifierList objects to enable for the CatalogItem.
     * At least one of `modifier_lists_to_enable` or `modifier_lists_to_disable` must be specified.
     */
    modifier_lists_to_enable?: string[] | null;
    /**
     * The IDs of the CatalogModifierList objects to disable for the CatalogItem.
     * At least one of `modifier_lists_to_enable` or `modifier_lists_to_disable` must be specified.
     */
    modifier_lists_to_disable?: string[] | null;
}
