import { array, lazy, object, optional, Schema, string } from '../schema';
import { Money, moneySchema } from './money';
import { ProcessingFee, processingFeeSchema } from './processingFee';

/**
 * Represents a refund of a payment made using Square. Contains information on
 * the original payment and the amount of money refunded.
 */
export interface PaymentRefund {
  /** Unique ID for this refund, generated by Square. */
  id: string;
  /**
   * The refund's status:
   * - `PENDING` - awaiting approval
   * - `COMPLETED` - successfully completed
   * - `REJECTED` - the refund was rejected
   * - `FAILED` - an error occurred
   */
  status?: string;
  /** Location ID associated with the payment this refund is attached to. */
  locationId?: string;
  /**
   * Represents an amount of money. `Money` fields can be signed or unsigned.
   * Fields that do not explicitly define whether they are signed or unsigned are
   * considered unsigned and can only hold positive amounts. For signed fields, the
   * sign of the value indicates the purpose of the money transfer. See
   * [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
   * for more information.
   */
  amountMoney: Money;
  /**
   * Represents an amount of money. `Money` fields can be signed or unsigned.
   * Fields that do not explicitly define whether they are signed or unsigned are
   * considered unsigned and can only hold positive amounts. For signed fields, the
   * sign of the value indicates the purpose of the money transfer. See
   * [Working with Monetary Amounts](https://developer.squareup.com/docs/build-basics/working-with-monetary-amounts)
   * for more information.
   */
  appFeeMoney?: Money;
  /** Processing fees and fee adjustments assessed by Square on this refund. */
  processingFee?: ProcessingFee[];
  /** The ID of the payment assocated with this refund. */
  paymentId?: string;
  /** The ID of the order associated with the refund. */
  orderId?: string;
  /** The reason for the refund. */
  reason?: string;
  /** Timestamp of when the refund was created, in RFC 3339 format. */
  createdAt?: string;
  /** Timestamp of when the refund was last updated, in RFC 3339 format. */
  updatedAt?: string;
}

export const paymentRefundSchema: Schema<PaymentRefund> = object({
  id: ['id', string()],
  status: ['status', optional(string())],
  locationId: ['location_id', optional(string())],
  amountMoney: ['amount_money', lazy(() => moneySchema)],
  appFeeMoney: ['app_fee_money', optional(lazy(() => moneySchema))],
  processingFee: [
    'processing_fee',
    optional(array(lazy(() => processingFeeSchema))),
  ],
  paymentId: ['payment_id', optional(string())],
  orderId: ['order_id', optional(string())],
  reason: ['reason', optional(string())],
  createdAt: ['created_at', optional(string())],
  updatedAt: ['updated_at', optional(string())],
});
