// This file was auto-generated by Fern from our API Definition.

import { SquareClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";

describe("Codes", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            device_codes: [
                {
                    id: "B3Z6NAMYQSMTM",
                    name: "Counter 1",
                    code: "EBCARJ",
                    device_id: "907CS13101300122",
                    product_type: "TERMINAL_API",
                    location_id: "B5E4484SHHNYH",
                    status: "PAIRED",
                    pair_by: "2020-02-06T18:49:33.000Z",
                    created_at: "2020-02-06T18:44:33.000Z",
                    status_changed_at: "2020-02-06T18:47:28.000Z",
                    paired_at: "paired_at",
                },
                {
                    id: "YKGMJMYK8H4PQ",
                    name: "Unused device code",
                    code: "GVXNYN",
                    device_id: "device_id",
                    product_type: "TERMINAL_API",
                    location_id: "A6SYFRSV4WAFW",
                    status: "UNPAIRED",
                    pair_by: "2020-02-07T20:00:04.000Z",
                    created_at: "2020-02-07T19:55:04.000Z",
                    status_changed_at: "2020-02-07T19:55:04.000Z",
                    paired_at: "paired_at",
                },
            ],
            cursor: "cursor",
        };
        server.mockEndpoint().get("/v2/devices/codes").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const expected = {
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            deviceCodes: [
                {
                    id: "B3Z6NAMYQSMTM",
                    name: "Counter 1",
                    code: "EBCARJ",
                    deviceId: "907CS13101300122",
                    productType: "TERMINAL_API",
                    locationId: "B5E4484SHHNYH",
                    status: "PAIRED",
                    pairBy: "2020-02-06T18:49:33.000Z",
                    createdAt: "2020-02-06T18:44:33.000Z",
                    statusChangedAt: "2020-02-06T18:47:28.000Z",
                    pairedAt: "paired_at",
                },
                {
                    id: "YKGMJMYK8H4PQ",
                    name: "Unused device code",
                    code: "GVXNYN",
                    deviceId: "device_id",
                    productType: "TERMINAL_API",
                    locationId: "A6SYFRSV4WAFW",
                    status: "UNPAIRED",
                    pairBy: "2020-02-07T20:00:04.000Z",
                    createdAt: "2020-02-07T19:55:04.000Z",
                    statusChangedAt: "2020-02-07T19:55:04.000Z",
                    pairedAt: "paired_at",
                },
            ],
            cursor: "cursor",
        };
        const page = await client.devices.codes.list({
            cursor: "cursor",
            locationId: "location_id",
            productType: "TERMINAL_API",
            status: "UNKNOWN",
        });

        expect(expected.deviceCodes).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.deviceCodes).toEqual(nextPage.data);
    });

    test("create", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ token: "test", environment: server.baseUrl });
        const rawRequestBody = {
            idempotency_key: "01bb00a6-0c86-4770-94ed-f5fca973cd56",
            device_code: { name: "Counter 1", product_type: "TERMINAL_API", location_id: "B5E4484SHHNYH" },
        };
        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            device_code: {
                id: "B3Z6NAMYQSMTM",
                name: "Counter 1",
                code: "EBCARJ",
                device_id: "device_id",
                product_type: "TERMINAL_API",
                location_id: "B5E4484SHHNYH",
                status: "UNPAIRED",
                pair_by: "2020-02-06T18:49:33.000Z",
                created_at: "2020-02-06T18:44:33.000Z",
                status_changed_at: "2020-02-06T18:44:33.000Z",
                paired_at: "paired_at",
            },
        };
        server
            .mockEndpoint()
            .post("/v2/devices/codes")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.devices.codes.create({
            idempotencyKey: "01bb00a6-0c86-4770-94ed-f5fca973cd56",
            deviceCode: {
                name: "Counter 1",
                productType: "TERMINAL_API",
                locationId: "B5E4484SHHNYH",
            },
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            deviceCode: {
                id: "B3Z6NAMYQSMTM",
                name: "Counter 1",
                code: "EBCARJ",
                deviceId: "device_id",
                productType: "TERMINAL_API",
                locationId: "B5E4484SHHNYH",
                status: "UNPAIRED",
                pairBy: "2020-02-06T18:49:33.000Z",
                createdAt: "2020-02-06T18:44:33.000Z",
                statusChangedAt: "2020-02-06T18:44:33.000Z",
                pairedAt: "paired_at",
            },
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new SquareClient({ token: "test", environment: server.baseUrl });

        const rawResponseBody = {
            errors: [{ category: "API_ERROR", code: "INTERNAL_SERVER_ERROR", detail: "detail", field: "field" }],
            device_code: {
                id: "B3Z6NAMYQSMTM",
                name: "Counter 1",
                code: "EBCARJ",
                device_id: "907CS13101300122",
                product_type: "TERMINAL_API",
                location_id: "B5E4484SHHNYH",
                status: "PAIRED",
                pair_by: "2020-02-06T18:49:33.000Z",
                created_at: "2020-02-06T18:44:33.000Z",
                status_changed_at: "2020-02-06T18:47:28.000Z",
                paired_at: "paired_at",
            },
        };
        server
            .mockEndpoint()
            .get("/v2/devices/codes/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.devices.codes.get({
            id: "id",
        });
        expect(response).toEqual({
            errors: [
                {
                    category: "API_ERROR",
                    code: "INTERNAL_SERVER_ERROR",
                    detail: "detail",
                    field: "field",
                },
            ],
            deviceCode: {
                id: "B3Z6NAMYQSMTM",
                name: "Counter 1",
                code: "EBCARJ",
                deviceId: "907CS13101300122",
                productType: "TERMINAL_API",
                locationId: "B5E4484SHHNYH",
                status: "PAIRED",
                pairBy: "2020-02-06T18:49:33.000Z",
                createdAt: "2020-02-06T18:44:33.000Z",
                statusChangedAt: "2020-02-06T18:47:28.000Z",
                pairedAt: "paired_at",
            },
        });
    });
});
