// This file was auto-generated by Fern from our API Definition.

import type * as Square from "../../../../../api/index";
import * as core from "../../../../../core";
import type * as serializers from "../../../../index";

export const CompletePaymentRequest: core.serialization.Schema<
    serializers.CompletePaymentRequest.Raw,
    Omit<Square.CompletePaymentRequest, "paymentId">
> = core.serialization.object({
    versionToken: core.serialization.property("version_token", core.serialization.string().optionalNullable()),
});

export declare namespace CompletePaymentRequest {
    export interface Raw {
        version_token?: (string | null | undefined) | null;
    }
}
