/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as Square from "../../../../../api/index";
import * as core from "../../../../../core";

export const ChangeBillingAnchorDateRequest: core.serialization.Schema<
    serializers.ChangeBillingAnchorDateRequest.Raw,
    Omit<Square.ChangeBillingAnchorDateRequest, "subscriptionId">
> = core.serialization.object({
    monthlyBillingAnchorDate: core.serialization.property(
        "monthly_billing_anchor_date",
        core.serialization.number().optionalNullable(),
    ),
    effectiveDate: core.serialization.property("effective_date", core.serialization.string().optionalNullable()),
});

export declare namespace ChangeBillingAnchorDateRequest {
    export interface Raw {
        monthly_billing_anchor_date?: (number | null) | null;
        effective_date?: (string | null) | null;
    }
}
